#!/usr/bin/env bash

EXTRA_ARGS=""

export BIGFRAME_HOME=$(cd "$(dirname $0)/.." 2>&1 >/dev/null ; pwd)

java -Xmx1200m -XX:MaxPermSize=350m -XX:ReservedCodeCacheSize=128m $EXTRA_ARGS -jar $BIGFRAME_HOME/sbt/sbt-launch.jar "$@"
