/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Cataglog_Sales extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Cataglog_Sales\",\"namespace\":\"bigframe.avro\",\"fields\":[{\"name\":\"cs_sold_date_sk\",\"type\":\"int\"},{\"name\":\"cs_sold_time_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_date_sk\",\"type\":\"int\"},{\"name\":\"cs_bill_customer_sk\",\"type\":\"int\"},{\"name\":\"cs_bill_cdemo_sk\",\"type\":\"int\"},{\"name\":\"cs_bill_hdemo_sk\",\"type\":\"int\"},{\"name\":\"cs_bill_addr_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_customer_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_cdemo_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_hdemo_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_addr_sk\",\"type\":\"int\"},{\"name\":\"cs_call_center_sk\",\"type\":\"int\"},{\"name\":\"cs_catalog_page_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_mode_sk\",\"type\":\"int\"},{\"name\":\"cs_warehouse_sk\",\"type\":\"int\"},{\"name\":\"cs_item_sk\",\"type\":\"int\"},{\"name\":\"cs_promo_sk\",\"type\":\"int\"},{\"name\":\"cs_order_number\",\"type\":\"int\"},{\"name\":\"cs_quantity\",\"type\":\"int\"},{\"name\":\"cs_wholesale_cost\",\"type\":\"float\"},{\"name\":\"cs_list_price\",\"type\":\"float\"},{\"name\":\"cs_sales_price\",\"type\":\"float\"},{\"name\":\"cs_ext_discount_amt\",\"type\":\"float\"},{\"name\":\"cs_ext_sales_price\",\"type\":\"float\"},{\"name\":\"cs_ext_wholesale_cost\",\"type\":\"float\"},{\"name\":\"cs_ext_list_price\",\"type\":\"float\"},{\"name\":\"cs_ext_tax\",\"type\":\"float\"},{\"name\":\"cs_coupon_amt\",\"type\":\"float\"},{\"name\":\"cs_ext_ship_cost\",\"type\":\"float\"},{\"name\":\"cs_net_paid\",\"type\":\"float\"},{\"name\":\"cs_net_paid_inc_tax\",\"type\":\"float\"},{\"name\":\"cs_net_paid_inc_ship\",\"type\":\"float\"},{\"name\":\"cs_net_paid_inc_ship_tax\",\"type\":\"float\"},{\"name\":\"cs_net_profit\",\"type\":\"float\"}]}");
  @Deprecated public int cs_sold_date_sk;
  @Deprecated public int cs_sold_time_sk;
  @Deprecated public int cs_ship_date_sk;
  @Deprecated public int cs_bill_customer_sk;
  @Deprecated public int cs_bill_cdemo_sk;
  @Deprecated public int cs_bill_hdemo_sk;
  @Deprecated public int cs_bill_addr_sk;
  @Deprecated public int cs_ship_customer_sk;
  @Deprecated public int cs_ship_cdemo_sk;
  @Deprecated public int cs_ship_hdemo_sk;
  @Deprecated public int cs_ship_addr_sk;
  @Deprecated public int cs_call_center_sk;
  @Deprecated public int cs_catalog_page_sk;
  @Deprecated public int cs_ship_mode_sk;
  @Deprecated public int cs_warehouse_sk;
  @Deprecated public int cs_item_sk;
  @Deprecated public int cs_promo_sk;
  @Deprecated public int cs_order_number;
  @Deprecated public int cs_quantity;
  @Deprecated public float cs_wholesale_cost;
  @Deprecated public float cs_list_price;
  @Deprecated public float cs_sales_price;
  @Deprecated public float cs_ext_discount_amt;
  @Deprecated public float cs_ext_sales_price;
  @Deprecated public float cs_ext_wholesale_cost;
  @Deprecated public float cs_ext_list_price;
  @Deprecated public float cs_ext_tax;
  @Deprecated public float cs_coupon_amt;
  @Deprecated public float cs_ext_ship_cost;
  @Deprecated public float cs_net_paid;
  @Deprecated public float cs_net_paid_inc_tax;
  @Deprecated public float cs_net_paid_inc_ship;
  @Deprecated public float cs_net_paid_inc_ship_tax;
  @Deprecated public float cs_net_profit;

  /**
   * Default constructor.
   */
  public Cataglog_Sales() {}

  /**
   * All-args constructor.
   */
  public Cataglog_Sales(java.lang.Integer cs_sold_date_sk, java.lang.Integer cs_sold_time_sk, java.lang.Integer cs_ship_date_sk, java.lang.Integer cs_bill_customer_sk, java.lang.Integer cs_bill_cdemo_sk, java.lang.Integer cs_bill_hdemo_sk, java.lang.Integer cs_bill_addr_sk, java.lang.Integer cs_ship_customer_sk, java.lang.Integer cs_ship_cdemo_sk, java.lang.Integer cs_ship_hdemo_sk, java.lang.Integer cs_ship_addr_sk, java.lang.Integer cs_call_center_sk, java.lang.Integer cs_catalog_page_sk, java.lang.Integer cs_ship_mode_sk, java.lang.Integer cs_warehouse_sk, java.lang.Integer cs_item_sk, java.lang.Integer cs_promo_sk, java.lang.Integer cs_order_number, java.lang.Integer cs_quantity, java.lang.Float cs_wholesale_cost, java.lang.Float cs_list_price, java.lang.Float cs_sales_price, java.lang.Float cs_ext_discount_amt, java.lang.Float cs_ext_sales_price, java.lang.Float cs_ext_wholesale_cost, java.lang.Float cs_ext_list_price, java.lang.Float cs_ext_tax, java.lang.Float cs_coupon_amt, java.lang.Float cs_ext_ship_cost, java.lang.Float cs_net_paid, java.lang.Float cs_net_paid_inc_tax, java.lang.Float cs_net_paid_inc_ship, java.lang.Float cs_net_paid_inc_ship_tax, java.lang.Float cs_net_profit) {
    this.cs_sold_date_sk = cs_sold_date_sk;
    this.cs_sold_time_sk = cs_sold_time_sk;
    this.cs_ship_date_sk = cs_ship_date_sk;
    this.cs_bill_customer_sk = cs_bill_customer_sk;
    this.cs_bill_cdemo_sk = cs_bill_cdemo_sk;
    this.cs_bill_hdemo_sk = cs_bill_hdemo_sk;
    this.cs_bill_addr_sk = cs_bill_addr_sk;
    this.cs_ship_customer_sk = cs_ship_customer_sk;
    this.cs_ship_cdemo_sk = cs_ship_cdemo_sk;
    this.cs_ship_hdemo_sk = cs_ship_hdemo_sk;
    this.cs_ship_addr_sk = cs_ship_addr_sk;
    this.cs_call_center_sk = cs_call_center_sk;
    this.cs_catalog_page_sk = cs_catalog_page_sk;
    this.cs_ship_mode_sk = cs_ship_mode_sk;
    this.cs_warehouse_sk = cs_warehouse_sk;
    this.cs_item_sk = cs_item_sk;
    this.cs_promo_sk = cs_promo_sk;
    this.cs_order_number = cs_order_number;
    this.cs_quantity = cs_quantity;
    this.cs_wholesale_cost = cs_wholesale_cost;
    this.cs_list_price = cs_list_price;
    this.cs_sales_price = cs_sales_price;
    this.cs_ext_discount_amt = cs_ext_discount_amt;
    this.cs_ext_sales_price = cs_ext_sales_price;
    this.cs_ext_wholesale_cost = cs_ext_wholesale_cost;
    this.cs_ext_list_price = cs_ext_list_price;
    this.cs_ext_tax = cs_ext_tax;
    this.cs_coupon_amt = cs_coupon_amt;
    this.cs_ext_ship_cost = cs_ext_ship_cost;
    this.cs_net_paid = cs_net_paid;
    this.cs_net_paid_inc_tax = cs_net_paid_inc_tax;
    this.cs_net_paid_inc_ship = cs_net_paid_inc_ship;
    this.cs_net_paid_inc_ship_tax = cs_net_paid_inc_ship_tax;
    this.cs_net_profit = cs_net_profit;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cs_sold_date_sk;
    case 1: return cs_sold_time_sk;
    case 2: return cs_ship_date_sk;
    case 3: return cs_bill_customer_sk;
    case 4: return cs_bill_cdemo_sk;
    case 5: return cs_bill_hdemo_sk;
    case 6: return cs_bill_addr_sk;
    case 7: return cs_ship_customer_sk;
    case 8: return cs_ship_cdemo_sk;
    case 9: return cs_ship_hdemo_sk;
    case 10: return cs_ship_addr_sk;
    case 11: return cs_call_center_sk;
    case 12: return cs_catalog_page_sk;
    case 13: return cs_ship_mode_sk;
    case 14: return cs_warehouse_sk;
    case 15: return cs_item_sk;
    case 16: return cs_promo_sk;
    case 17: return cs_order_number;
    case 18: return cs_quantity;
    case 19: return cs_wholesale_cost;
    case 20: return cs_list_price;
    case 21: return cs_sales_price;
    case 22: return cs_ext_discount_amt;
    case 23: return cs_ext_sales_price;
    case 24: return cs_ext_wholesale_cost;
    case 25: return cs_ext_list_price;
    case 26: return cs_ext_tax;
    case 27: return cs_coupon_amt;
    case 28: return cs_ext_ship_cost;
    case 29: return cs_net_paid;
    case 30: return cs_net_paid_inc_tax;
    case 31: return cs_net_paid_inc_ship;
    case 32: return cs_net_paid_inc_ship_tax;
    case 33: return cs_net_profit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cs_sold_date_sk = (java.lang.Integer)value$; break;
    case 1: cs_sold_time_sk = (java.lang.Integer)value$; break;
    case 2: cs_ship_date_sk = (java.lang.Integer)value$; break;
    case 3: cs_bill_customer_sk = (java.lang.Integer)value$; break;
    case 4: cs_bill_cdemo_sk = (java.lang.Integer)value$; break;
    case 5: cs_bill_hdemo_sk = (java.lang.Integer)value$; break;
    case 6: cs_bill_addr_sk = (java.lang.Integer)value$; break;
    case 7: cs_ship_customer_sk = (java.lang.Integer)value$; break;
    case 8: cs_ship_cdemo_sk = (java.lang.Integer)value$; break;
    case 9: cs_ship_hdemo_sk = (java.lang.Integer)value$; break;
    case 10: cs_ship_addr_sk = (java.lang.Integer)value$; break;
    case 11: cs_call_center_sk = (java.lang.Integer)value$; break;
    case 12: cs_catalog_page_sk = (java.lang.Integer)value$; break;
    case 13: cs_ship_mode_sk = (java.lang.Integer)value$; break;
    case 14: cs_warehouse_sk = (java.lang.Integer)value$; break;
    case 15: cs_item_sk = (java.lang.Integer)value$; break;
    case 16: cs_promo_sk = (java.lang.Integer)value$; break;
    case 17: cs_order_number = (java.lang.Integer)value$; break;
    case 18: cs_quantity = (java.lang.Integer)value$; break;
    case 19: cs_wholesale_cost = (java.lang.Float)value$; break;
    case 20: cs_list_price = (java.lang.Float)value$; break;
    case 21: cs_sales_price = (java.lang.Float)value$; break;
    case 22: cs_ext_discount_amt = (java.lang.Float)value$; break;
    case 23: cs_ext_sales_price = (java.lang.Float)value$; break;
    case 24: cs_ext_wholesale_cost = (java.lang.Float)value$; break;
    case 25: cs_ext_list_price = (java.lang.Float)value$; break;
    case 26: cs_ext_tax = (java.lang.Float)value$; break;
    case 27: cs_coupon_amt = (java.lang.Float)value$; break;
    case 28: cs_ext_ship_cost = (java.lang.Float)value$; break;
    case 29: cs_net_paid = (java.lang.Float)value$; break;
    case 30: cs_net_paid_inc_tax = (java.lang.Float)value$; break;
    case 31: cs_net_paid_inc_ship = (java.lang.Float)value$; break;
    case 32: cs_net_paid_inc_ship_tax = (java.lang.Float)value$; break;
    case 33: cs_net_profit = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'cs_sold_date_sk' field.
   */
  public java.lang.Integer getCsSoldDateSk() {
    return cs_sold_date_sk;
  }

  /**
   * Sets the value of the 'cs_sold_date_sk' field.
   * @param value the value to set.
   */
  public void setCsSoldDateSk(java.lang.Integer value) {
    this.cs_sold_date_sk = value;
  }

  /**
   * Gets the value of the 'cs_sold_time_sk' field.
   */
  public java.lang.Integer getCsSoldTimeSk() {
    return cs_sold_time_sk;
  }

  /**
   * Sets the value of the 'cs_sold_time_sk' field.
   * @param value the value to set.
   */
  public void setCsSoldTimeSk(java.lang.Integer value) {
    this.cs_sold_time_sk = value;
  }

  /**
   * Gets the value of the 'cs_ship_date_sk' field.
   */
  public java.lang.Integer getCsShipDateSk() {
    return cs_ship_date_sk;
  }

  /**
   * Sets the value of the 'cs_ship_date_sk' field.
   * @param value the value to set.
   */
  public void setCsShipDateSk(java.lang.Integer value) {
    this.cs_ship_date_sk = value;
  }

  /**
   * Gets the value of the 'cs_bill_customer_sk' field.
   */
  public java.lang.Integer getCsBillCustomerSk() {
    return cs_bill_customer_sk;
  }

  /**
   * Sets the value of the 'cs_bill_customer_sk' field.
   * @param value the value to set.
   */
  public void setCsBillCustomerSk(java.lang.Integer value) {
    this.cs_bill_customer_sk = value;
  }

  /**
   * Gets the value of the 'cs_bill_cdemo_sk' field.
   */
  public java.lang.Integer getCsBillCdemoSk() {
    return cs_bill_cdemo_sk;
  }

  /**
   * Sets the value of the 'cs_bill_cdemo_sk' field.
   * @param value the value to set.
   */
  public void setCsBillCdemoSk(java.lang.Integer value) {
    this.cs_bill_cdemo_sk = value;
  }

  /**
   * Gets the value of the 'cs_bill_hdemo_sk' field.
   */
  public java.lang.Integer getCsBillHdemoSk() {
    return cs_bill_hdemo_sk;
  }

  /**
   * Sets the value of the 'cs_bill_hdemo_sk' field.
   * @param value the value to set.
   */
  public void setCsBillHdemoSk(java.lang.Integer value) {
    this.cs_bill_hdemo_sk = value;
  }

  /**
   * Gets the value of the 'cs_bill_addr_sk' field.
   */
  public java.lang.Integer getCsBillAddrSk() {
    return cs_bill_addr_sk;
  }

  /**
   * Sets the value of the 'cs_bill_addr_sk' field.
   * @param value the value to set.
   */
  public void setCsBillAddrSk(java.lang.Integer value) {
    this.cs_bill_addr_sk = value;
  }

  /**
   * Gets the value of the 'cs_ship_customer_sk' field.
   */
  public java.lang.Integer getCsShipCustomerSk() {
    return cs_ship_customer_sk;
  }

  /**
   * Sets the value of the 'cs_ship_customer_sk' field.
   * @param value the value to set.
   */
  public void setCsShipCustomerSk(java.lang.Integer value) {
    this.cs_ship_customer_sk = value;
  }

  /**
   * Gets the value of the 'cs_ship_cdemo_sk' field.
   */
  public java.lang.Integer getCsShipCdemoSk() {
    return cs_ship_cdemo_sk;
  }

  /**
   * Sets the value of the 'cs_ship_cdemo_sk' field.
   * @param value the value to set.
   */
  public void setCsShipCdemoSk(java.lang.Integer value) {
    this.cs_ship_cdemo_sk = value;
  }

  /**
   * Gets the value of the 'cs_ship_hdemo_sk' field.
   */
  public java.lang.Integer getCsShipHdemoSk() {
    return cs_ship_hdemo_sk;
  }

  /**
   * Sets the value of the 'cs_ship_hdemo_sk' field.
   * @param value the value to set.
   */
  public void setCsShipHdemoSk(java.lang.Integer value) {
    this.cs_ship_hdemo_sk = value;
  }

  /**
   * Gets the value of the 'cs_ship_addr_sk' field.
   */
  public java.lang.Integer getCsShipAddrSk() {
    return cs_ship_addr_sk;
  }

  /**
   * Sets the value of the 'cs_ship_addr_sk' field.
   * @param value the value to set.
   */
  public void setCsShipAddrSk(java.lang.Integer value) {
    this.cs_ship_addr_sk = value;
  }

  /**
   * Gets the value of the 'cs_call_center_sk' field.
   */
  public java.lang.Integer getCsCallCenterSk() {
    return cs_call_center_sk;
  }

  /**
   * Sets the value of the 'cs_call_center_sk' field.
   * @param value the value to set.
   */
  public void setCsCallCenterSk(java.lang.Integer value) {
    this.cs_call_center_sk = value;
  }

  /**
   * Gets the value of the 'cs_catalog_page_sk' field.
   */
  public java.lang.Integer getCsCatalogPageSk() {
    return cs_catalog_page_sk;
  }

  /**
   * Sets the value of the 'cs_catalog_page_sk' field.
   * @param value the value to set.
   */
  public void setCsCatalogPageSk(java.lang.Integer value) {
    this.cs_catalog_page_sk = value;
  }

  /**
   * Gets the value of the 'cs_ship_mode_sk' field.
   */
  public java.lang.Integer getCsShipModeSk() {
    return cs_ship_mode_sk;
  }

  /**
   * Sets the value of the 'cs_ship_mode_sk' field.
   * @param value the value to set.
   */
  public void setCsShipModeSk(java.lang.Integer value) {
    this.cs_ship_mode_sk = value;
  }

  /**
   * Gets the value of the 'cs_warehouse_sk' field.
   */
  public java.lang.Integer getCsWarehouseSk() {
    return cs_warehouse_sk;
  }

  /**
   * Sets the value of the 'cs_warehouse_sk' field.
   * @param value the value to set.
   */
  public void setCsWarehouseSk(java.lang.Integer value) {
    this.cs_warehouse_sk = value;
  }

  /**
   * Gets the value of the 'cs_item_sk' field.
   */
  public java.lang.Integer getCsItemSk() {
    return cs_item_sk;
  }

  /**
   * Sets the value of the 'cs_item_sk' field.
   * @param value the value to set.
   */
  public void setCsItemSk(java.lang.Integer value) {
    this.cs_item_sk = value;
  }

  /**
   * Gets the value of the 'cs_promo_sk' field.
   */
  public java.lang.Integer getCsPromoSk() {
    return cs_promo_sk;
  }

  /**
   * Sets the value of the 'cs_promo_sk' field.
   * @param value the value to set.
   */
  public void setCsPromoSk(java.lang.Integer value) {
    this.cs_promo_sk = value;
  }

  /**
   * Gets the value of the 'cs_order_number' field.
   */
  public java.lang.Integer getCsOrderNumber() {
    return cs_order_number;
  }

  /**
   * Sets the value of the 'cs_order_number' field.
   * @param value the value to set.
   */
  public void setCsOrderNumber(java.lang.Integer value) {
    this.cs_order_number = value;
  }

  /**
   * Gets the value of the 'cs_quantity' field.
   */
  public java.lang.Integer getCsQuantity() {
    return cs_quantity;
  }

  /**
   * Sets the value of the 'cs_quantity' field.
   * @param value the value to set.
   */
  public void setCsQuantity(java.lang.Integer value) {
    this.cs_quantity = value;
  }

  /**
   * Gets the value of the 'cs_wholesale_cost' field.
   */
  public java.lang.Float getCsWholesaleCost() {
    return cs_wholesale_cost;
  }

  /**
   * Sets the value of the 'cs_wholesale_cost' field.
   * @param value the value to set.
   */
  public void setCsWholesaleCost(java.lang.Float value) {
    this.cs_wholesale_cost = value;
  }

  /**
   * Gets the value of the 'cs_list_price' field.
   */
  public java.lang.Float getCsListPrice() {
    return cs_list_price;
  }

  /**
   * Sets the value of the 'cs_list_price' field.
   * @param value the value to set.
   */
  public void setCsListPrice(java.lang.Float value) {
    this.cs_list_price = value;
  }

  /**
   * Gets the value of the 'cs_sales_price' field.
   */
  public java.lang.Float getCsSalesPrice() {
    return cs_sales_price;
  }

  /**
   * Sets the value of the 'cs_sales_price' field.
   * @param value the value to set.
   */
  public void setCsSalesPrice(java.lang.Float value) {
    this.cs_sales_price = value;
  }

  /**
   * Gets the value of the 'cs_ext_discount_amt' field.
   */
  public java.lang.Float getCsExtDiscountAmt() {
    return cs_ext_discount_amt;
  }

  /**
   * Sets the value of the 'cs_ext_discount_amt' field.
   * @param value the value to set.
   */
  public void setCsExtDiscountAmt(java.lang.Float value) {
    this.cs_ext_discount_amt = value;
  }

  /**
   * Gets the value of the 'cs_ext_sales_price' field.
   */
  public java.lang.Float getCsExtSalesPrice() {
    return cs_ext_sales_price;
  }

  /**
   * Sets the value of the 'cs_ext_sales_price' field.
   * @param value the value to set.
   */
  public void setCsExtSalesPrice(java.lang.Float value) {
    this.cs_ext_sales_price = value;
  }

  /**
   * Gets the value of the 'cs_ext_wholesale_cost' field.
   */
  public java.lang.Float getCsExtWholesaleCost() {
    return cs_ext_wholesale_cost;
  }

  /**
   * Sets the value of the 'cs_ext_wholesale_cost' field.
   * @param value the value to set.
   */
  public void setCsExtWholesaleCost(java.lang.Float value) {
    this.cs_ext_wholesale_cost = value;
  }

  /**
   * Gets the value of the 'cs_ext_list_price' field.
   */
  public java.lang.Float getCsExtListPrice() {
    return cs_ext_list_price;
  }

  /**
   * Sets the value of the 'cs_ext_list_price' field.
   * @param value the value to set.
   */
  public void setCsExtListPrice(java.lang.Float value) {
    this.cs_ext_list_price = value;
  }

  /**
   * Gets the value of the 'cs_ext_tax' field.
   */
  public java.lang.Float getCsExtTax() {
    return cs_ext_tax;
  }

  /**
   * Sets the value of the 'cs_ext_tax' field.
   * @param value the value to set.
   */
  public void setCsExtTax(java.lang.Float value) {
    this.cs_ext_tax = value;
  }

  /**
   * Gets the value of the 'cs_coupon_amt' field.
   */
  public java.lang.Float getCsCouponAmt() {
    return cs_coupon_amt;
  }

  /**
   * Sets the value of the 'cs_coupon_amt' field.
   * @param value the value to set.
   */
  public void setCsCouponAmt(java.lang.Float value) {
    this.cs_coupon_amt = value;
  }

  /**
   * Gets the value of the 'cs_ext_ship_cost' field.
   */
  public java.lang.Float getCsExtShipCost() {
    return cs_ext_ship_cost;
  }

  /**
   * Sets the value of the 'cs_ext_ship_cost' field.
   * @param value the value to set.
   */
  public void setCsExtShipCost(java.lang.Float value) {
    this.cs_ext_ship_cost = value;
  }

  /**
   * Gets the value of the 'cs_net_paid' field.
   */
  public java.lang.Float getCsNetPaid() {
    return cs_net_paid;
  }

  /**
   * Sets the value of the 'cs_net_paid' field.
   * @param value the value to set.
   */
  public void setCsNetPaid(java.lang.Float value) {
    this.cs_net_paid = value;
  }

  /**
   * Gets the value of the 'cs_net_paid_inc_tax' field.
   */
  public java.lang.Float getCsNetPaidIncTax() {
    return cs_net_paid_inc_tax;
  }

  /**
   * Sets the value of the 'cs_net_paid_inc_tax' field.
   * @param value the value to set.
   */
  public void setCsNetPaidIncTax(java.lang.Float value) {
    this.cs_net_paid_inc_tax = value;
  }

  /**
   * Gets the value of the 'cs_net_paid_inc_ship' field.
   */
  public java.lang.Float getCsNetPaidIncShip() {
    return cs_net_paid_inc_ship;
  }

  /**
   * Sets the value of the 'cs_net_paid_inc_ship' field.
   * @param value the value to set.
   */
  public void setCsNetPaidIncShip(java.lang.Float value) {
    this.cs_net_paid_inc_ship = value;
  }

  /**
   * Gets the value of the 'cs_net_paid_inc_ship_tax' field.
   */
  public java.lang.Float getCsNetPaidIncShipTax() {
    return cs_net_paid_inc_ship_tax;
  }

  /**
   * Sets the value of the 'cs_net_paid_inc_ship_tax' field.
   * @param value the value to set.
   */
  public void setCsNetPaidIncShipTax(java.lang.Float value) {
    this.cs_net_paid_inc_ship_tax = value;
  }

  /**
   * Gets the value of the 'cs_net_profit' field.
   */
  public java.lang.Float getCsNetProfit() {
    return cs_net_profit;
  }

  /**
   * Sets the value of the 'cs_net_profit' field.
   * @param value the value to set.
   */
  public void setCsNetProfit(java.lang.Float value) {
    this.cs_net_profit = value;
  }

  /** Creates a new Cataglog_Sales RecordBuilder */
  public static bigframe.avro.Cataglog_Sales.Builder newBuilder() {
    return new bigframe.avro.Cataglog_Sales.Builder();
  }
  
  /** Creates a new Cataglog_Sales RecordBuilder by copying an existing Builder */
  public static bigframe.avro.Cataglog_Sales.Builder newBuilder(bigframe.avro.Cataglog_Sales.Builder other) {
    return new bigframe.avro.Cataglog_Sales.Builder(other);
  }
  
  /** Creates a new Cataglog_Sales RecordBuilder by copying an existing Cataglog_Sales instance */
  public static bigframe.avro.Cataglog_Sales.Builder newBuilder(bigframe.avro.Cataglog_Sales other) {
    return new bigframe.avro.Cataglog_Sales.Builder(other);
  }
  
  /**
   * RecordBuilder for Cataglog_Sales instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Cataglog_Sales>
    implements org.apache.avro.data.RecordBuilder<Cataglog_Sales> {

    private int cs_sold_date_sk;
    private int cs_sold_time_sk;
    private int cs_ship_date_sk;
    private int cs_bill_customer_sk;
    private int cs_bill_cdemo_sk;
    private int cs_bill_hdemo_sk;
    private int cs_bill_addr_sk;
    private int cs_ship_customer_sk;
    private int cs_ship_cdemo_sk;
    private int cs_ship_hdemo_sk;
    private int cs_ship_addr_sk;
    private int cs_call_center_sk;
    private int cs_catalog_page_sk;
    private int cs_ship_mode_sk;
    private int cs_warehouse_sk;
    private int cs_item_sk;
    private int cs_promo_sk;
    private int cs_order_number;
    private int cs_quantity;
    private float cs_wholesale_cost;
    private float cs_list_price;
    private float cs_sales_price;
    private float cs_ext_discount_amt;
    private float cs_ext_sales_price;
    private float cs_ext_wholesale_cost;
    private float cs_ext_list_price;
    private float cs_ext_tax;
    private float cs_coupon_amt;
    private float cs_ext_ship_cost;
    private float cs_net_paid;
    private float cs_net_paid_inc_tax;
    private float cs_net_paid_inc_ship;
    private float cs_net_paid_inc_ship_tax;
    private float cs_net_profit;

    /** Creates a new Builder */
    private Builder() {
      super(bigframe.avro.Cataglog_Sales.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(bigframe.avro.Cataglog_Sales.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Cataglog_Sales instance */
    private Builder(bigframe.avro.Cataglog_Sales other) {
            super(bigframe.avro.Cataglog_Sales.SCHEMA$);
      if (isValidValue(fields()[0], other.cs_sold_date_sk)) {
        this.cs_sold_date_sk = data().deepCopy(fields()[0].schema(), other.cs_sold_date_sk);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cs_sold_time_sk)) {
        this.cs_sold_time_sk = data().deepCopy(fields()[1].schema(), other.cs_sold_time_sk);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cs_ship_date_sk)) {
        this.cs_ship_date_sk = data().deepCopy(fields()[2].schema(), other.cs_ship_date_sk);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.cs_bill_customer_sk)) {
        this.cs_bill_customer_sk = data().deepCopy(fields()[3].schema(), other.cs_bill_customer_sk);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cs_bill_cdemo_sk)) {
        this.cs_bill_cdemo_sk = data().deepCopy(fields()[4].schema(), other.cs_bill_cdemo_sk);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.cs_bill_hdemo_sk)) {
        this.cs_bill_hdemo_sk = data().deepCopy(fields()[5].schema(), other.cs_bill_hdemo_sk);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.cs_bill_addr_sk)) {
        this.cs_bill_addr_sk = data().deepCopy(fields()[6].schema(), other.cs_bill_addr_sk);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.cs_ship_customer_sk)) {
        this.cs_ship_customer_sk = data().deepCopy(fields()[7].schema(), other.cs_ship_customer_sk);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.cs_ship_cdemo_sk)) {
        this.cs_ship_cdemo_sk = data().deepCopy(fields()[8].schema(), other.cs_ship_cdemo_sk);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.cs_ship_hdemo_sk)) {
        this.cs_ship_hdemo_sk = data().deepCopy(fields()[9].schema(), other.cs_ship_hdemo_sk);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.cs_ship_addr_sk)) {
        this.cs_ship_addr_sk = data().deepCopy(fields()[10].schema(), other.cs_ship_addr_sk);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.cs_call_center_sk)) {
        this.cs_call_center_sk = data().deepCopy(fields()[11].schema(), other.cs_call_center_sk);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.cs_catalog_page_sk)) {
        this.cs_catalog_page_sk = data().deepCopy(fields()[12].schema(), other.cs_catalog_page_sk);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.cs_ship_mode_sk)) {
        this.cs_ship_mode_sk = data().deepCopy(fields()[13].schema(), other.cs_ship_mode_sk);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.cs_warehouse_sk)) {
        this.cs_warehouse_sk = data().deepCopy(fields()[14].schema(), other.cs_warehouse_sk);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.cs_item_sk)) {
        this.cs_item_sk = data().deepCopy(fields()[15].schema(), other.cs_item_sk);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.cs_promo_sk)) {
        this.cs_promo_sk = data().deepCopy(fields()[16].schema(), other.cs_promo_sk);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.cs_order_number)) {
        this.cs_order_number = data().deepCopy(fields()[17].schema(), other.cs_order_number);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.cs_quantity)) {
        this.cs_quantity = data().deepCopy(fields()[18].schema(), other.cs_quantity);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.cs_wholesale_cost)) {
        this.cs_wholesale_cost = data().deepCopy(fields()[19].schema(), other.cs_wholesale_cost);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.cs_list_price)) {
        this.cs_list_price = data().deepCopy(fields()[20].schema(), other.cs_list_price);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.cs_sales_price)) {
        this.cs_sales_price = data().deepCopy(fields()[21].schema(), other.cs_sales_price);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.cs_ext_discount_amt)) {
        this.cs_ext_discount_amt = data().deepCopy(fields()[22].schema(), other.cs_ext_discount_amt);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.cs_ext_sales_price)) {
        this.cs_ext_sales_price = data().deepCopy(fields()[23].schema(), other.cs_ext_sales_price);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.cs_ext_wholesale_cost)) {
        this.cs_ext_wholesale_cost = data().deepCopy(fields()[24].schema(), other.cs_ext_wholesale_cost);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.cs_ext_list_price)) {
        this.cs_ext_list_price = data().deepCopy(fields()[25].schema(), other.cs_ext_list_price);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.cs_ext_tax)) {
        this.cs_ext_tax = data().deepCopy(fields()[26].schema(), other.cs_ext_tax);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.cs_coupon_amt)) {
        this.cs_coupon_amt = data().deepCopy(fields()[27].schema(), other.cs_coupon_amt);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.cs_ext_ship_cost)) {
        this.cs_ext_ship_cost = data().deepCopy(fields()[28].schema(), other.cs_ext_ship_cost);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.cs_net_paid)) {
        this.cs_net_paid = data().deepCopy(fields()[29].schema(), other.cs_net_paid);
        fieldSetFlags()[29] = true;
      }
      if (isValidValue(fields()[30], other.cs_net_paid_inc_tax)) {
        this.cs_net_paid_inc_tax = data().deepCopy(fields()[30].schema(), other.cs_net_paid_inc_tax);
        fieldSetFlags()[30] = true;
      }
      if (isValidValue(fields()[31], other.cs_net_paid_inc_ship)) {
        this.cs_net_paid_inc_ship = data().deepCopy(fields()[31].schema(), other.cs_net_paid_inc_ship);
        fieldSetFlags()[31] = true;
      }
      if (isValidValue(fields()[32], other.cs_net_paid_inc_ship_tax)) {
        this.cs_net_paid_inc_ship_tax = data().deepCopy(fields()[32].schema(), other.cs_net_paid_inc_ship_tax);
        fieldSetFlags()[32] = true;
      }
      if (isValidValue(fields()[33], other.cs_net_profit)) {
        this.cs_net_profit = data().deepCopy(fields()[33].schema(), other.cs_net_profit);
        fieldSetFlags()[33] = true;
      }
    }

    /** Gets the value of the 'cs_sold_date_sk' field */
    public java.lang.Integer getCsSoldDateSk() {
      return cs_sold_date_sk;
    }
    
    /** Sets the value of the 'cs_sold_date_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsSoldDateSk(int value) {
      validate(fields()[0], value);
      this.cs_sold_date_sk = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_sold_date_sk' field has been set */
    public boolean hasCsSoldDateSk() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'cs_sold_date_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsSoldDateSk() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'cs_sold_time_sk' field */
    public java.lang.Integer getCsSoldTimeSk() {
      return cs_sold_time_sk;
    }
    
    /** Sets the value of the 'cs_sold_time_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsSoldTimeSk(int value) {
      validate(fields()[1], value);
      this.cs_sold_time_sk = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_sold_time_sk' field has been set */
    public boolean hasCsSoldTimeSk() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'cs_sold_time_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsSoldTimeSk() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'cs_ship_date_sk' field */
    public java.lang.Integer getCsShipDateSk() {
      return cs_ship_date_sk;
    }
    
    /** Sets the value of the 'cs_ship_date_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsShipDateSk(int value) {
      validate(fields()[2], value);
      this.cs_ship_date_sk = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ship_date_sk' field has been set */
    public boolean hasCsShipDateSk() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'cs_ship_date_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsShipDateSk() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'cs_bill_customer_sk' field */
    public java.lang.Integer getCsBillCustomerSk() {
      return cs_bill_customer_sk;
    }
    
    /** Sets the value of the 'cs_bill_customer_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsBillCustomerSk(int value) {
      validate(fields()[3], value);
      this.cs_bill_customer_sk = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_bill_customer_sk' field has been set */
    public boolean hasCsBillCustomerSk() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'cs_bill_customer_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsBillCustomerSk() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'cs_bill_cdemo_sk' field */
    public java.lang.Integer getCsBillCdemoSk() {
      return cs_bill_cdemo_sk;
    }
    
    /** Sets the value of the 'cs_bill_cdemo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsBillCdemoSk(int value) {
      validate(fields()[4], value);
      this.cs_bill_cdemo_sk = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_bill_cdemo_sk' field has been set */
    public boolean hasCsBillCdemoSk() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'cs_bill_cdemo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsBillCdemoSk() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'cs_bill_hdemo_sk' field */
    public java.lang.Integer getCsBillHdemoSk() {
      return cs_bill_hdemo_sk;
    }
    
    /** Sets the value of the 'cs_bill_hdemo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsBillHdemoSk(int value) {
      validate(fields()[5], value);
      this.cs_bill_hdemo_sk = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_bill_hdemo_sk' field has been set */
    public boolean hasCsBillHdemoSk() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'cs_bill_hdemo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsBillHdemoSk() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'cs_bill_addr_sk' field */
    public java.lang.Integer getCsBillAddrSk() {
      return cs_bill_addr_sk;
    }
    
    /** Sets the value of the 'cs_bill_addr_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsBillAddrSk(int value) {
      validate(fields()[6], value);
      this.cs_bill_addr_sk = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_bill_addr_sk' field has been set */
    public boolean hasCsBillAddrSk() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'cs_bill_addr_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsBillAddrSk() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'cs_ship_customer_sk' field */
    public java.lang.Integer getCsShipCustomerSk() {
      return cs_ship_customer_sk;
    }
    
    /** Sets the value of the 'cs_ship_customer_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsShipCustomerSk(int value) {
      validate(fields()[7], value);
      this.cs_ship_customer_sk = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ship_customer_sk' field has been set */
    public boolean hasCsShipCustomerSk() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'cs_ship_customer_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsShipCustomerSk() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'cs_ship_cdemo_sk' field */
    public java.lang.Integer getCsShipCdemoSk() {
      return cs_ship_cdemo_sk;
    }
    
    /** Sets the value of the 'cs_ship_cdemo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsShipCdemoSk(int value) {
      validate(fields()[8], value);
      this.cs_ship_cdemo_sk = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ship_cdemo_sk' field has been set */
    public boolean hasCsShipCdemoSk() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'cs_ship_cdemo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsShipCdemoSk() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'cs_ship_hdemo_sk' field */
    public java.lang.Integer getCsShipHdemoSk() {
      return cs_ship_hdemo_sk;
    }
    
    /** Sets the value of the 'cs_ship_hdemo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsShipHdemoSk(int value) {
      validate(fields()[9], value);
      this.cs_ship_hdemo_sk = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ship_hdemo_sk' field has been set */
    public boolean hasCsShipHdemoSk() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'cs_ship_hdemo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsShipHdemoSk() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'cs_ship_addr_sk' field */
    public java.lang.Integer getCsShipAddrSk() {
      return cs_ship_addr_sk;
    }
    
    /** Sets the value of the 'cs_ship_addr_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsShipAddrSk(int value) {
      validate(fields()[10], value);
      this.cs_ship_addr_sk = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ship_addr_sk' field has been set */
    public boolean hasCsShipAddrSk() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'cs_ship_addr_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsShipAddrSk() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'cs_call_center_sk' field */
    public java.lang.Integer getCsCallCenterSk() {
      return cs_call_center_sk;
    }
    
    /** Sets the value of the 'cs_call_center_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsCallCenterSk(int value) {
      validate(fields()[11], value);
      this.cs_call_center_sk = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_call_center_sk' field has been set */
    public boolean hasCsCallCenterSk() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'cs_call_center_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsCallCenterSk() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'cs_catalog_page_sk' field */
    public java.lang.Integer getCsCatalogPageSk() {
      return cs_catalog_page_sk;
    }
    
    /** Sets the value of the 'cs_catalog_page_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsCatalogPageSk(int value) {
      validate(fields()[12], value);
      this.cs_catalog_page_sk = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_catalog_page_sk' field has been set */
    public boolean hasCsCatalogPageSk() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'cs_catalog_page_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsCatalogPageSk() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'cs_ship_mode_sk' field */
    public java.lang.Integer getCsShipModeSk() {
      return cs_ship_mode_sk;
    }
    
    /** Sets the value of the 'cs_ship_mode_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsShipModeSk(int value) {
      validate(fields()[13], value);
      this.cs_ship_mode_sk = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ship_mode_sk' field has been set */
    public boolean hasCsShipModeSk() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'cs_ship_mode_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsShipModeSk() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'cs_warehouse_sk' field */
    public java.lang.Integer getCsWarehouseSk() {
      return cs_warehouse_sk;
    }
    
    /** Sets the value of the 'cs_warehouse_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsWarehouseSk(int value) {
      validate(fields()[14], value);
      this.cs_warehouse_sk = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_warehouse_sk' field has been set */
    public boolean hasCsWarehouseSk() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'cs_warehouse_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsWarehouseSk() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'cs_item_sk' field */
    public java.lang.Integer getCsItemSk() {
      return cs_item_sk;
    }
    
    /** Sets the value of the 'cs_item_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsItemSk(int value) {
      validate(fields()[15], value);
      this.cs_item_sk = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_item_sk' field has been set */
    public boolean hasCsItemSk() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'cs_item_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsItemSk() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'cs_promo_sk' field */
    public java.lang.Integer getCsPromoSk() {
      return cs_promo_sk;
    }
    
    /** Sets the value of the 'cs_promo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsPromoSk(int value) {
      validate(fields()[16], value);
      this.cs_promo_sk = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_promo_sk' field has been set */
    public boolean hasCsPromoSk() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'cs_promo_sk' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsPromoSk() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'cs_order_number' field */
    public java.lang.Integer getCsOrderNumber() {
      return cs_order_number;
    }
    
    /** Sets the value of the 'cs_order_number' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsOrderNumber(int value) {
      validate(fields()[17], value);
      this.cs_order_number = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_order_number' field has been set */
    public boolean hasCsOrderNumber() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'cs_order_number' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsOrderNumber() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'cs_quantity' field */
    public java.lang.Integer getCsQuantity() {
      return cs_quantity;
    }
    
    /** Sets the value of the 'cs_quantity' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsQuantity(int value) {
      validate(fields()[18], value);
      this.cs_quantity = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_quantity' field has been set */
    public boolean hasCsQuantity() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'cs_quantity' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsQuantity() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'cs_wholesale_cost' field */
    public java.lang.Float getCsWholesaleCost() {
      return cs_wholesale_cost;
    }
    
    /** Sets the value of the 'cs_wholesale_cost' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsWholesaleCost(float value) {
      validate(fields()[19], value);
      this.cs_wholesale_cost = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_wholesale_cost' field has been set */
    public boolean hasCsWholesaleCost() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'cs_wholesale_cost' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsWholesaleCost() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'cs_list_price' field */
    public java.lang.Float getCsListPrice() {
      return cs_list_price;
    }
    
    /** Sets the value of the 'cs_list_price' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsListPrice(float value) {
      validate(fields()[20], value);
      this.cs_list_price = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_list_price' field has been set */
    public boolean hasCsListPrice() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'cs_list_price' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsListPrice() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'cs_sales_price' field */
    public java.lang.Float getCsSalesPrice() {
      return cs_sales_price;
    }
    
    /** Sets the value of the 'cs_sales_price' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsSalesPrice(float value) {
      validate(fields()[21], value);
      this.cs_sales_price = value;
      fieldSetFlags()[21] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_sales_price' field has been set */
    public boolean hasCsSalesPrice() {
      return fieldSetFlags()[21];
    }
    
    /** Clears the value of the 'cs_sales_price' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsSalesPrice() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /** Gets the value of the 'cs_ext_discount_amt' field */
    public java.lang.Float getCsExtDiscountAmt() {
      return cs_ext_discount_amt;
    }
    
    /** Sets the value of the 'cs_ext_discount_amt' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsExtDiscountAmt(float value) {
      validate(fields()[22], value);
      this.cs_ext_discount_amt = value;
      fieldSetFlags()[22] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ext_discount_amt' field has been set */
    public boolean hasCsExtDiscountAmt() {
      return fieldSetFlags()[22];
    }
    
    /** Clears the value of the 'cs_ext_discount_amt' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsExtDiscountAmt() {
      fieldSetFlags()[22] = false;
      return this;
    }

    /** Gets the value of the 'cs_ext_sales_price' field */
    public java.lang.Float getCsExtSalesPrice() {
      return cs_ext_sales_price;
    }
    
    /** Sets the value of the 'cs_ext_sales_price' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsExtSalesPrice(float value) {
      validate(fields()[23], value);
      this.cs_ext_sales_price = value;
      fieldSetFlags()[23] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ext_sales_price' field has been set */
    public boolean hasCsExtSalesPrice() {
      return fieldSetFlags()[23];
    }
    
    /** Clears the value of the 'cs_ext_sales_price' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsExtSalesPrice() {
      fieldSetFlags()[23] = false;
      return this;
    }

    /** Gets the value of the 'cs_ext_wholesale_cost' field */
    public java.lang.Float getCsExtWholesaleCost() {
      return cs_ext_wholesale_cost;
    }
    
    /** Sets the value of the 'cs_ext_wholesale_cost' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsExtWholesaleCost(float value) {
      validate(fields()[24], value);
      this.cs_ext_wholesale_cost = value;
      fieldSetFlags()[24] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ext_wholesale_cost' field has been set */
    public boolean hasCsExtWholesaleCost() {
      return fieldSetFlags()[24];
    }
    
    /** Clears the value of the 'cs_ext_wholesale_cost' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsExtWholesaleCost() {
      fieldSetFlags()[24] = false;
      return this;
    }

    /** Gets the value of the 'cs_ext_list_price' field */
    public java.lang.Float getCsExtListPrice() {
      return cs_ext_list_price;
    }
    
    /** Sets the value of the 'cs_ext_list_price' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsExtListPrice(float value) {
      validate(fields()[25], value);
      this.cs_ext_list_price = value;
      fieldSetFlags()[25] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ext_list_price' field has been set */
    public boolean hasCsExtListPrice() {
      return fieldSetFlags()[25];
    }
    
    /** Clears the value of the 'cs_ext_list_price' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsExtListPrice() {
      fieldSetFlags()[25] = false;
      return this;
    }

    /** Gets the value of the 'cs_ext_tax' field */
    public java.lang.Float getCsExtTax() {
      return cs_ext_tax;
    }
    
    /** Sets the value of the 'cs_ext_tax' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsExtTax(float value) {
      validate(fields()[26], value);
      this.cs_ext_tax = value;
      fieldSetFlags()[26] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ext_tax' field has been set */
    public boolean hasCsExtTax() {
      return fieldSetFlags()[26];
    }
    
    /** Clears the value of the 'cs_ext_tax' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsExtTax() {
      fieldSetFlags()[26] = false;
      return this;
    }

    /** Gets the value of the 'cs_coupon_amt' field */
    public java.lang.Float getCsCouponAmt() {
      return cs_coupon_amt;
    }
    
    /** Sets the value of the 'cs_coupon_amt' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsCouponAmt(float value) {
      validate(fields()[27], value);
      this.cs_coupon_amt = value;
      fieldSetFlags()[27] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_coupon_amt' field has been set */
    public boolean hasCsCouponAmt() {
      return fieldSetFlags()[27];
    }
    
    /** Clears the value of the 'cs_coupon_amt' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsCouponAmt() {
      fieldSetFlags()[27] = false;
      return this;
    }

    /** Gets the value of the 'cs_ext_ship_cost' field */
    public java.lang.Float getCsExtShipCost() {
      return cs_ext_ship_cost;
    }
    
    /** Sets the value of the 'cs_ext_ship_cost' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsExtShipCost(float value) {
      validate(fields()[28], value);
      this.cs_ext_ship_cost = value;
      fieldSetFlags()[28] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_ext_ship_cost' field has been set */
    public boolean hasCsExtShipCost() {
      return fieldSetFlags()[28];
    }
    
    /** Clears the value of the 'cs_ext_ship_cost' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsExtShipCost() {
      fieldSetFlags()[28] = false;
      return this;
    }

    /** Gets the value of the 'cs_net_paid' field */
    public java.lang.Float getCsNetPaid() {
      return cs_net_paid;
    }
    
    /** Sets the value of the 'cs_net_paid' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsNetPaid(float value) {
      validate(fields()[29], value);
      this.cs_net_paid = value;
      fieldSetFlags()[29] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_net_paid' field has been set */
    public boolean hasCsNetPaid() {
      return fieldSetFlags()[29];
    }
    
    /** Clears the value of the 'cs_net_paid' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsNetPaid() {
      fieldSetFlags()[29] = false;
      return this;
    }

    /** Gets the value of the 'cs_net_paid_inc_tax' field */
    public java.lang.Float getCsNetPaidIncTax() {
      return cs_net_paid_inc_tax;
    }
    
    /** Sets the value of the 'cs_net_paid_inc_tax' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsNetPaidIncTax(float value) {
      validate(fields()[30], value);
      this.cs_net_paid_inc_tax = value;
      fieldSetFlags()[30] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_net_paid_inc_tax' field has been set */
    public boolean hasCsNetPaidIncTax() {
      return fieldSetFlags()[30];
    }
    
    /** Clears the value of the 'cs_net_paid_inc_tax' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsNetPaidIncTax() {
      fieldSetFlags()[30] = false;
      return this;
    }

    /** Gets the value of the 'cs_net_paid_inc_ship' field */
    public java.lang.Float getCsNetPaidIncShip() {
      return cs_net_paid_inc_ship;
    }
    
    /** Sets the value of the 'cs_net_paid_inc_ship' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsNetPaidIncShip(float value) {
      validate(fields()[31], value);
      this.cs_net_paid_inc_ship = value;
      fieldSetFlags()[31] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_net_paid_inc_ship' field has been set */
    public boolean hasCsNetPaidIncShip() {
      return fieldSetFlags()[31];
    }
    
    /** Clears the value of the 'cs_net_paid_inc_ship' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsNetPaidIncShip() {
      fieldSetFlags()[31] = false;
      return this;
    }

    /** Gets the value of the 'cs_net_paid_inc_ship_tax' field */
    public java.lang.Float getCsNetPaidIncShipTax() {
      return cs_net_paid_inc_ship_tax;
    }
    
    /** Sets the value of the 'cs_net_paid_inc_ship_tax' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsNetPaidIncShipTax(float value) {
      validate(fields()[32], value);
      this.cs_net_paid_inc_ship_tax = value;
      fieldSetFlags()[32] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_net_paid_inc_ship_tax' field has been set */
    public boolean hasCsNetPaidIncShipTax() {
      return fieldSetFlags()[32];
    }
    
    /** Clears the value of the 'cs_net_paid_inc_ship_tax' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsNetPaidIncShipTax() {
      fieldSetFlags()[32] = false;
      return this;
    }

    /** Gets the value of the 'cs_net_profit' field */
    public java.lang.Float getCsNetProfit() {
      return cs_net_profit;
    }
    
    /** Sets the value of the 'cs_net_profit' field */
    public bigframe.avro.Cataglog_Sales.Builder setCsNetProfit(float value) {
      validate(fields()[33], value);
      this.cs_net_profit = value;
      fieldSetFlags()[33] = true;
      return this; 
    }
    
    /** Checks whether the 'cs_net_profit' field has been set */
    public boolean hasCsNetProfit() {
      return fieldSetFlags()[33];
    }
    
    /** Clears the value of the 'cs_net_profit' field */
    public bigframe.avro.Cataglog_Sales.Builder clearCsNetProfit() {
      fieldSetFlags()[33] = false;
      return this;
    }

    @Override
    public Cataglog_Sales build() {
      try {
        Cataglog_Sales record = new Cataglog_Sales();
        record.cs_sold_date_sk = fieldSetFlags()[0] ? this.cs_sold_date_sk : (java.lang.Integer) defaultValue(fields()[0]);
        record.cs_sold_time_sk = fieldSetFlags()[1] ? this.cs_sold_time_sk : (java.lang.Integer) defaultValue(fields()[1]);
        record.cs_ship_date_sk = fieldSetFlags()[2] ? this.cs_ship_date_sk : (java.lang.Integer) defaultValue(fields()[2]);
        record.cs_bill_customer_sk = fieldSetFlags()[3] ? this.cs_bill_customer_sk : (java.lang.Integer) defaultValue(fields()[3]);
        record.cs_bill_cdemo_sk = fieldSetFlags()[4] ? this.cs_bill_cdemo_sk : (java.lang.Integer) defaultValue(fields()[4]);
        record.cs_bill_hdemo_sk = fieldSetFlags()[5] ? this.cs_bill_hdemo_sk : (java.lang.Integer) defaultValue(fields()[5]);
        record.cs_bill_addr_sk = fieldSetFlags()[6] ? this.cs_bill_addr_sk : (java.lang.Integer) defaultValue(fields()[6]);
        record.cs_ship_customer_sk = fieldSetFlags()[7] ? this.cs_ship_customer_sk : (java.lang.Integer) defaultValue(fields()[7]);
        record.cs_ship_cdemo_sk = fieldSetFlags()[8] ? this.cs_ship_cdemo_sk : (java.lang.Integer) defaultValue(fields()[8]);
        record.cs_ship_hdemo_sk = fieldSetFlags()[9] ? this.cs_ship_hdemo_sk : (java.lang.Integer) defaultValue(fields()[9]);
        record.cs_ship_addr_sk = fieldSetFlags()[10] ? this.cs_ship_addr_sk : (java.lang.Integer) defaultValue(fields()[10]);
        record.cs_call_center_sk = fieldSetFlags()[11] ? this.cs_call_center_sk : (java.lang.Integer) defaultValue(fields()[11]);
        record.cs_catalog_page_sk = fieldSetFlags()[12] ? this.cs_catalog_page_sk : (java.lang.Integer) defaultValue(fields()[12]);
        record.cs_ship_mode_sk = fieldSetFlags()[13] ? this.cs_ship_mode_sk : (java.lang.Integer) defaultValue(fields()[13]);
        record.cs_warehouse_sk = fieldSetFlags()[14] ? this.cs_warehouse_sk : (java.lang.Integer) defaultValue(fields()[14]);
        record.cs_item_sk = fieldSetFlags()[15] ? this.cs_item_sk : (java.lang.Integer) defaultValue(fields()[15]);
        record.cs_promo_sk = fieldSetFlags()[16] ? this.cs_promo_sk : (java.lang.Integer) defaultValue(fields()[16]);
        record.cs_order_number = fieldSetFlags()[17] ? this.cs_order_number : (java.lang.Integer) defaultValue(fields()[17]);
        record.cs_quantity = fieldSetFlags()[18] ? this.cs_quantity : (java.lang.Integer) defaultValue(fields()[18]);
        record.cs_wholesale_cost = fieldSetFlags()[19] ? this.cs_wholesale_cost : (java.lang.Float) defaultValue(fields()[19]);
        record.cs_list_price = fieldSetFlags()[20] ? this.cs_list_price : (java.lang.Float) defaultValue(fields()[20]);
        record.cs_sales_price = fieldSetFlags()[21] ? this.cs_sales_price : (java.lang.Float) defaultValue(fields()[21]);
        record.cs_ext_discount_amt = fieldSetFlags()[22] ? this.cs_ext_discount_amt : (java.lang.Float) defaultValue(fields()[22]);
        record.cs_ext_sales_price = fieldSetFlags()[23] ? this.cs_ext_sales_price : (java.lang.Float) defaultValue(fields()[23]);
        record.cs_ext_wholesale_cost = fieldSetFlags()[24] ? this.cs_ext_wholesale_cost : (java.lang.Float) defaultValue(fields()[24]);
        record.cs_ext_list_price = fieldSetFlags()[25] ? this.cs_ext_list_price : (java.lang.Float) defaultValue(fields()[25]);
        record.cs_ext_tax = fieldSetFlags()[26] ? this.cs_ext_tax : (java.lang.Float) defaultValue(fields()[26]);
        record.cs_coupon_amt = fieldSetFlags()[27] ? this.cs_coupon_amt : (java.lang.Float) defaultValue(fields()[27]);
        record.cs_ext_ship_cost = fieldSetFlags()[28] ? this.cs_ext_ship_cost : (java.lang.Float) defaultValue(fields()[28]);
        record.cs_net_paid = fieldSetFlags()[29] ? this.cs_net_paid : (java.lang.Float) defaultValue(fields()[29]);
        record.cs_net_paid_inc_tax = fieldSetFlags()[30] ? this.cs_net_paid_inc_tax : (java.lang.Float) defaultValue(fields()[30]);
        record.cs_net_paid_inc_ship = fieldSetFlags()[31] ? this.cs_net_paid_inc_ship : (java.lang.Float) defaultValue(fields()[31]);
        record.cs_net_paid_inc_ship_tax = fieldSetFlags()[32] ? this.cs_net_paid_inc_ship_tax : (java.lang.Float) defaultValue(fields()[32]);
        record.cs_net_profit = fieldSetFlags()[33] ? this.cs_net_profit : (java.lang.Float) defaultValue(fields()[33]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
