/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Date_Dim extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Date_Dim\",\"namespace\":\"bigframe.avro\",\"fields\":[{\"name\":\"d_date_sk\",\"type\":\"int\"},{\"name\":\"d_date_id\",\"type\":\"string\"},{\"name\":\"d_date\",\"type\":\"string\"},{\"name\":\"d_month_seq\",\"type\":\"int\"},{\"name\":\"d_week_seq\",\"type\":\"int\"},{\"name\":\"d_quarter_seq\",\"type\":\"int\"},{\"name\":\"d_year\",\"type\":\"int\"},{\"name\":\"d_dow\",\"type\":\"int\"},{\"name\":\"d_moy\",\"type\":\"int\"},{\"name\":\"d_dom\",\"type\":\"int\"},{\"name\":\"d_qoy\",\"type\":\"int\"},{\"name\":\"d_fy_year\",\"type\":\"int\"},{\"name\":\"d_fy_quarter_seq\",\"type\":\"int\"},{\"name\":\"d_fy_week_seq\",\"type\":\"int\"},{\"name\":\"d_day_name\",\"type\":\"string\"},{\"name\":\"d_quarter_name\",\"type\":\"string\"},{\"name\":\"d_holiday\",\"type\":\"string\"},{\"name\":\"d_weekend\",\"type\":\"string\"},{\"name\":\"d_following_holiday\",\"type\":\"string\"},{\"name\":\"d_first_dom\",\"type\":\"int\"},{\"name\":\"d_last_dom\",\"type\":\"int\"},{\"name\":\"d_same_day_ly\",\"type\":\"int\"},{\"name\":\"d_same_day_lq\",\"type\":\"int\"},{\"name\":\"d_current_day\",\"type\":\"string\"},{\"name\":\"d_current_week\",\"type\":\"string\"},{\"name\":\"d_current_month\",\"type\":\"string\"},{\"name\":\"d_current_quarter\",\"type\":\"string\"},{\"name\":\"d_current_year\",\"type\":\"string\"}]}");
  @Deprecated public int d_date_sk;
  @Deprecated public java.lang.CharSequence d_date_id;
  @Deprecated public java.lang.CharSequence d_date;
  @Deprecated public int d_month_seq;
  @Deprecated public int d_week_seq;
  @Deprecated public int d_quarter_seq;
  @Deprecated public int d_year;
  @Deprecated public int d_dow;
  @Deprecated public int d_moy;
  @Deprecated public int d_dom;
  @Deprecated public int d_qoy;
  @Deprecated public int d_fy_year;
  @Deprecated public int d_fy_quarter_seq;
  @Deprecated public int d_fy_week_seq;
  @Deprecated public java.lang.CharSequence d_day_name;
  @Deprecated public java.lang.CharSequence d_quarter_name;
  @Deprecated public java.lang.CharSequence d_holiday;
  @Deprecated public java.lang.CharSequence d_weekend;
  @Deprecated public java.lang.CharSequence d_following_holiday;
  @Deprecated public int d_first_dom;
  @Deprecated public int d_last_dom;
  @Deprecated public int d_same_day_ly;
  @Deprecated public int d_same_day_lq;
  @Deprecated public java.lang.CharSequence d_current_day;
  @Deprecated public java.lang.CharSequence d_current_week;
  @Deprecated public java.lang.CharSequence d_current_month;
  @Deprecated public java.lang.CharSequence d_current_quarter;
  @Deprecated public java.lang.CharSequence d_current_year;

  /**
   * Default constructor.
   */
  public Date_Dim() {}

  /**
   * All-args constructor.
   */
  public Date_Dim(java.lang.Integer d_date_sk, java.lang.CharSequence d_date_id, java.lang.CharSequence d_date, java.lang.Integer d_month_seq, java.lang.Integer d_week_seq, java.lang.Integer d_quarter_seq, java.lang.Integer d_year, java.lang.Integer d_dow, java.lang.Integer d_moy, java.lang.Integer d_dom, java.lang.Integer d_qoy, java.lang.Integer d_fy_year, java.lang.Integer d_fy_quarter_seq, java.lang.Integer d_fy_week_seq, java.lang.CharSequence d_day_name, java.lang.CharSequence d_quarter_name, java.lang.CharSequence d_holiday, java.lang.CharSequence d_weekend, java.lang.CharSequence d_following_holiday, java.lang.Integer d_first_dom, java.lang.Integer d_last_dom, java.lang.Integer d_same_day_ly, java.lang.Integer d_same_day_lq, java.lang.CharSequence d_current_day, java.lang.CharSequence d_current_week, java.lang.CharSequence d_current_month, java.lang.CharSequence d_current_quarter, java.lang.CharSequence d_current_year) {
    this.d_date_sk = d_date_sk;
    this.d_date_id = d_date_id;
    this.d_date = d_date;
    this.d_month_seq = d_month_seq;
    this.d_week_seq = d_week_seq;
    this.d_quarter_seq = d_quarter_seq;
    this.d_year = d_year;
    this.d_dow = d_dow;
    this.d_moy = d_moy;
    this.d_dom = d_dom;
    this.d_qoy = d_qoy;
    this.d_fy_year = d_fy_year;
    this.d_fy_quarter_seq = d_fy_quarter_seq;
    this.d_fy_week_seq = d_fy_week_seq;
    this.d_day_name = d_day_name;
    this.d_quarter_name = d_quarter_name;
    this.d_holiday = d_holiday;
    this.d_weekend = d_weekend;
    this.d_following_holiday = d_following_holiday;
    this.d_first_dom = d_first_dom;
    this.d_last_dom = d_last_dom;
    this.d_same_day_ly = d_same_day_ly;
    this.d_same_day_lq = d_same_day_lq;
    this.d_current_day = d_current_day;
    this.d_current_week = d_current_week;
    this.d_current_month = d_current_month;
    this.d_current_quarter = d_current_quarter;
    this.d_current_year = d_current_year;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return d_date_sk;
    case 1: return d_date_id;
    case 2: return d_date;
    case 3: return d_month_seq;
    case 4: return d_week_seq;
    case 5: return d_quarter_seq;
    case 6: return d_year;
    case 7: return d_dow;
    case 8: return d_moy;
    case 9: return d_dom;
    case 10: return d_qoy;
    case 11: return d_fy_year;
    case 12: return d_fy_quarter_seq;
    case 13: return d_fy_week_seq;
    case 14: return d_day_name;
    case 15: return d_quarter_name;
    case 16: return d_holiday;
    case 17: return d_weekend;
    case 18: return d_following_holiday;
    case 19: return d_first_dom;
    case 20: return d_last_dom;
    case 21: return d_same_day_ly;
    case 22: return d_same_day_lq;
    case 23: return d_current_day;
    case 24: return d_current_week;
    case 25: return d_current_month;
    case 26: return d_current_quarter;
    case 27: return d_current_year;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: d_date_sk = (java.lang.Integer)value$; break;
    case 1: d_date_id = (java.lang.CharSequence)value$; break;
    case 2: d_date = (java.lang.CharSequence)value$; break;
    case 3: d_month_seq = (java.lang.Integer)value$; break;
    case 4: d_week_seq = (java.lang.Integer)value$; break;
    case 5: d_quarter_seq = (java.lang.Integer)value$; break;
    case 6: d_year = (java.lang.Integer)value$; break;
    case 7: d_dow = (java.lang.Integer)value$; break;
    case 8: d_moy = (java.lang.Integer)value$; break;
    case 9: d_dom = (java.lang.Integer)value$; break;
    case 10: d_qoy = (java.lang.Integer)value$; break;
    case 11: d_fy_year = (java.lang.Integer)value$; break;
    case 12: d_fy_quarter_seq = (java.lang.Integer)value$; break;
    case 13: d_fy_week_seq = (java.lang.Integer)value$; break;
    case 14: d_day_name = (java.lang.CharSequence)value$; break;
    case 15: d_quarter_name = (java.lang.CharSequence)value$; break;
    case 16: d_holiday = (java.lang.CharSequence)value$; break;
    case 17: d_weekend = (java.lang.CharSequence)value$; break;
    case 18: d_following_holiday = (java.lang.CharSequence)value$; break;
    case 19: d_first_dom = (java.lang.Integer)value$; break;
    case 20: d_last_dom = (java.lang.Integer)value$; break;
    case 21: d_same_day_ly = (java.lang.Integer)value$; break;
    case 22: d_same_day_lq = (java.lang.Integer)value$; break;
    case 23: d_current_day = (java.lang.CharSequence)value$; break;
    case 24: d_current_week = (java.lang.CharSequence)value$; break;
    case 25: d_current_month = (java.lang.CharSequence)value$; break;
    case 26: d_current_quarter = (java.lang.CharSequence)value$; break;
    case 27: d_current_year = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'd_date_sk' field.
   */
  public java.lang.Integer getDDateSk() {
    return d_date_sk;
  }

  /**
   * Sets the value of the 'd_date_sk' field.
   * @param value the value to set.
   */
  public void setDDateSk(java.lang.Integer value) {
    this.d_date_sk = value;
  }

  /**
   * Gets the value of the 'd_date_id' field.
   */
  public java.lang.CharSequence getDDateId() {
    return d_date_id;
  }

  /**
   * Sets the value of the 'd_date_id' field.
   * @param value the value to set.
   */
  public void setDDateId(java.lang.CharSequence value) {
    this.d_date_id = value;
  }

  /**
   * Gets the value of the 'd_date' field.
   */
  public java.lang.CharSequence getDDate() {
    return d_date;
  }

  /**
   * Sets the value of the 'd_date' field.
   * @param value the value to set.
   */
  public void setDDate(java.lang.CharSequence value) {
    this.d_date = value;
  }

  /**
   * Gets the value of the 'd_month_seq' field.
   */
  public java.lang.Integer getDMonthSeq() {
    return d_month_seq;
  }

  /**
   * Sets the value of the 'd_month_seq' field.
   * @param value the value to set.
   */
  public void setDMonthSeq(java.lang.Integer value) {
    this.d_month_seq = value;
  }

  /**
   * Gets the value of the 'd_week_seq' field.
   */
  public java.lang.Integer getDWeekSeq() {
    return d_week_seq;
  }

  /**
   * Sets the value of the 'd_week_seq' field.
   * @param value the value to set.
   */
  public void setDWeekSeq(java.lang.Integer value) {
    this.d_week_seq = value;
  }

  /**
   * Gets the value of the 'd_quarter_seq' field.
   */
  public java.lang.Integer getDQuarterSeq() {
    return d_quarter_seq;
  }

  /**
   * Sets the value of the 'd_quarter_seq' field.
   * @param value the value to set.
   */
  public void setDQuarterSeq(java.lang.Integer value) {
    this.d_quarter_seq = value;
  }

  /**
   * Gets the value of the 'd_year' field.
   */
  public java.lang.Integer getDYear() {
    return d_year;
  }

  /**
   * Sets the value of the 'd_year' field.
   * @param value the value to set.
   */
  public void setDYear(java.lang.Integer value) {
    this.d_year = value;
  }

  /**
   * Gets the value of the 'd_dow' field.
   */
  public java.lang.Integer getDDow() {
    return d_dow;
  }

  /**
   * Sets the value of the 'd_dow' field.
   * @param value the value to set.
   */
  public void setDDow(java.lang.Integer value) {
    this.d_dow = value;
  }

  /**
   * Gets the value of the 'd_moy' field.
   */
  public java.lang.Integer getDMoy() {
    return d_moy;
  }

  /**
   * Sets the value of the 'd_moy' field.
   * @param value the value to set.
   */
  public void setDMoy(java.lang.Integer value) {
    this.d_moy = value;
  }

  /**
   * Gets the value of the 'd_dom' field.
   */
  public java.lang.Integer getDDom() {
    return d_dom;
  }

  /**
   * Sets the value of the 'd_dom' field.
   * @param value the value to set.
   */
  public void setDDom(java.lang.Integer value) {
    this.d_dom = value;
  }

  /**
   * Gets the value of the 'd_qoy' field.
   */
  public java.lang.Integer getDQoy() {
    return d_qoy;
  }

  /**
   * Sets the value of the 'd_qoy' field.
   * @param value the value to set.
   */
  public void setDQoy(java.lang.Integer value) {
    this.d_qoy = value;
  }

  /**
   * Gets the value of the 'd_fy_year' field.
   */
  public java.lang.Integer getDFyYear() {
    return d_fy_year;
  }

  /**
   * Sets the value of the 'd_fy_year' field.
   * @param value the value to set.
   */
  public void setDFyYear(java.lang.Integer value) {
    this.d_fy_year = value;
  }

  /**
   * Gets the value of the 'd_fy_quarter_seq' field.
   */
  public java.lang.Integer getDFyQuarterSeq() {
    return d_fy_quarter_seq;
  }

  /**
   * Sets the value of the 'd_fy_quarter_seq' field.
   * @param value the value to set.
   */
  public void setDFyQuarterSeq(java.lang.Integer value) {
    this.d_fy_quarter_seq = value;
  }

  /**
   * Gets the value of the 'd_fy_week_seq' field.
   */
  public java.lang.Integer getDFyWeekSeq() {
    return d_fy_week_seq;
  }

  /**
   * Sets the value of the 'd_fy_week_seq' field.
   * @param value the value to set.
   */
  public void setDFyWeekSeq(java.lang.Integer value) {
    this.d_fy_week_seq = value;
  }

  /**
   * Gets the value of the 'd_day_name' field.
   */
  public java.lang.CharSequence getDDayName() {
    return d_day_name;
  }

  /**
   * Sets the value of the 'd_day_name' field.
   * @param value the value to set.
   */
  public void setDDayName(java.lang.CharSequence value) {
    this.d_day_name = value;
  }

  /**
   * Gets the value of the 'd_quarter_name' field.
   */
  public java.lang.CharSequence getDQuarterName() {
    return d_quarter_name;
  }

  /**
   * Sets the value of the 'd_quarter_name' field.
   * @param value the value to set.
   */
  public void setDQuarterName(java.lang.CharSequence value) {
    this.d_quarter_name = value;
  }

  /**
   * Gets the value of the 'd_holiday' field.
   */
  public java.lang.CharSequence getDHoliday() {
    return d_holiday;
  }

  /**
   * Sets the value of the 'd_holiday' field.
   * @param value the value to set.
   */
  public void setDHoliday(java.lang.CharSequence value) {
    this.d_holiday = value;
  }

  /**
   * Gets the value of the 'd_weekend' field.
   */
  public java.lang.CharSequence getDWeekend() {
    return d_weekend;
  }

  /**
   * Sets the value of the 'd_weekend' field.
   * @param value the value to set.
   */
  public void setDWeekend(java.lang.CharSequence value) {
    this.d_weekend = value;
  }

  /**
   * Gets the value of the 'd_following_holiday' field.
   */
  public java.lang.CharSequence getDFollowingHoliday() {
    return d_following_holiday;
  }

  /**
   * Sets the value of the 'd_following_holiday' field.
   * @param value the value to set.
   */
  public void setDFollowingHoliday(java.lang.CharSequence value) {
    this.d_following_holiday = value;
  }

  /**
   * Gets the value of the 'd_first_dom' field.
   */
  public java.lang.Integer getDFirstDom() {
    return d_first_dom;
  }

  /**
   * Sets the value of the 'd_first_dom' field.
   * @param value the value to set.
   */
  public void setDFirstDom(java.lang.Integer value) {
    this.d_first_dom = value;
  }

  /**
   * Gets the value of the 'd_last_dom' field.
   */
  public java.lang.Integer getDLastDom() {
    return d_last_dom;
  }

  /**
   * Sets the value of the 'd_last_dom' field.
   * @param value the value to set.
   */
  public void setDLastDom(java.lang.Integer value) {
    this.d_last_dom = value;
  }

  /**
   * Gets the value of the 'd_same_day_ly' field.
   */
  public java.lang.Integer getDSameDayLy() {
    return d_same_day_ly;
  }

  /**
   * Sets the value of the 'd_same_day_ly' field.
   * @param value the value to set.
   */
  public void setDSameDayLy(java.lang.Integer value) {
    this.d_same_day_ly = value;
  }

  /**
   * Gets the value of the 'd_same_day_lq' field.
   */
  public java.lang.Integer getDSameDayLq() {
    return d_same_day_lq;
  }

  /**
   * Sets the value of the 'd_same_day_lq' field.
   * @param value the value to set.
   */
  public void setDSameDayLq(java.lang.Integer value) {
    this.d_same_day_lq = value;
  }

  /**
   * Gets the value of the 'd_current_day' field.
   */
  public java.lang.CharSequence getDCurrentDay() {
    return d_current_day;
  }

  /**
   * Sets the value of the 'd_current_day' field.
   * @param value the value to set.
   */
  public void setDCurrentDay(java.lang.CharSequence value) {
    this.d_current_day = value;
  }

  /**
   * Gets the value of the 'd_current_week' field.
   */
  public java.lang.CharSequence getDCurrentWeek() {
    return d_current_week;
  }

  /**
   * Sets the value of the 'd_current_week' field.
   * @param value the value to set.
   */
  public void setDCurrentWeek(java.lang.CharSequence value) {
    this.d_current_week = value;
  }

  /**
   * Gets the value of the 'd_current_month' field.
   */
  public java.lang.CharSequence getDCurrentMonth() {
    return d_current_month;
  }

  /**
   * Sets the value of the 'd_current_month' field.
   * @param value the value to set.
   */
  public void setDCurrentMonth(java.lang.CharSequence value) {
    this.d_current_month = value;
  }

  /**
   * Gets the value of the 'd_current_quarter' field.
   */
  public java.lang.CharSequence getDCurrentQuarter() {
    return d_current_quarter;
  }

  /**
   * Sets the value of the 'd_current_quarter' field.
   * @param value the value to set.
   */
  public void setDCurrentQuarter(java.lang.CharSequence value) {
    this.d_current_quarter = value;
  }

  /**
   * Gets the value of the 'd_current_year' field.
   */
  public java.lang.CharSequence getDCurrentYear() {
    return d_current_year;
  }

  /**
   * Sets the value of the 'd_current_year' field.
   * @param value the value to set.
   */
  public void setDCurrentYear(java.lang.CharSequence value) {
    this.d_current_year = value;
  }

  /** Creates a new Date_Dim RecordBuilder */
  public static bigframe.avro.Date_Dim.Builder newBuilder() {
    return new bigframe.avro.Date_Dim.Builder();
  }
  
  /** Creates a new Date_Dim RecordBuilder by copying an existing Builder */
  public static bigframe.avro.Date_Dim.Builder newBuilder(bigframe.avro.Date_Dim.Builder other) {
    return new bigframe.avro.Date_Dim.Builder(other);
  }
  
  /** Creates a new Date_Dim RecordBuilder by copying an existing Date_Dim instance */
  public static bigframe.avro.Date_Dim.Builder newBuilder(bigframe.avro.Date_Dim other) {
    return new bigframe.avro.Date_Dim.Builder(other);
  }
  
  /**
   * RecordBuilder for Date_Dim instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Date_Dim>
    implements org.apache.avro.data.RecordBuilder<Date_Dim> {

    private int d_date_sk;
    private java.lang.CharSequence d_date_id;
    private java.lang.CharSequence d_date;
    private int d_month_seq;
    private int d_week_seq;
    private int d_quarter_seq;
    private int d_year;
    private int d_dow;
    private int d_moy;
    private int d_dom;
    private int d_qoy;
    private int d_fy_year;
    private int d_fy_quarter_seq;
    private int d_fy_week_seq;
    private java.lang.CharSequence d_day_name;
    private java.lang.CharSequence d_quarter_name;
    private java.lang.CharSequence d_holiday;
    private java.lang.CharSequence d_weekend;
    private java.lang.CharSequence d_following_holiday;
    private int d_first_dom;
    private int d_last_dom;
    private int d_same_day_ly;
    private int d_same_day_lq;
    private java.lang.CharSequence d_current_day;
    private java.lang.CharSequence d_current_week;
    private java.lang.CharSequence d_current_month;
    private java.lang.CharSequence d_current_quarter;
    private java.lang.CharSequence d_current_year;

    /** Creates a new Builder */
    private Builder() {
      super(bigframe.avro.Date_Dim.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(bigframe.avro.Date_Dim.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Date_Dim instance */
    private Builder(bigframe.avro.Date_Dim other) {
            super(bigframe.avro.Date_Dim.SCHEMA$);
      if (isValidValue(fields()[0], other.d_date_sk)) {
        this.d_date_sk = data().deepCopy(fields()[0].schema(), other.d_date_sk);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.d_date_id)) {
        this.d_date_id = data().deepCopy(fields()[1].schema(), other.d_date_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.d_date)) {
        this.d_date = data().deepCopy(fields()[2].schema(), other.d_date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.d_month_seq)) {
        this.d_month_seq = data().deepCopy(fields()[3].schema(), other.d_month_seq);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.d_week_seq)) {
        this.d_week_seq = data().deepCopy(fields()[4].schema(), other.d_week_seq);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.d_quarter_seq)) {
        this.d_quarter_seq = data().deepCopy(fields()[5].schema(), other.d_quarter_seq);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.d_year)) {
        this.d_year = data().deepCopy(fields()[6].schema(), other.d_year);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.d_dow)) {
        this.d_dow = data().deepCopy(fields()[7].schema(), other.d_dow);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.d_moy)) {
        this.d_moy = data().deepCopy(fields()[8].schema(), other.d_moy);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.d_dom)) {
        this.d_dom = data().deepCopy(fields()[9].schema(), other.d_dom);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.d_qoy)) {
        this.d_qoy = data().deepCopy(fields()[10].schema(), other.d_qoy);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.d_fy_year)) {
        this.d_fy_year = data().deepCopy(fields()[11].schema(), other.d_fy_year);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.d_fy_quarter_seq)) {
        this.d_fy_quarter_seq = data().deepCopy(fields()[12].schema(), other.d_fy_quarter_seq);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.d_fy_week_seq)) {
        this.d_fy_week_seq = data().deepCopy(fields()[13].schema(), other.d_fy_week_seq);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.d_day_name)) {
        this.d_day_name = data().deepCopy(fields()[14].schema(), other.d_day_name);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.d_quarter_name)) {
        this.d_quarter_name = data().deepCopy(fields()[15].schema(), other.d_quarter_name);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.d_holiday)) {
        this.d_holiday = data().deepCopy(fields()[16].schema(), other.d_holiday);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.d_weekend)) {
        this.d_weekend = data().deepCopy(fields()[17].schema(), other.d_weekend);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.d_following_holiday)) {
        this.d_following_holiday = data().deepCopy(fields()[18].schema(), other.d_following_holiday);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.d_first_dom)) {
        this.d_first_dom = data().deepCopy(fields()[19].schema(), other.d_first_dom);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.d_last_dom)) {
        this.d_last_dom = data().deepCopy(fields()[20].schema(), other.d_last_dom);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.d_same_day_ly)) {
        this.d_same_day_ly = data().deepCopy(fields()[21].schema(), other.d_same_day_ly);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.d_same_day_lq)) {
        this.d_same_day_lq = data().deepCopy(fields()[22].schema(), other.d_same_day_lq);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.d_current_day)) {
        this.d_current_day = data().deepCopy(fields()[23].schema(), other.d_current_day);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.d_current_week)) {
        this.d_current_week = data().deepCopy(fields()[24].schema(), other.d_current_week);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.d_current_month)) {
        this.d_current_month = data().deepCopy(fields()[25].schema(), other.d_current_month);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.d_current_quarter)) {
        this.d_current_quarter = data().deepCopy(fields()[26].schema(), other.d_current_quarter);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.d_current_year)) {
        this.d_current_year = data().deepCopy(fields()[27].schema(), other.d_current_year);
        fieldSetFlags()[27] = true;
      }
    }

    /** Gets the value of the 'd_date_sk' field */
    public java.lang.Integer getDDateSk() {
      return d_date_sk;
    }
    
    /** Sets the value of the 'd_date_sk' field */
    public bigframe.avro.Date_Dim.Builder setDDateSk(int value) {
      validate(fields()[0], value);
      this.d_date_sk = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'd_date_sk' field has been set */
    public boolean hasDDateSk() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'd_date_sk' field */
    public bigframe.avro.Date_Dim.Builder clearDDateSk() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'd_date_id' field */
    public java.lang.CharSequence getDDateId() {
      return d_date_id;
    }
    
    /** Sets the value of the 'd_date_id' field */
    public bigframe.avro.Date_Dim.Builder setDDateId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.d_date_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'd_date_id' field has been set */
    public boolean hasDDateId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'd_date_id' field */
    public bigframe.avro.Date_Dim.Builder clearDDateId() {
      d_date_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'd_date' field */
    public java.lang.CharSequence getDDate() {
      return d_date;
    }
    
    /** Sets the value of the 'd_date' field */
    public bigframe.avro.Date_Dim.Builder setDDate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.d_date = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'd_date' field has been set */
    public boolean hasDDate() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'd_date' field */
    public bigframe.avro.Date_Dim.Builder clearDDate() {
      d_date = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'd_month_seq' field */
    public java.lang.Integer getDMonthSeq() {
      return d_month_seq;
    }
    
    /** Sets the value of the 'd_month_seq' field */
    public bigframe.avro.Date_Dim.Builder setDMonthSeq(int value) {
      validate(fields()[3], value);
      this.d_month_seq = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'd_month_seq' field has been set */
    public boolean hasDMonthSeq() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'd_month_seq' field */
    public bigframe.avro.Date_Dim.Builder clearDMonthSeq() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'd_week_seq' field */
    public java.lang.Integer getDWeekSeq() {
      return d_week_seq;
    }
    
    /** Sets the value of the 'd_week_seq' field */
    public bigframe.avro.Date_Dim.Builder setDWeekSeq(int value) {
      validate(fields()[4], value);
      this.d_week_seq = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'd_week_seq' field has been set */
    public boolean hasDWeekSeq() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'd_week_seq' field */
    public bigframe.avro.Date_Dim.Builder clearDWeekSeq() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'd_quarter_seq' field */
    public java.lang.Integer getDQuarterSeq() {
      return d_quarter_seq;
    }
    
    /** Sets the value of the 'd_quarter_seq' field */
    public bigframe.avro.Date_Dim.Builder setDQuarterSeq(int value) {
      validate(fields()[5], value);
      this.d_quarter_seq = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'd_quarter_seq' field has been set */
    public boolean hasDQuarterSeq() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'd_quarter_seq' field */
    public bigframe.avro.Date_Dim.Builder clearDQuarterSeq() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'd_year' field */
    public java.lang.Integer getDYear() {
      return d_year;
    }
    
    /** Sets the value of the 'd_year' field */
    public bigframe.avro.Date_Dim.Builder setDYear(int value) {
      validate(fields()[6], value);
      this.d_year = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'd_year' field has been set */
    public boolean hasDYear() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'd_year' field */
    public bigframe.avro.Date_Dim.Builder clearDYear() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'd_dow' field */
    public java.lang.Integer getDDow() {
      return d_dow;
    }
    
    /** Sets the value of the 'd_dow' field */
    public bigframe.avro.Date_Dim.Builder setDDow(int value) {
      validate(fields()[7], value);
      this.d_dow = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'd_dow' field has been set */
    public boolean hasDDow() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'd_dow' field */
    public bigframe.avro.Date_Dim.Builder clearDDow() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'd_moy' field */
    public java.lang.Integer getDMoy() {
      return d_moy;
    }
    
    /** Sets the value of the 'd_moy' field */
    public bigframe.avro.Date_Dim.Builder setDMoy(int value) {
      validate(fields()[8], value);
      this.d_moy = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'd_moy' field has been set */
    public boolean hasDMoy() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'd_moy' field */
    public bigframe.avro.Date_Dim.Builder clearDMoy() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'd_dom' field */
    public java.lang.Integer getDDom() {
      return d_dom;
    }
    
    /** Sets the value of the 'd_dom' field */
    public bigframe.avro.Date_Dim.Builder setDDom(int value) {
      validate(fields()[9], value);
      this.d_dom = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'd_dom' field has been set */
    public boolean hasDDom() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'd_dom' field */
    public bigframe.avro.Date_Dim.Builder clearDDom() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'd_qoy' field */
    public java.lang.Integer getDQoy() {
      return d_qoy;
    }
    
    /** Sets the value of the 'd_qoy' field */
    public bigframe.avro.Date_Dim.Builder setDQoy(int value) {
      validate(fields()[10], value);
      this.d_qoy = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'd_qoy' field has been set */
    public boolean hasDQoy() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'd_qoy' field */
    public bigframe.avro.Date_Dim.Builder clearDQoy() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'd_fy_year' field */
    public java.lang.Integer getDFyYear() {
      return d_fy_year;
    }
    
    /** Sets the value of the 'd_fy_year' field */
    public bigframe.avro.Date_Dim.Builder setDFyYear(int value) {
      validate(fields()[11], value);
      this.d_fy_year = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'd_fy_year' field has been set */
    public boolean hasDFyYear() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'd_fy_year' field */
    public bigframe.avro.Date_Dim.Builder clearDFyYear() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'd_fy_quarter_seq' field */
    public java.lang.Integer getDFyQuarterSeq() {
      return d_fy_quarter_seq;
    }
    
    /** Sets the value of the 'd_fy_quarter_seq' field */
    public bigframe.avro.Date_Dim.Builder setDFyQuarterSeq(int value) {
      validate(fields()[12], value);
      this.d_fy_quarter_seq = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'd_fy_quarter_seq' field has been set */
    public boolean hasDFyQuarterSeq() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'd_fy_quarter_seq' field */
    public bigframe.avro.Date_Dim.Builder clearDFyQuarterSeq() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'd_fy_week_seq' field */
    public java.lang.Integer getDFyWeekSeq() {
      return d_fy_week_seq;
    }
    
    /** Sets the value of the 'd_fy_week_seq' field */
    public bigframe.avro.Date_Dim.Builder setDFyWeekSeq(int value) {
      validate(fields()[13], value);
      this.d_fy_week_seq = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'd_fy_week_seq' field has been set */
    public boolean hasDFyWeekSeq() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'd_fy_week_seq' field */
    public bigframe.avro.Date_Dim.Builder clearDFyWeekSeq() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'd_day_name' field */
    public java.lang.CharSequence getDDayName() {
      return d_day_name;
    }
    
    /** Sets the value of the 'd_day_name' field */
    public bigframe.avro.Date_Dim.Builder setDDayName(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.d_day_name = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'd_day_name' field has been set */
    public boolean hasDDayName() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'd_day_name' field */
    public bigframe.avro.Date_Dim.Builder clearDDayName() {
      d_day_name = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'd_quarter_name' field */
    public java.lang.CharSequence getDQuarterName() {
      return d_quarter_name;
    }
    
    /** Sets the value of the 'd_quarter_name' field */
    public bigframe.avro.Date_Dim.Builder setDQuarterName(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.d_quarter_name = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'd_quarter_name' field has been set */
    public boolean hasDQuarterName() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'd_quarter_name' field */
    public bigframe.avro.Date_Dim.Builder clearDQuarterName() {
      d_quarter_name = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'd_holiday' field */
    public java.lang.CharSequence getDHoliday() {
      return d_holiday;
    }
    
    /** Sets the value of the 'd_holiday' field */
    public bigframe.avro.Date_Dim.Builder setDHoliday(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.d_holiday = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'd_holiday' field has been set */
    public boolean hasDHoliday() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'd_holiday' field */
    public bigframe.avro.Date_Dim.Builder clearDHoliday() {
      d_holiday = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'd_weekend' field */
    public java.lang.CharSequence getDWeekend() {
      return d_weekend;
    }
    
    /** Sets the value of the 'd_weekend' field */
    public bigframe.avro.Date_Dim.Builder setDWeekend(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.d_weekend = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'd_weekend' field has been set */
    public boolean hasDWeekend() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'd_weekend' field */
    public bigframe.avro.Date_Dim.Builder clearDWeekend() {
      d_weekend = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'd_following_holiday' field */
    public java.lang.CharSequence getDFollowingHoliday() {
      return d_following_holiday;
    }
    
    /** Sets the value of the 'd_following_holiday' field */
    public bigframe.avro.Date_Dim.Builder setDFollowingHoliday(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.d_following_holiday = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'd_following_holiday' field has been set */
    public boolean hasDFollowingHoliday() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'd_following_holiday' field */
    public bigframe.avro.Date_Dim.Builder clearDFollowingHoliday() {
      d_following_holiday = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'd_first_dom' field */
    public java.lang.Integer getDFirstDom() {
      return d_first_dom;
    }
    
    /** Sets the value of the 'd_first_dom' field */
    public bigframe.avro.Date_Dim.Builder setDFirstDom(int value) {
      validate(fields()[19], value);
      this.d_first_dom = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'd_first_dom' field has been set */
    public boolean hasDFirstDom() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'd_first_dom' field */
    public bigframe.avro.Date_Dim.Builder clearDFirstDom() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'd_last_dom' field */
    public java.lang.Integer getDLastDom() {
      return d_last_dom;
    }
    
    /** Sets the value of the 'd_last_dom' field */
    public bigframe.avro.Date_Dim.Builder setDLastDom(int value) {
      validate(fields()[20], value);
      this.d_last_dom = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'd_last_dom' field has been set */
    public boolean hasDLastDom() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'd_last_dom' field */
    public bigframe.avro.Date_Dim.Builder clearDLastDom() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'd_same_day_ly' field */
    public java.lang.Integer getDSameDayLy() {
      return d_same_day_ly;
    }
    
    /** Sets the value of the 'd_same_day_ly' field */
    public bigframe.avro.Date_Dim.Builder setDSameDayLy(int value) {
      validate(fields()[21], value);
      this.d_same_day_ly = value;
      fieldSetFlags()[21] = true;
      return this; 
    }
    
    /** Checks whether the 'd_same_day_ly' field has been set */
    public boolean hasDSameDayLy() {
      return fieldSetFlags()[21];
    }
    
    /** Clears the value of the 'd_same_day_ly' field */
    public bigframe.avro.Date_Dim.Builder clearDSameDayLy() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /** Gets the value of the 'd_same_day_lq' field */
    public java.lang.Integer getDSameDayLq() {
      return d_same_day_lq;
    }
    
    /** Sets the value of the 'd_same_day_lq' field */
    public bigframe.avro.Date_Dim.Builder setDSameDayLq(int value) {
      validate(fields()[22], value);
      this.d_same_day_lq = value;
      fieldSetFlags()[22] = true;
      return this; 
    }
    
    /** Checks whether the 'd_same_day_lq' field has been set */
    public boolean hasDSameDayLq() {
      return fieldSetFlags()[22];
    }
    
    /** Clears the value of the 'd_same_day_lq' field */
    public bigframe.avro.Date_Dim.Builder clearDSameDayLq() {
      fieldSetFlags()[22] = false;
      return this;
    }

    /** Gets the value of the 'd_current_day' field */
    public java.lang.CharSequence getDCurrentDay() {
      return d_current_day;
    }
    
    /** Sets the value of the 'd_current_day' field */
    public bigframe.avro.Date_Dim.Builder setDCurrentDay(java.lang.CharSequence value) {
      validate(fields()[23], value);
      this.d_current_day = value;
      fieldSetFlags()[23] = true;
      return this; 
    }
    
    /** Checks whether the 'd_current_day' field has been set */
    public boolean hasDCurrentDay() {
      return fieldSetFlags()[23];
    }
    
    /** Clears the value of the 'd_current_day' field */
    public bigframe.avro.Date_Dim.Builder clearDCurrentDay() {
      d_current_day = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /** Gets the value of the 'd_current_week' field */
    public java.lang.CharSequence getDCurrentWeek() {
      return d_current_week;
    }
    
    /** Sets the value of the 'd_current_week' field */
    public bigframe.avro.Date_Dim.Builder setDCurrentWeek(java.lang.CharSequence value) {
      validate(fields()[24], value);
      this.d_current_week = value;
      fieldSetFlags()[24] = true;
      return this; 
    }
    
    /** Checks whether the 'd_current_week' field has been set */
    public boolean hasDCurrentWeek() {
      return fieldSetFlags()[24];
    }
    
    /** Clears the value of the 'd_current_week' field */
    public bigframe.avro.Date_Dim.Builder clearDCurrentWeek() {
      d_current_week = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /** Gets the value of the 'd_current_month' field */
    public java.lang.CharSequence getDCurrentMonth() {
      return d_current_month;
    }
    
    /** Sets the value of the 'd_current_month' field */
    public bigframe.avro.Date_Dim.Builder setDCurrentMonth(java.lang.CharSequence value) {
      validate(fields()[25], value);
      this.d_current_month = value;
      fieldSetFlags()[25] = true;
      return this; 
    }
    
    /** Checks whether the 'd_current_month' field has been set */
    public boolean hasDCurrentMonth() {
      return fieldSetFlags()[25];
    }
    
    /** Clears the value of the 'd_current_month' field */
    public bigframe.avro.Date_Dim.Builder clearDCurrentMonth() {
      d_current_month = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /** Gets the value of the 'd_current_quarter' field */
    public java.lang.CharSequence getDCurrentQuarter() {
      return d_current_quarter;
    }
    
    /** Sets the value of the 'd_current_quarter' field */
    public bigframe.avro.Date_Dim.Builder setDCurrentQuarter(java.lang.CharSequence value) {
      validate(fields()[26], value);
      this.d_current_quarter = value;
      fieldSetFlags()[26] = true;
      return this; 
    }
    
    /** Checks whether the 'd_current_quarter' field has been set */
    public boolean hasDCurrentQuarter() {
      return fieldSetFlags()[26];
    }
    
    /** Clears the value of the 'd_current_quarter' field */
    public bigframe.avro.Date_Dim.Builder clearDCurrentQuarter() {
      d_current_quarter = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /** Gets the value of the 'd_current_year' field */
    public java.lang.CharSequence getDCurrentYear() {
      return d_current_year;
    }
    
    /** Sets the value of the 'd_current_year' field */
    public bigframe.avro.Date_Dim.Builder setDCurrentYear(java.lang.CharSequence value) {
      validate(fields()[27], value);
      this.d_current_year = value;
      fieldSetFlags()[27] = true;
      return this; 
    }
    
    /** Checks whether the 'd_current_year' field has been set */
    public boolean hasDCurrentYear() {
      return fieldSetFlags()[27];
    }
    
    /** Clears the value of the 'd_current_year' field */
    public bigframe.avro.Date_Dim.Builder clearDCurrentYear() {
      d_current_year = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    @Override
    public Date_Dim build() {
      try {
        Date_Dim record = new Date_Dim();
        record.d_date_sk = fieldSetFlags()[0] ? this.d_date_sk : (java.lang.Integer) defaultValue(fields()[0]);
        record.d_date_id = fieldSetFlags()[1] ? this.d_date_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.d_date = fieldSetFlags()[2] ? this.d_date : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.d_month_seq = fieldSetFlags()[3] ? this.d_month_seq : (java.lang.Integer) defaultValue(fields()[3]);
        record.d_week_seq = fieldSetFlags()[4] ? this.d_week_seq : (java.lang.Integer) defaultValue(fields()[4]);
        record.d_quarter_seq = fieldSetFlags()[5] ? this.d_quarter_seq : (java.lang.Integer) defaultValue(fields()[5]);
        record.d_year = fieldSetFlags()[6] ? this.d_year : (java.lang.Integer) defaultValue(fields()[6]);
        record.d_dow = fieldSetFlags()[7] ? this.d_dow : (java.lang.Integer) defaultValue(fields()[7]);
        record.d_moy = fieldSetFlags()[8] ? this.d_moy : (java.lang.Integer) defaultValue(fields()[8]);
        record.d_dom = fieldSetFlags()[9] ? this.d_dom : (java.lang.Integer) defaultValue(fields()[9]);
        record.d_qoy = fieldSetFlags()[10] ? this.d_qoy : (java.lang.Integer) defaultValue(fields()[10]);
        record.d_fy_year = fieldSetFlags()[11] ? this.d_fy_year : (java.lang.Integer) defaultValue(fields()[11]);
        record.d_fy_quarter_seq = fieldSetFlags()[12] ? this.d_fy_quarter_seq : (java.lang.Integer) defaultValue(fields()[12]);
        record.d_fy_week_seq = fieldSetFlags()[13] ? this.d_fy_week_seq : (java.lang.Integer) defaultValue(fields()[13]);
        record.d_day_name = fieldSetFlags()[14] ? this.d_day_name : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.d_quarter_name = fieldSetFlags()[15] ? this.d_quarter_name : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.d_holiday = fieldSetFlags()[16] ? this.d_holiday : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.d_weekend = fieldSetFlags()[17] ? this.d_weekend : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.d_following_holiday = fieldSetFlags()[18] ? this.d_following_holiday : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.d_first_dom = fieldSetFlags()[19] ? this.d_first_dom : (java.lang.Integer) defaultValue(fields()[19]);
        record.d_last_dom = fieldSetFlags()[20] ? this.d_last_dom : (java.lang.Integer) defaultValue(fields()[20]);
        record.d_same_day_ly = fieldSetFlags()[21] ? this.d_same_day_ly : (java.lang.Integer) defaultValue(fields()[21]);
        record.d_same_day_lq = fieldSetFlags()[22] ? this.d_same_day_lq : (java.lang.Integer) defaultValue(fields()[22]);
        record.d_current_day = fieldSetFlags()[23] ? this.d_current_day : (java.lang.CharSequence) defaultValue(fields()[23]);
        record.d_current_week = fieldSetFlags()[24] ? this.d_current_week : (java.lang.CharSequence) defaultValue(fields()[24]);
        record.d_current_month = fieldSetFlags()[25] ? this.d_current_month : (java.lang.CharSequence) defaultValue(fields()[25]);
        record.d_current_quarter = fieldSetFlags()[26] ? this.d_current_quarter : (java.lang.CharSequence) defaultValue(fields()[26]);
        record.d_current_year = fieldSetFlags()[27] ? this.d_current_year : (java.lang.CharSequence) defaultValue(fields()[27]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
