/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Item extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Item\",\"namespace\":\"bigframe.avro\",\"fields\":[{\"name\":\"i_item_sk\",\"type\":\"int\"},{\"name\":\"i_item_id\",\"type\":\"string\"},{\"name\":\"i_rec_start_date\",\"type\":\"string\"},{\"name\":\"i_rec_end_date\",\"type\":\"string\"},{\"name\":\"i_item_desc\",\"type\":\"string\"},{\"name\":\"i_current_price\",\"type\":\"float\"},{\"name\":\"i_wholesale_cost\",\"type\":\"float\"},{\"name\":\"i_brand_id\",\"type\":\"int\"},{\"name\":\"i_brand\",\"type\":\"string\"},{\"name\":\"i_claws_id\",\"type\":\"int\"},{\"name\":\"i_class\",\"type\":\"string\"},{\"name\":\"i_category_id\",\"type\":\"int\"},{\"name\":\"i_category\",\"type\":\"string\"},{\"name\":\"i_manufact_id\",\"type\":\"int\"},{\"name\":\"i_manufact\",\"type\":\"string\"},{\"name\":\"i_size\",\"type\":\"string\"},{\"name\":\"i_formulation\",\"type\":\"string\"},{\"name\":\"i_color\",\"type\":\"string\"},{\"name\":\"i_units\",\"type\":\"string\"},{\"name\":\"i_container\",\"type\":\"string\"},{\"name\":\"i_manager_id\",\"type\":\"int\"},{\"name\":\"i_product_name\",\"type\":\"string\"}]}");
  @Deprecated public int i_item_sk;
  @Deprecated public java.lang.CharSequence i_item_id;
  @Deprecated public java.lang.CharSequence i_rec_start_date;
  @Deprecated public java.lang.CharSequence i_rec_end_date;
  @Deprecated public java.lang.CharSequence i_item_desc;
  @Deprecated public float i_current_price;
  @Deprecated public float i_wholesale_cost;
  @Deprecated public int i_brand_id;
  @Deprecated public java.lang.CharSequence i_brand;
  @Deprecated public int i_claws_id;
  @Deprecated public java.lang.CharSequence i_class;
  @Deprecated public int i_category_id;
  @Deprecated public java.lang.CharSequence i_category;
  @Deprecated public int i_manufact_id;
  @Deprecated public java.lang.CharSequence i_manufact;
  @Deprecated public java.lang.CharSequence i_size;
  @Deprecated public java.lang.CharSequence i_formulation;
  @Deprecated public java.lang.CharSequence i_color;
  @Deprecated public java.lang.CharSequence i_units;
  @Deprecated public java.lang.CharSequence i_container;
  @Deprecated public int i_manager_id;
  @Deprecated public java.lang.CharSequence i_product_name;

  /**
   * Default constructor.
   */
  public Item() {}

  /**
   * All-args constructor.
   */
  public Item(java.lang.Integer i_item_sk, java.lang.CharSequence i_item_id, java.lang.CharSequence i_rec_start_date, java.lang.CharSequence i_rec_end_date, java.lang.CharSequence i_item_desc, java.lang.Float i_current_price, java.lang.Float i_wholesale_cost, java.lang.Integer i_brand_id, java.lang.CharSequence i_brand, java.lang.Integer i_claws_id, java.lang.CharSequence i_class, java.lang.Integer i_category_id, java.lang.CharSequence i_category, java.lang.Integer i_manufact_id, java.lang.CharSequence i_manufact, java.lang.CharSequence i_size, java.lang.CharSequence i_formulation, java.lang.CharSequence i_color, java.lang.CharSequence i_units, java.lang.CharSequence i_container, java.lang.Integer i_manager_id, java.lang.CharSequence i_product_name) {
    this.i_item_sk = i_item_sk;
    this.i_item_id = i_item_id;
    this.i_rec_start_date = i_rec_start_date;
    this.i_rec_end_date = i_rec_end_date;
    this.i_item_desc = i_item_desc;
    this.i_current_price = i_current_price;
    this.i_wholesale_cost = i_wholesale_cost;
    this.i_brand_id = i_brand_id;
    this.i_brand = i_brand;
    this.i_claws_id = i_claws_id;
    this.i_class = i_class;
    this.i_category_id = i_category_id;
    this.i_category = i_category;
    this.i_manufact_id = i_manufact_id;
    this.i_manufact = i_manufact;
    this.i_size = i_size;
    this.i_formulation = i_formulation;
    this.i_color = i_color;
    this.i_units = i_units;
    this.i_container = i_container;
    this.i_manager_id = i_manager_id;
    this.i_product_name = i_product_name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return i_item_sk;
    case 1: return i_item_id;
    case 2: return i_rec_start_date;
    case 3: return i_rec_end_date;
    case 4: return i_item_desc;
    case 5: return i_current_price;
    case 6: return i_wholesale_cost;
    case 7: return i_brand_id;
    case 8: return i_brand;
    case 9: return i_claws_id;
    case 10: return i_class;
    case 11: return i_category_id;
    case 12: return i_category;
    case 13: return i_manufact_id;
    case 14: return i_manufact;
    case 15: return i_size;
    case 16: return i_formulation;
    case 17: return i_color;
    case 18: return i_units;
    case 19: return i_container;
    case 20: return i_manager_id;
    case 21: return i_product_name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: i_item_sk = (java.lang.Integer)value$; break;
    case 1: i_item_id = (java.lang.CharSequence)value$; break;
    case 2: i_rec_start_date = (java.lang.CharSequence)value$; break;
    case 3: i_rec_end_date = (java.lang.CharSequence)value$; break;
    case 4: i_item_desc = (java.lang.CharSequence)value$; break;
    case 5: i_current_price = (java.lang.Float)value$; break;
    case 6: i_wholesale_cost = (java.lang.Float)value$; break;
    case 7: i_brand_id = (java.lang.Integer)value$; break;
    case 8: i_brand = (java.lang.CharSequence)value$; break;
    case 9: i_claws_id = (java.lang.Integer)value$; break;
    case 10: i_class = (java.lang.CharSequence)value$; break;
    case 11: i_category_id = (java.lang.Integer)value$; break;
    case 12: i_category = (java.lang.CharSequence)value$; break;
    case 13: i_manufact_id = (java.lang.Integer)value$; break;
    case 14: i_manufact = (java.lang.CharSequence)value$; break;
    case 15: i_size = (java.lang.CharSequence)value$; break;
    case 16: i_formulation = (java.lang.CharSequence)value$; break;
    case 17: i_color = (java.lang.CharSequence)value$; break;
    case 18: i_units = (java.lang.CharSequence)value$; break;
    case 19: i_container = (java.lang.CharSequence)value$; break;
    case 20: i_manager_id = (java.lang.Integer)value$; break;
    case 21: i_product_name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'i_item_sk' field.
   */
  public java.lang.Integer getIItemSk() {
    return i_item_sk;
  }

  /**
   * Sets the value of the 'i_item_sk' field.
   * @param value the value to set.
   */
  public void setIItemSk(java.lang.Integer value) {
    this.i_item_sk = value;
  }

  /**
   * Gets the value of the 'i_item_id' field.
   */
  public java.lang.CharSequence getIItemId() {
    return i_item_id;
  }

  /**
   * Sets the value of the 'i_item_id' field.
   * @param value the value to set.
   */
  public void setIItemId(java.lang.CharSequence value) {
    this.i_item_id = value;
  }

  /**
   * Gets the value of the 'i_rec_start_date' field.
   */
  public java.lang.CharSequence getIRecStartDate() {
    return i_rec_start_date;
  }

  /**
   * Sets the value of the 'i_rec_start_date' field.
   * @param value the value to set.
   */
  public void setIRecStartDate(java.lang.CharSequence value) {
    this.i_rec_start_date = value;
  }

  /**
   * Gets the value of the 'i_rec_end_date' field.
   */
  public java.lang.CharSequence getIRecEndDate() {
    return i_rec_end_date;
  }

  /**
   * Sets the value of the 'i_rec_end_date' field.
   * @param value the value to set.
   */
  public void setIRecEndDate(java.lang.CharSequence value) {
    this.i_rec_end_date = value;
  }

  /**
   * Gets the value of the 'i_item_desc' field.
   */
  public java.lang.CharSequence getIItemDesc() {
    return i_item_desc;
  }

  /**
   * Sets the value of the 'i_item_desc' field.
   * @param value the value to set.
   */
  public void setIItemDesc(java.lang.CharSequence value) {
    this.i_item_desc = value;
  }

  /**
   * Gets the value of the 'i_current_price' field.
   */
  public java.lang.Float getICurrentPrice() {
    return i_current_price;
  }

  /**
   * Sets the value of the 'i_current_price' field.
   * @param value the value to set.
   */
  public void setICurrentPrice(java.lang.Float value) {
    this.i_current_price = value;
  }

  /**
   * Gets the value of the 'i_wholesale_cost' field.
   */
  public java.lang.Float getIWholesaleCost() {
    return i_wholesale_cost;
  }

  /**
   * Sets the value of the 'i_wholesale_cost' field.
   * @param value the value to set.
   */
  public void setIWholesaleCost(java.lang.Float value) {
    this.i_wholesale_cost = value;
  }

  /**
   * Gets the value of the 'i_brand_id' field.
   */
  public java.lang.Integer getIBrandId() {
    return i_brand_id;
  }

  /**
   * Sets the value of the 'i_brand_id' field.
   * @param value the value to set.
   */
  public void setIBrandId(java.lang.Integer value) {
    this.i_brand_id = value;
  }

  /**
   * Gets the value of the 'i_brand' field.
   */
  public java.lang.CharSequence getIBrand() {
    return i_brand;
  }

  /**
   * Sets the value of the 'i_brand' field.
   * @param value the value to set.
   */
  public void setIBrand(java.lang.CharSequence value) {
    this.i_brand = value;
  }

  /**
   * Gets the value of the 'i_claws_id' field.
   */
  public java.lang.Integer getIClawsId() {
    return i_claws_id;
  }

  /**
   * Sets the value of the 'i_claws_id' field.
   * @param value the value to set.
   */
  public void setIClawsId(java.lang.Integer value) {
    this.i_claws_id = value;
  }

  /**
   * Gets the value of the 'i_class' field.
   */
  public java.lang.CharSequence getIClass() {
    return i_class;
  }

  /**
   * Sets the value of the 'i_class' field.
   * @param value the value to set.
   */
  public void setIClass(java.lang.CharSequence value) {
    this.i_class = value;
  }

  /**
   * Gets the value of the 'i_category_id' field.
   */
  public java.lang.Integer getICategoryId() {
    return i_category_id;
  }

  /**
   * Sets the value of the 'i_category_id' field.
   * @param value the value to set.
   */
  public void setICategoryId(java.lang.Integer value) {
    this.i_category_id = value;
  }

  /**
   * Gets the value of the 'i_category' field.
   */
  public java.lang.CharSequence getICategory() {
    return i_category;
  }

  /**
   * Sets the value of the 'i_category' field.
   * @param value the value to set.
   */
  public void setICategory(java.lang.CharSequence value) {
    this.i_category = value;
  }

  /**
   * Gets the value of the 'i_manufact_id' field.
   */
  public java.lang.Integer getIManufactId() {
    return i_manufact_id;
  }

  /**
   * Sets the value of the 'i_manufact_id' field.
   * @param value the value to set.
   */
  public void setIManufactId(java.lang.Integer value) {
    this.i_manufact_id = value;
  }

  /**
   * Gets the value of the 'i_manufact' field.
   */
  public java.lang.CharSequence getIManufact() {
    return i_manufact;
  }

  /**
   * Sets the value of the 'i_manufact' field.
   * @param value the value to set.
   */
  public void setIManufact(java.lang.CharSequence value) {
    this.i_manufact = value;
  }

  /**
   * Gets the value of the 'i_size' field.
   */
  public java.lang.CharSequence getISize() {
    return i_size;
  }

  /**
   * Sets the value of the 'i_size' field.
   * @param value the value to set.
   */
  public void setISize(java.lang.CharSequence value) {
    this.i_size = value;
  }

  /**
   * Gets the value of the 'i_formulation' field.
   */
  public java.lang.CharSequence getIFormulation() {
    return i_formulation;
  }

  /**
   * Sets the value of the 'i_formulation' field.
   * @param value the value to set.
   */
  public void setIFormulation(java.lang.CharSequence value) {
    this.i_formulation = value;
  }

  /**
   * Gets the value of the 'i_color' field.
   */
  public java.lang.CharSequence getIColor() {
    return i_color;
  }

  /**
   * Sets the value of the 'i_color' field.
   * @param value the value to set.
   */
  public void setIColor(java.lang.CharSequence value) {
    this.i_color = value;
  }

  /**
   * Gets the value of the 'i_units' field.
   */
  public java.lang.CharSequence getIUnits() {
    return i_units;
  }

  /**
   * Sets the value of the 'i_units' field.
   * @param value the value to set.
   */
  public void setIUnits(java.lang.CharSequence value) {
    this.i_units = value;
  }

  /**
   * Gets the value of the 'i_container' field.
   */
  public java.lang.CharSequence getIContainer() {
    return i_container;
  }

  /**
   * Sets the value of the 'i_container' field.
   * @param value the value to set.
   */
  public void setIContainer(java.lang.CharSequence value) {
    this.i_container = value;
  }

  /**
   * Gets the value of the 'i_manager_id' field.
   */
  public java.lang.Integer getIManagerId() {
    return i_manager_id;
  }

  /**
   * Sets the value of the 'i_manager_id' field.
   * @param value the value to set.
   */
  public void setIManagerId(java.lang.Integer value) {
    this.i_manager_id = value;
  }

  /**
   * Gets the value of the 'i_product_name' field.
   */
  public java.lang.CharSequence getIProductName() {
    return i_product_name;
  }

  /**
   * Sets the value of the 'i_product_name' field.
   * @param value the value to set.
   */
  public void setIProductName(java.lang.CharSequence value) {
    this.i_product_name = value;
  }

  /** Creates a new Item RecordBuilder */
  public static bigframe.avro.Item.Builder newBuilder() {
    return new bigframe.avro.Item.Builder();
  }
  
  /** Creates a new Item RecordBuilder by copying an existing Builder */
  public static bigframe.avro.Item.Builder newBuilder(bigframe.avro.Item.Builder other) {
    return new bigframe.avro.Item.Builder(other);
  }
  
  /** Creates a new Item RecordBuilder by copying an existing Item instance */
  public static bigframe.avro.Item.Builder newBuilder(bigframe.avro.Item other) {
    return new bigframe.avro.Item.Builder(other);
  }
  
  /**
   * RecordBuilder for Item instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Item>
    implements org.apache.avro.data.RecordBuilder<Item> {

    private int i_item_sk;
    private java.lang.CharSequence i_item_id;
    private java.lang.CharSequence i_rec_start_date;
    private java.lang.CharSequence i_rec_end_date;
    private java.lang.CharSequence i_item_desc;
    private float i_current_price;
    private float i_wholesale_cost;
    private int i_brand_id;
    private java.lang.CharSequence i_brand;
    private int i_claws_id;
    private java.lang.CharSequence i_class;
    private int i_category_id;
    private java.lang.CharSequence i_category;
    private int i_manufact_id;
    private java.lang.CharSequence i_manufact;
    private java.lang.CharSequence i_size;
    private java.lang.CharSequence i_formulation;
    private java.lang.CharSequence i_color;
    private java.lang.CharSequence i_units;
    private java.lang.CharSequence i_container;
    private int i_manager_id;
    private java.lang.CharSequence i_product_name;

    /** Creates a new Builder */
    private Builder() {
      super(bigframe.avro.Item.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(bigframe.avro.Item.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Item instance */
    private Builder(bigframe.avro.Item other) {
            super(bigframe.avro.Item.SCHEMA$);
      if (isValidValue(fields()[0], other.i_item_sk)) {
        this.i_item_sk = data().deepCopy(fields()[0].schema(), other.i_item_sk);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.i_item_id)) {
        this.i_item_id = data().deepCopy(fields()[1].schema(), other.i_item_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.i_rec_start_date)) {
        this.i_rec_start_date = data().deepCopy(fields()[2].schema(), other.i_rec_start_date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.i_rec_end_date)) {
        this.i_rec_end_date = data().deepCopy(fields()[3].schema(), other.i_rec_end_date);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.i_item_desc)) {
        this.i_item_desc = data().deepCopy(fields()[4].schema(), other.i_item_desc);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.i_current_price)) {
        this.i_current_price = data().deepCopy(fields()[5].schema(), other.i_current_price);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.i_wholesale_cost)) {
        this.i_wholesale_cost = data().deepCopy(fields()[6].schema(), other.i_wholesale_cost);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.i_brand_id)) {
        this.i_brand_id = data().deepCopy(fields()[7].schema(), other.i_brand_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.i_brand)) {
        this.i_brand = data().deepCopy(fields()[8].schema(), other.i_brand);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.i_claws_id)) {
        this.i_claws_id = data().deepCopy(fields()[9].schema(), other.i_claws_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.i_class)) {
        this.i_class = data().deepCopy(fields()[10].schema(), other.i_class);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.i_category_id)) {
        this.i_category_id = data().deepCopy(fields()[11].schema(), other.i_category_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.i_category)) {
        this.i_category = data().deepCopy(fields()[12].schema(), other.i_category);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.i_manufact_id)) {
        this.i_manufact_id = data().deepCopy(fields()[13].schema(), other.i_manufact_id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.i_manufact)) {
        this.i_manufact = data().deepCopy(fields()[14].schema(), other.i_manufact);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.i_size)) {
        this.i_size = data().deepCopy(fields()[15].schema(), other.i_size);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.i_formulation)) {
        this.i_formulation = data().deepCopy(fields()[16].schema(), other.i_formulation);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.i_color)) {
        this.i_color = data().deepCopy(fields()[17].schema(), other.i_color);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.i_units)) {
        this.i_units = data().deepCopy(fields()[18].schema(), other.i_units);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.i_container)) {
        this.i_container = data().deepCopy(fields()[19].schema(), other.i_container);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.i_manager_id)) {
        this.i_manager_id = data().deepCopy(fields()[20].schema(), other.i_manager_id);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.i_product_name)) {
        this.i_product_name = data().deepCopy(fields()[21].schema(), other.i_product_name);
        fieldSetFlags()[21] = true;
      }
    }

    /** Gets the value of the 'i_item_sk' field */
    public java.lang.Integer getIItemSk() {
      return i_item_sk;
    }
    
    /** Sets the value of the 'i_item_sk' field */
    public bigframe.avro.Item.Builder setIItemSk(int value) {
      validate(fields()[0], value);
      this.i_item_sk = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'i_item_sk' field has been set */
    public boolean hasIItemSk() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'i_item_sk' field */
    public bigframe.avro.Item.Builder clearIItemSk() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'i_item_id' field */
    public java.lang.CharSequence getIItemId() {
      return i_item_id;
    }
    
    /** Sets the value of the 'i_item_id' field */
    public bigframe.avro.Item.Builder setIItemId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.i_item_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'i_item_id' field has been set */
    public boolean hasIItemId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'i_item_id' field */
    public bigframe.avro.Item.Builder clearIItemId() {
      i_item_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'i_rec_start_date' field */
    public java.lang.CharSequence getIRecStartDate() {
      return i_rec_start_date;
    }
    
    /** Sets the value of the 'i_rec_start_date' field */
    public bigframe.avro.Item.Builder setIRecStartDate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.i_rec_start_date = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'i_rec_start_date' field has been set */
    public boolean hasIRecStartDate() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'i_rec_start_date' field */
    public bigframe.avro.Item.Builder clearIRecStartDate() {
      i_rec_start_date = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'i_rec_end_date' field */
    public java.lang.CharSequence getIRecEndDate() {
      return i_rec_end_date;
    }
    
    /** Sets the value of the 'i_rec_end_date' field */
    public bigframe.avro.Item.Builder setIRecEndDate(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.i_rec_end_date = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'i_rec_end_date' field has been set */
    public boolean hasIRecEndDate() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'i_rec_end_date' field */
    public bigframe.avro.Item.Builder clearIRecEndDate() {
      i_rec_end_date = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'i_item_desc' field */
    public java.lang.CharSequence getIItemDesc() {
      return i_item_desc;
    }
    
    /** Sets the value of the 'i_item_desc' field */
    public bigframe.avro.Item.Builder setIItemDesc(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.i_item_desc = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'i_item_desc' field has been set */
    public boolean hasIItemDesc() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'i_item_desc' field */
    public bigframe.avro.Item.Builder clearIItemDesc() {
      i_item_desc = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'i_current_price' field */
    public java.lang.Float getICurrentPrice() {
      return i_current_price;
    }
    
    /** Sets the value of the 'i_current_price' field */
    public bigframe.avro.Item.Builder setICurrentPrice(float value) {
      validate(fields()[5], value);
      this.i_current_price = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'i_current_price' field has been set */
    public boolean hasICurrentPrice() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'i_current_price' field */
    public bigframe.avro.Item.Builder clearICurrentPrice() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'i_wholesale_cost' field */
    public java.lang.Float getIWholesaleCost() {
      return i_wholesale_cost;
    }
    
    /** Sets the value of the 'i_wholesale_cost' field */
    public bigframe.avro.Item.Builder setIWholesaleCost(float value) {
      validate(fields()[6], value);
      this.i_wholesale_cost = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'i_wholesale_cost' field has been set */
    public boolean hasIWholesaleCost() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'i_wholesale_cost' field */
    public bigframe.avro.Item.Builder clearIWholesaleCost() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'i_brand_id' field */
    public java.lang.Integer getIBrandId() {
      return i_brand_id;
    }
    
    /** Sets the value of the 'i_brand_id' field */
    public bigframe.avro.Item.Builder setIBrandId(int value) {
      validate(fields()[7], value);
      this.i_brand_id = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'i_brand_id' field has been set */
    public boolean hasIBrandId() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'i_brand_id' field */
    public bigframe.avro.Item.Builder clearIBrandId() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'i_brand' field */
    public java.lang.CharSequence getIBrand() {
      return i_brand;
    }
    
    /** Sets the value of the 'i_brand' field */
    public bigframe.avro.Item.Builder setIBrand(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.i_brand = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'i_brand' field has been set */
    public boolean hasIBrand() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'i_brand' field */
    public bigframe.avro.Item.Builder clearIBrand() {
      i_brand = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'i_claws_id' field */
    public java.lang.Integer getIClawsId() {
      return i_claws_id;
    }
    
    /** Sets the value of the 'i_claws_id' field */
    public bigframe.avro.Item.Builder setIClawsId(int value) {
      validate(fields()[9], value);
      this.i_claws_id = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'i_claws_id' field has been set */
    public boolean hasIClawsId() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'i_claws_id' field */
    public bigframe.avro.Item.Builder clearIClawsId() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'i_class' field */
    public java.lang.CharSequence getIClass() {
      return i_class;
    }
    
    /** Sets the value of the 'i_class' field */
    public bigframe.avro.Item.Builder setIClass(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.i_class = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'i_class' field has been set */
    public boolean hasIClass() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'i_class' field */
    public bigframe.avro.Item.Builder clearIClass() {
      i_class = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'i_category_id' field */
    public java.lang.Integer getICategoryId() {
      return i_category_id;
    }
    
    /** Sets the value of the 'i_category_id' field */
    public bigframe.avro.Item.Builder setICategoryId(int value) {
      validate(fields()[11], value);
      this.i_category_id = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'i_category_id' field has been set */
    public boolean hasICategoryId() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'i_category_id' field */
    public bigframe.avro.Item.Builder clearICategoryId() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'i_category' field */
    public java.lang.CharSequence getICategory() {
      return i_category;
    }
    
    /** Sets the value of the 'i_category' field */
    public bigframe.avro.Item.Builder setICategory(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.i_category = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'i_category' field has been set */
    public boolean hasICategory() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'i_category' field */
    public bigframe.avro.Item.Builder clearICategory() {
      i_category = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'i_manufact_id' field */
    public java.lang.Integer getIManufactId() {
      return i_manufact_id;
    }
    
    /** Sets the value of the 'i_manufact_id' field */
    public bigframe.avro.Item.Builder setIManufactId(int value) {
      validate(fields()[13], value);
      this.i_manufact_id = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'i_manufact_id' field has been set */
    public boolean hasIManufactId() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'i_manufact_id' field */
    public bigframe.avro.Item.Builder clearIManufactId() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'i_manufact' field */
    public java.lang.CharSequence getIManufact() {
      return i_manufact;
    }
    
    /** Sets the value of the 'i_manufact' field */
    public bigframe.avro.Item.Builder setIManufact(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.i_manufact = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'i_manufact' field has been set */
    public boolean hasIManufact() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'i_manufact' field */
    public bigframe.avro.Item.Builder clearIManufact() {
      i_manufact = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'i_size' field */
    public java.lang.CharSequence getISize() {
      return i_size;
    }
    
    /** Sets the value of the 'i_size' field */
    public bigframe.avro.Item.Builder setISize(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.i_size = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'i_size' field has been set */
    public boolean hasISize() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'i_size' field */
    public bigframe.avro.Item.Builder clearISize() {
      i_size = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'i_formulation' field */
    public java.lang.CharSequence getIFormulation() {
      return i_formulation;
    }
    
    /** Sets the value of the 'i_formulation' field */
    public bigframe.avro.Item.Builder setIFormulation(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.i_formulation = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'i_formulation' field has been set */
    public boolean hasIFormulation() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'i_formulation' field */
    public bigframe.avro.Item.Builder clearIFormulation() {
      i_formulation = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'i_color' field */
    public java.lang.CharSequence getIColor() {
      return i_color;
    }
    
    /** Sets the value of the 'i_color' field */
    public bigframe.avro.Item.Builder setIColor(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.i_color = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'i_color' field has been set */
    public boolean hasIColor() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'i_color' field */
    public bigframe.avro.Item.Builder clearIColor() {
      i_color = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'i_units' field */
    public java.lang.CharSequence getIUnits() {
      return i_units;
    }
    
    /** Sets the value of the 'i_units' field */
    public bigframe.avro.Item.Builder setIUnits(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.i_units = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'i_units' field has been set */
    public boolean hasIUnits() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'i_units' field */
    public bigframe.avro.Item.Builder clearIUnits() {
      i_units = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'i_container' field */
    public java.lang.CharSequence getIContainer() {
      return i_container;
    }
    
    /** Sets the value of the 'i_container' field */
    public bigframe.avro.Item.Builder setIContainer(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.i_container = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'i_container' field has been set */
    public boolean hasIContainer() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'i_container' field */
    public bigframe.avro.Item.Builder clearIContainer() {
      i_container = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'i_manager_id' field */
    public java.lang.Integer getIManagerId() {
      return i_manager_id;
    }
    
    /** Sets the value of the 'i_manager_id' field */
    public bigframe.avro.Item.Builder setIManagerId(int value) {
      validate(fields()[20], value);
      this.i_manager_id = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'i_manager_id' field has been set */
    public boolean hasIManagerId() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'i_manager_id' field */
    public bigframe.avro.Item.Builder clearIManagerId() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'i_product_name' field */
    public java.lang.CharSequence getIProductName() {
      return i_product_name;
    }
    
    /** Sets the value of the 'i_product_name' field */
    public bigframe.avro.Item.Builder setIProductName(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.i_product_name = value;
      fieldSetFlags()[21] = true;
      return this; 
    }
    
    /** Checks whether the 'i_product_name' field has been set */
    public boolean hasIProductName() {
      return fieldSetFlags()[21];
    }
    
    /** Clears the value of the 'i_product_name' field */
    public bigframe.avro.Item.Builder clearIProductName() {
      i_product_name = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    @Override
    public Item build() {
      try {
        Item record = new Item();
        record.i_item_sk = fieldSetFlags()[0] ? this.i_item_sk : (java.lang.Integer) defaultValue(fields()[0]);
        record.i_item_id = fieldSetFlags()[1] ? this.i_item_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.i_rec_start_date = fieldSetFlags()[2] ? this.i_rec_start_date : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.i_rec_end_date = fieldSetFlags()[3] ? this.i_rec_end_date : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.i_item_desc = fieldSetFlags()[4] ? this.i_item_desc : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.i_current_price = fieldSetFlags()[5] ? this.i_current_price : (java.lang.Float) defaultValue(fields()[5]);
        record.i_wholesale_cost = fieldSetFlags()[6] ? this.i_wholesale_cost : (java.lang.Float) defaultValue(fields()[6]);
        record.i_brand_id = fieldSetFlags()[7] ? this.i_brand_id : (java.lang.Integer) defaultValue(fields()[7]);
        record.i_brand = fieldSetFlags()[8] ? this.i_brand : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.i_claws_id = fieldSetFlags()[9] ? this.i_claws_id : (java.lang.Integer) defaultValue(fields()[9]);
        record.i_class = fieldSetFlags()[10] ? this.i_class : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.i_category_id = fieldSetFlags()[11] ? this.i_category_id : (java.lang.Integer) defaultValue(fields()[11]);
        record.i_category = fieldSetFlags()[12] ? this.i_category : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.i_manufact_id = fieldSetFlags()[13] ? this.i_manufact_id : (java.lang.Integer) defaultValue(fields()[13]);
        record.i_manufact = fieldSetFlags()[14] ? this.i_manufact : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.i_size = fieldSetFlags()[15] ? this.i_size : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.i_formulation = fieldSetFlags()[16] ? this.i_formulation : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.i_color = fieldSetFlags()[17] ? this.i_color : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.i_units = fieldSetFlags()[18] ? this.i_units : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.i_container = fieldSetFlags()[19] ? this.i_container : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.i_manager_id = fieldSetFlags()[20] ? this.i_manager_id : (java.lang.Integer) defaultValue(fields()[20]);
        record.i_product_name = fieldSetFlags()[21] ? this.i_product_name : (java.lang.CharSequence) defaultValue(fields()[21]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
