/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Promotion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Promotion\",\"namespace\":\"bigframe.avro\",\"fields\":[{\"name\":\"p_promo_sk\",\"type\":\"int\"},{\"name\":\"p_promo_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_start_date_sk\",\"type\":[\"null\",\"int\"]},{\"name\":\"p_end_date_sk\",\"type\":[\"null\",\"int\"]},{\"name\":\"p_item_sk\",\"type\":[\"null\",\"int\"]},{\"name\":\"p_cost\",\"type\":[\"null\",\"float\"]},{\"name\":\"p_response_target\",\"type\":[\"null\",\"int\"]},{\"name\":\"p_promo_name\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_dmail\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_email\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_catalog\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_tv\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_radio\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_press\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_event\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_demo\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_details\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_purpose\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_discount_active\",\"type\":[\"null\",\"string\"]}]}");
  @Deprecated public int p_promo_sk;
  @Deprecated public java.lang.CharSequence p_promo_id;
  @Deprecated public java.lang.Integer p_start_date_sk;
  @Deprecated public java.lang.Integer p_end_date_sk;
  @Deprecated public java.lang.Integer p_item_sk;
  @Deprecated public java.lang.Float p_cost;
  @Deprecated public java.lang.Integer p_response_target;
  @Deprecated public java.lang.CharSequence p_promo_name;
  @Deprecated public java.lang.CharSequence p_channel_dmail;
  @Deprecated public java.lang.CharSequence p_channel_email;
  @Deprecated public java.lang.CharSequence p_channel_catalog;
  @Deprecated public java.lang.CharSequence p_channel_tv;
  @Deprecated public java.lang.CharSequence p_channel_radio;
  @Deprecated public java.lang.CharSequence p_channel_press;
  @Deprecated public java.lang.CharSequence p_channel_event;
  @Deprecated public java.lang.CharSequence p_channel_demo;
  @Deprecated public java.lang.CharSequence p_channel_details;
  @Deprecated public java.lang.CharSequence p_purpose;
  @Deprecated public java.lang.CharSequence p_discount_active;

  /**
   * Default constructor.
   */
  public Promotion() {}

  /**
   * All-args constructor.
   */
  public Promotion(java.lang.Integer p_promo_sk, java.lang.CharSequence p_promo_id, java.lang.Integer p_start_date_sk, java.lang.Integer p_end_date_sk, java.lang.Integer p_item_sk, java.lang.Float p_cost, java.lang.Integer p_response_target, java.lang.CharSequence p_promo_name, java.lang.CharSequence p_channel_dmail, java.lang.CharSequence p_channel_email, java.lang.CharSequence p_channel_catalog, java.lang.CharSequence p_channel_tv, java.lang.CharSequence p_channel_radio, java.lang.CharSequence p_channel_press, java.lang.CharSequence p_channel_event, java.lang.CharSequence p_channel_demo, java.lang.CharSequence p_channel_details, java.lang.CharSequence p_purpose, java.lang.CharSequence p_discount_active) {
    this.p_promo_sk = p_promo_sk;
    this.p_promo_id = p_promo_id;
    this.p_start_date_sk = p_start_date_sk;
    this.p_end_date_sk = p_end_date_sk;
    this.p_item_sk = p_item_sk;
    this.p_cost = p_cost;
    this.p_response_target = p_response_target;
    this.p_promo_name = p_promo_name;
    this.p_channel_dmail = p_channel_dmail;
    this.p_channel_email = p_channel_email;
    this.p_channel_catalog = p_channel_catalog;
    this.p_channel_tv = p_channel_tv;
    this.p_channel_radio = p_channel_radio;
    this.p_channel_press = p_channel_press;
    this.p_channel_event = p_channel_event;
    this.p_channel_demo = p_channel_demo;
    this.p_channel_details = p_channel_details;
    this.p_purpose = p_purpose;
    this.p_discount_active = p_discount_active;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return p_promo_sk;
    case 1: return p_promo_id;
    case 2: return p_start_date_sk;
    case 3: return p_end_date_sk;
    case 4: return p_item_sk;
    case 5: return p_cost;
    case 6: return p_response_target;
    case 7: return p_promo_name;
    case 8: return p_channel_dmail;
    case 9: return p_channel_email;
    case 10: return p_channel_catalog;
    case 11: return p_channel_tv;
    case 12: return p_channel_radio;
    case 13: return p_channel_press;
    case 14: return p_channel_event;
    case 15: return p_channel_demo;
    case 16: return p_channel_details;
    case 17: return p_purpose;
    case 18: return p_discount_active;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: p_promo_sk = (java.lang.Integer)value$; break;
    case 1: p_promo_id = (java.lang.CharSequence)value$; break;
    case 2: p_start_date_sk = (java.lang.Integer)value$; break;
    case 3: p_end_date_sk = (java.lang.Integer)value$; break;
    case 4: p_item_sk = (java.lang.Integer)value$; break;
    case 5: p_cost = (java.lang.Float)value$; break;
    case 6: p_response_target = (java.lang.Integer)value$; break;
    case 7: p_promo_name = (java.lang.CharSequence)value$; break;
    case 8: p_channel_dmail = (java.lang.CharSequence)value$; break;
    case 9: p_channel_email = (java.lang.CharSequence)value$; break;
    case 10: p_channel_catalog = (java.lang.CharSequence)value$; break;
    case 11: p_channel_tv = (java.lang.CharSequence)value$; break;
    case 12: p_channel_radio = (java.lang.CharSequence)value$; break;
    case 13: p_channel_press = (java.lang.CharSequence)value$; break;
    case 14: p_channel_event = (java.lang.CharSequence)value$; break;
    case 15: p_channel_demo = (java.lang.CharSequence)value$; break;
    case 16: p_channel_details = (java.lang.CharSequence)value$; break;
    case 17: p_purpose = (java.lang.CharSequence)value$; break;
    case 18: p_discount_active = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'p_promo_sk' field.
   */
  public java.lang.Integer getPPromoSk() {
    return p_promo_sk;
  }

  /**
   * Sets the value of the 'p_promo_sk' field.
   * @param value the value to set.
   */
  public void setPPromoSk(java.lang.Integer value) {
    this.p_promo_sk = value;
  }

  /**
   * Gets the value of the 'p_promo_id' field.
   */
  public java.lang.CharSequence getPPromoId() {
    return p_promo_id;
  }

  /**
   * Sets the value of the 'p_promo_id' field.
   * @param value the value to set.
   */
  public void setPPromoId(java.lang.CharSequence value) {
    this.p_promo_id = value;
  }

  /**
   * Gets the value of the 'p_start_date_sk' field.
   */
  public java.lang.Integer getPStartDateSk() {
    return p_start_date_sk;
  }

  /**
   * Sets the value of the 'p_start_date_sk' field.
   * @param value the value to set.
   */
  public void setPStartDateSk(java.lang.Integer value) {
    this.p_start_date_sk = value;
  }

  /**
   * Gets the value of the 'p_end_date_sk' field.
   */
  public java.lang.Integer getPEndDateSk() {
    return p_end_date_sk;
  }

  /**
   * Sets the value of the 'p_end_date_sk' field.
   * @param value the value to set.
   */
  public void setPEndDateSk(java.lang.Integer value) {
    this.p_end_date_sk = value;
  }

  /**
   * Gets the value of the 'p_item_sk' field.
   */
  public java.lang.Integer getPItemSk() {
    return p_item_sk;
  }

  /**
   * Sets the value of the 'p_item_sk' field.
   * @param value the value to set.
   */
  public void setPItemSk(java.lang.Integer value) {
    this.p_item_sk = value;
  }

  /**
   * Gets the value of the 'p_cost' field.
   */
  public java.lang.Float getPCost() {
    return p_cost;
  }

  /**
   * Sets the value of the 'p_cost' field.
   * @param value the value to set.
   */
  public void setPCost(java.lang.Float value) {
    this.p_cost = value;
  }

  /**
   * Gets the value of the 'p_response_target' field.
   */
  public java.lang.Integer getPResponseTarget() {
    return p_response_target;
  }

  /**
   * Sets the value of the 'p_response_target' field.
   * @param value the value to set.
   */
  public void setPResponseTarget(java.lang.Integer value) {
    this.p_response_target = value;
  }

  /**
   * Gets the value of the 'p_promo_name' field.
   */
  public java.lang.CharSequence getPPromoName() {
    return p_promo_name;
  }

  /**
   * Sets the value of the 'p_promo_name' field.
   * @param value the value to set.
   */
  public void setPPromoName(java.lang.CharSequence value) {
    this.p_promo_name = value;
  }

  /**
   * Gets the value of the 'p_channel_dmail' field.
   */
  public java.lang.CharSequence getPChannelDmail() {
    return p_channel_dmail;
  }

  /**
   * Sets the value of the 'p_channel_dmail' field.
   * @param value the value to set.
   */
  public void setPChannelDmail(java.lang.CharSequence value) {
    this.p_channel_dmail = value;
  }

  /**
   * Gets the value of the 'p_channel_email' field.
   */
  public java.lang.CharSequence getPChannelEmail() {
    return p_channel_email;
  }

  /**
   * Sets the value of the 'p_channel_email' field.
   * @param value the value to set.
   */
  public void setPChannelEmail(java.lang.CharSequence value) {
    this.p_channel_email = value;
  }

  /**
   * Gets the value of the 'p_channel_catalog' field.
   */
  public java.lang.CharSequence getPChannelCatalog() {
    return p_channel_catalog;
  }

  /**
   * Sets the value of the 'p_channel_catalog' field.
   * @param value the value to set.
   */
  public void setPChannelCatalog(java.lang.CharSequence value) {
    this.p_channel_catalog = value;
  }

  /**
   * Gets the value of the 'p_channel_tv' field.
   */
  public java.lang.CharSequence getPChannelTv() {
    return p_channel_tv;
  }

  /**
   * Sets the value of the 'p_channel_tv' field.
   * @param value the value to set.
   */
  public void setPChannelTv(java.lang.CharSequence value) {
    this.p_channel_tv = value;
  }

  /**
   * Gets the value of the 'p_channel_radio' field.
   */
  public java.lang.CharSequence getPChannelRadio() {
    return p_channel_radio;
  }

  /**
   * Sets the value of the 'p_channel_radio' field.
   * @param value the value to set.
   */
  public void setPChannelRadio(java.lang.CharSequence value) {
    this.p_channel_radio = value;
  }

  /**
   * Gets the value of the 'p_channel_press' field.
   */
  public java.lang.CharSequence getPChannelPress() {
    return p_channel_press;
  }

  /**
   * Sets the value of the 'p_channel_press' field.
   * @param value the value to set.
   */
  public void setPChannelPress(java.lang.CharSequence value) {
    this.p_channel_press = value;
  }

  /**
   * Gets the value of the 'p_channel_event' field.
   */
  public java.lang.CharSequence getPChannelEvent() {
    return p_channel_event;
  }

  /**
   * Sets the value of the 'p_channel_event' field.
   * @param value the value to set.
   */
  public void setPChannelEvent(java.lang.CharSequence value) {
    this.p_channel_event = value;
  }

  /**
   * Gets the value of the 'p_channel_demo' field.
   */
  public java.lang.CharSequence getPChannelDemo() {
    return p_channel_demo;
  }

  /**
   * Sets the value of the 'p_channel_demo' field.
   * @param value the value to set.
   */
  public void setPChannelDemo(java.lang.CharSequence value) {
    this.p_channel_demo = value;
  }

  /**
   * Gets the value of the 'p_channel_details' field.
   */
  public java.lang.CharSequence getPChannelDetails() {
    return p_channel_details;
  }

  /**
   * Sets the value of the 'p_channel_details' field.
   * @param value the value to set.
   */
  public void setPChannelDetails(java.lang.CharSequence value) {
    this.p_channel_details = value;
  }

  /**
   * Gets the value of the 'p_purpose' field.
   */
  public java.lang.CharSequence getPPurpose() {
    return p_purpose;
  }

  /**
   * Sets the value of the 'p_purpose' field.
   * @param value the value to set.
   */
  public void setPPurpose(java.lang.CharSequence value) {
    this.p_purpose = value;
  }

  /**
   * Gets the value of the 'p_discount_active' field.
   */
  public java.lang.CharSequence getPDiscountActive() {
    return p_discount_active;
  }

  /**
   * Sets the value of the 'p_discount_active' field.
   * @param value the value to set.
   */
  public void setPDiscountActive(java.lang.CharSequence value) {
    this.p_discount_active = value;
  }

  /** Creates a new Promotion RecordBuilder */
  public static bigframe.avro.Promotion.Builder newBuilder() {
    return new bigframe.avro.Promotion.Builder();
  }
  
  /** Creates a new Promotion RecordBuilder by copying an existing Builder */
  public static bigframe.avro.Promotion.Builder newBuilder(bigframe.avro.Promotion.Builder other) {
    return new bigframe.avro.Promotion.Builder(other);
  }
  
  /** Creates a new Promotion RecordBuilder by copying an existing Promotion instance */
  public static bigframe.avro.Promotion.Builder newBuilder(bigframe.avro.Promotion other) {
    return new bigframe.avro.Promotion.Builder(other);
  }
  
  /**
   * RecordBuilder for Promotion instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Promotion>
    implements org.apache.avro.data.RecordBuilder<Promotion> {

    private int p_promo_sk;
    private java.lang.CharSequence p_promo_id;
    private java.lang.Integer p_start_date_sk;
    private java.lang.Integer p_end_date_sk;
    private java.lang.Integer p_item_sk;
    private java.lang.Float p_cost;
    private java.lang.Integer p_response_target;
    private java.lang.CharSequence p_promo_name;
    private java.lang.CharSequence p_channel_dmail;
    private java.lang.CharSequence p_channel_email;
    private java.lang.CharSequence p_channel_catalog;
    private java.lang.CharSequence p_channel_tv;
    private java.lang.CharSequence p_channel_radio;
    private java.lang.CharSequence p_channel_press;
    private java.lang.CharSequence p_channel_event;
    private java.lang.CharSequence p_channel_demo;
    private java.lang.CharSequence p_channel_details;
    private java.lang.CharSequence p_purpose;
    private java.lang.CharSequence p_discount_active;

    /** Creates a new Builder */
    private Builder() {
      super(bigframe.avro.Promotion.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(bigframe.avro.Promotion.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Promotion instance */
    private Builder(bigframe.avro.Promotion other) {
            super(bigframe.avro.Promotion.SCHEMA$);
      if (isValidValue(fields()[0], other.p_promo_sk)) {
        this.p_promo_sk = data().deepCopy(fields()[0].schema(), other.p_promo_sk);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.p_promo_id)) {
        this.p_promo_id = data().deepCopy(fields()[1].schema(), other.p_promo_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.p_start_date_sk)) {
        this.p_start_date_sk = data().deepCopy(fields()[2].schema(), other.p_start_date_sk);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.p_end_date_sk)) {
        this.p_end_date_sk = data().deepCopy(fields()[3].schema(), other.p_end_date_sk);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.p_item_sk)) {
        this.p_item_sk = data().deepCopy(fields()[4].schema(), other.p_item_sk);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.p_cost)) {
        this.p_cost = data().deepCopy(fields()[5].schema(), other.p_cost);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.p_response_target)) {
        this.p_response_target = data().deepCopy(fields()[6].schema(), other.p_response_target);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.p_promo_name)) {
        this.p_promo_name = data().deepCopy(fields()[7].schema(), other.p_promo_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.p_channel_dmail)) {
        this.p_channel_dmail = data().deepCopy(fields()[8].schema(), other.p_channel_dmail);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.p_channel_email)) {
        this.p_channel_email = data().deepCopy(fields()[9].schema(), other.p_channel_email);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.p_channel_catalog)) {
        this.p_channel_catalog = data().deepCopy(fields()[10].schema(), other.p_channel_catalog);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.p_channel_tv)) {
        this.p_channel_tv = data().deepCopy(fields()[11].schema(), other.p_channel_tv);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.p_channel_radio)) {
        this.p_channel_radio = data().deepCopy(fields()[12].schema(), other.p_channel_radio);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.p_channel_press)) {
        this.p_channel_press = data().deepCopy(fields()[13].schema(), other.p_channel_press);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.p_channel_event)) {
        this.p_channel_event = data().deepCopy(fields()[14].schema(), other.p_channel_event);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.p_channel_demo)) {
        this.p_channel_demo = data().deepCopy(fields()[15].schema(), other.p_channel_demo);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.p_channel_details)) {
        this.p_channel_details = data().deepCopy(fields()[16].schema(), other.p_channel_details);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.p_purpose)) {
        this.p_purpose = data().deepCopy(fields()[17].schema(), other.p_purpose);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.p_discount_active)) {
        this.p_discount_active = data().deepCopy(fields()[18].schema(), other.p_discount_active);
        fieldSetFlags()[18] = true;
      }
    }

    /** Gets the value of the 'p_promo_sk' field */
    public java.lang.Integer getPPromoSk() {
      return p_promo_sk;
    }
    
    /** Sets the value of the 'p_promo_sk' field */
    public bigframe.avro.Promotion.Builder setPPromoSk(int value) {
      validate(fields()[0], value);
      this.p_promo_sk = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'p_promo_sk' field has been set */
    public boolean hasPPromoSk() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'p_promo_sk' field */
    public bigframe.avro.Promotion.Builder clearPPromoSk() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'p_promo_id' field */
    public java.lang.CharSequence getPPromoId() {
      return p_promo_id;
    }
    
    /** Sets the value of the 'p_promo_id' field */
    public bigframe.avro.Promotion.Builder setPPromoId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.p_promo_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'p_promo_id' field has been set */
    public boolean hasPPromoId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'p_promo_id' field */
    public bigframe.avro.Promotion.Builder clearPPromoId() {
      p_promo_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'p_start_date_sk' field */
    public java.lang.Integer getPStartDateSk() {
      return p_start_date_sk;
    }
    
    /** Sets the value of the 'p_start_date_sk' field */
    public bigframe.avro.Promotion.Builder setPStartDateSk(java.lang.Integer value) {
      validate(fields()[2], value);
      this.p_start_date_sk = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'p_start_date_sk' field has been set */
    public boolean hasPStartDateSk() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'p_start_date_sk' field */
    public bigframe.avro.Promotion.Builder clearPStartDateSk() {
      p_start_date_sk = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'p_end_date_sk' field */
    public java.lang.Integer getPEndDateSk() {
      return p_end_date_sk;
    }
    
    /** Sets the value of the 'p_end_date_sk' field */
    public bigframe.avro.Promotion.Builder setPEndDateSk(java.lang.Integer value) {
      validate(fields()[3], value);
      this.p_end_date_sk = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'p_end_date_sk' field has been set */
    public boolean hasPEndDateSk() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'p_end_date_sk' field */
    public bigframe.avro.Promotion.Builder clearPEndDateSk() {
      p_end_date_sk = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'p_item_sk' field */
    public java.lang.Integer getPItemSk() {
      return p_item_sk;
    }
    
    /** Sets the value of the 'p_item_sk' field */
    public bigframe.avro.Promotion.Builder setPItemSk(java.lang.Integer value) {
      validate(fields()[4], value);
      this.p_item_sk = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'p_item_sk' field has been set */
    public boolean hasPItemSk() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'p_item_sk' field */
    public bigframe.avro.Promotion.Builder clearPItemSk() {
      p_item_sk = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'p_cost' field */
    public java.lang.Float getPCost() {
      return p_cost;
    }
    
    /** Sets the value of the 'p_cost' field */
    public bigframe.avro.Promotion.Builder setPCost(java.lang.Float value) {
      validate(fields()[5], value);
      this.p_cost = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'p_cost' field has been set */
    public boolean hasPCost() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'p_cost' field */
    public bigframe.avro.Promotion.Builder clearPCost() {
      p_cost = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'p_response_target' field */
    public java.lang.Integer getPResponseTarget() {
      return p_response_target;
    }
    
    /** Sets the value of the 'p_response_target' field */
    public bigframe.avro.Promotion.Builder setPResponseTarget(java.lang.Integer value) {
      validate(fields()[6], value);
      this.p_response_target = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'p_response_target' field has been set */
    public boolean hasPResponseTarget() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'p_response_target' field */
    public bigframe.avro.Promotion.Builder clearPResponseTarget() {
      p_response_target = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'p_promo_name' field */
    public java.lang.CharSequence getPPromoName() {
      return p_promo_name;
    }
    
    /** Sets the value of the 'p_promo_name' field */
    public bigframe.avro.Promotion.Builder setPPromoName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.p_promo_name = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'p_promo_name' field has been set */
    public boolean hasPPromoName() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'p_promo_name' field */
    public bigframe.avro.Promotion.Builder clearPPromoName() {
      p_promo_name = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'p_channel_dmail' field */
    public java.lang.CharSequence getPChannelDmail() {
      return p_channel_dmail;
    }
    
    /** Sets the value of the 'p_channel_dmail' field */
    public bigframe.avro.Promotion.Builder setPChannelDmail(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.p_channel_dmail = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'p_channel_dmail' field has been set */
    public boolean hasPChannelDmail() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'p_channel_dmail' field */
    public bigframe.avro.Promotion.Builder clearPChannelDmail() {
      p_channel_dmail = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'p_channel_email' field */
    public java.lang.CharSequence getPChannelEmail() {
      return p_channel_email;
    }
    
    /** Sets the value of the 'p_channel_email' field */
    public bigframe.avro.Promotion.Builder setPChannelEmail(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.p_channel_email = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'p_channel_email' field has been set */
    public boolean hasPChannelEmail() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'p_channel_email' field */
    public bigframe.avro.Promotion.Builder clearPChannelEmail() {
      p_channel_email = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'p_channel_catalog' field */
    public java.lang.CharSequence getPChannelCatalog() {
      return p_channel_catalog;
    }
    
    /** Sets the value of the 'p_channel_catalog' field */
    public bigframe.avro.Promotion.Builder setPChannelCatalog(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.p_channel_catalog = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'p_channel_catalog' field has been set */
    public boolean hasPChannelCatalog() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'p_channel_catalog' field */
    public bigframe.avro.Promotion.Builder clearPChannelCatalog() {
      p_channel_catalog = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'p_channel_tv' field */
    public java.lang.CharSequence getPChannelTv() {
      return p_channel_tv;
    }
    
    /** Sets the value of the 'p_channel_tv' field */
    public bigframe.avro.Promotion.Builder setPChannelTv(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.p_channel_tv = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'p_channel_tv' field has been set */
    public boolean hasPChannelTv() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'p_channel_tv' field */
    public bigframe.avro.Promotion.Builder clearPChannelTv() {
      p_channel_tv = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'p_channel_radio' field */
    public java.lang.CharSequence getPChannelRadio() {
      return p_channel_radio;
    }
    
    /** Sets the value of the 'p_channel_radio' field */
    public bigframe.avro.Promotion.Builder setPChannelRadio(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.p_channel_radio = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'p_channel_radio' field has been set */
    public boolean hasPChannelRadio() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'p_channel_radio' field */
    public bigframe.avro.Promotion.Builder clearPChannelRadio() {
      p_channel_radio = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'p_channel_press' field */
    public java.lang.CharSequence getPChannelPress() {
      return p_channel_press;
    }
    
    /** Sets the value of the 'p_channel_press' field */
    public bigframe.avro.Promotion.Builder setPChannelPress(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.p_channel_press = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'p_channel_press' field has been set */
    public boolean hasPChannelPress() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'p_channel_press' field */
    public bigframe.avro.Promotion.Builder clearPChannelPress() {
      p_channel_press = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'p_channel_event' field */
    public java.lang.CharSequence getPChannelEvent() {
      return p_channel_event;
    }
    
    /** Sets the value of the 'p_channel_event' field */
    public bigframe.avro.Promotion.Builder setPChannelEvent(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.p_channel_event = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'p_channel_event' field has been set */
    public boolean hasPChannelEvent() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'p_channel_event' field */
    public bigframe.avro.Promotion.Builder clearPChannelEvent() {
      p_channel_event = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'p_channel_demo' field */
    public java.lang.CharSequence getPChannelDemo() {
      return p_channel_demo;
    }
    
    /** Sets the value of the 'p_channel_demo' field */
    public bigframe.avro.Promotion.Builder setPChannelDemo(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.p_channel_demo = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'p_channel_demo' field has been set */
    public boolean hasPChannelDemo() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'p_channel_demo' field */
    public bigframe.avro.Promotion.Builder clearPChannelDemo() {
      p_channel_demo = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'p_channel_details' field */
    public java.lang.CharSequence getPChannelDetails() {
      return p_channel_details;
    }
    
    /** Sets the value of the 'p_channel_details' field */
    public bigframe.avro.Promotion.Builder setPChannelDetails(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.p_channel_details = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'p_channel_details' field has been set */
    public boolean hasPChannelDetails() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'p_channel_details' field */
    public bigframe.avro.Promotion.Builder clearPChannelDetails() {
      p_channel_details = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'p_purpose' field */
    public java.lang.CharSequence getPPurpose() {
      return p_purpose;
    }
    
    /** Sets the value of the 'p_purpose' field */
    public bigframe.avro.Promotion.Builder setPPurpose(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.p_purpose = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'p_purpose' field has been set */
    public boolean hasPPurpose() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'p_purpose' field */
    public bigframe.avro.Promotion.Builder clearPPurpose() {
      p_purpose = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'p_discount_active' field */
    public java.lang.CharSequence getPDiscountActive() {
      return p_discount_active;
    }
    
    /** Sets the value of the 'p_discount_active' field */
    public bigframe.avro.Promotion.Builder setPDiscountActive(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.p_discount_active = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'p_discount_active' field has been set */
    public boolean hasPDiscountActive() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'p_discount_active' field */
    public bigframe.avro.Promotion.Builder clearPDiscountActive() {
      p_discount_active = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    @Override
    public Promotion build() {
      try {
        Promotion record = new Promotion();
        record.p_promo_sk = fieldSetFlags()[0] ? this.p_promo_sk : (java.lang.Integer) defaultValue(fields()[0]);
        record.p_promo_id = fieldSetFlags()[1] ? this.p_promo_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.p_start_date_sk = fieldSetFlags()[2] ? this.p_start_date_sk : (java.lang.Integer) defaultValue(fields()[2]);
        record.p_end_date_sk = fieldSetFlags()[3] ? this.p_end_date_sk : (java.lang.Integer) defaultValue(fields()[3]);
        record.p_item_sk = fieldSetFlags()[4] ? this.p_item_sk : (java.lang.Integer) defaultValue(fields()[4]);
        record.p_cost = fieldSetFlags()[5] ? this.p_cost : (java.lang.Float) defaultValue(fields()[5]);
        record.p_response_target = fieldSetFlags()[6] ? this.p_response_target : (java.lang.Integer) defaultValue(fields()[6]);
        record.p_promo_name = fieldSetFlags()[7] ? this.p_promo_name : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.p_channel_dmail = fieldSetFlags()[8] ? this.p_channel_dmail : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.p_channel_email = fieldSetFlags()[9] ? this.p_channel_email : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.p_channel_catalog = fieldSetFlags()[10] ? this.p_channel_catalog : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.p_channel_tv = fieldSetFlags()[11] ? this.p_channel_tv : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.p_channel_radio = fieldSetFlags()[12] ? this.p_channel_radio : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.p_channel_press = fieldSetFlags()[13] ? this.p_channel_press : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.p_channel_event = fieldSetFlags()[14] ? this.p_channel_event : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.p_channel_demo = fieldSetFlags()[15] ? this.p_channel_demo : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.p_channel_details = fieldSetFlags()[16] ? this.p_channel_details : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.p_purpose = fieldSetFlags()[17] ? this.p_purpose : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.p_discount_active = fieldSetFlags()[18] ? this.p_discount_active : (java.lang.CharSequence) defaultValue(fields()[18]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
