/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SparkParquetAvro_P {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SparkParquetAvro_P\",\"namespace\":\"bigframe.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Promotion\",\"fields\":[{\"name\":\"p_promo_sk\",\"type\":\"int\"},{\"name\":\"p_promo_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_start_date_sk\",\"type\":[\"null\",\"int\"]},{\"name\":\"p_end_date_sk\",\"type\":[\"null\",\"int\"]},{\"name\":\"p_item_sk\",\"type\":[\"null\",\"int\"]},{\"name\":\"p_cost\",\"type\":[\"null\",\"float\"]},{\"name\":\"p_response_target\",\"type\":[\"null\",\"int\"]},{\"name\":\"p_promo_name\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_dmail\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_email\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_catalog\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_tv\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_radio\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_press\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_event\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_demo\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_channel_details\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_purpose\",\"type\":[\"null\",\"string\"]},{\"name\":\"p_discount_active\",\"type\":[\"null\",\"string\"]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends SparkParquetAvro_P {
    public static final org.apache.avro.Protocol PROTOCOL = bigframe.avro.SparkParquetAvro_P.PROTOCOL;
  }
}