/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SparkParquetAvro_I {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SparkParquetAvro_I\",\"namespace\":\"bigframe.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Item\",\"fields\":[{\"name\":\"i_item_sk\",\"type\":\"int\"},{\"name\":\"i_item_id\",\"type\":\"string\"},{\"name\":\"i_rec_start_date\",\"type\":\"string\"},{\"name\":\"i_rec_end_date\",\"type\":\"string\"},{\"name\":\"i_item_desc\",\"type\":\"string\"},{\"name\":\"i_current_price\",\"type\":\"float\"},{\"name\":\"i_wholesale_cost\",\"type\":\"float\"},{\"name\":\"i_brand_id\",\"type\":\"int\"},{\"name\":\"i_brand\",\"type\":\"string\"},{\"name\":\"i_claws_id\",\"type\":\"int\"},{\"name\":\"i_class\",\"type\":\"string\"},{\"name\":\"i_category_id\",\"type\":\"int\"},{\"name\":\"i_category\",\"type\":\"string\"},{\"name\":\"i_manufact_id\",\"type\":\"int\"},{\"name\":\"i_manufact\",\"type\":\"string\"},{\"name\":\"i_size\",\"type\":\"string\"},{\"name\":\"i_formulation\",\"type\":\"string\"},{\"name\":\"i_color\",\"type\":\"string\"},{\"name\":\"i_units\",\"type\":\"string\"},{\"name\":\"i_container\",\"type\":\"string\"},{\"name\":\"i_manager_id\",\"type\":\"int\"},{\"name\":\"i_product_name\",\"type\":\"string\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends SparkParquetAvro_I {
    public static final org.apache.avro.Protocol PROTOCOL = bigframe.avro.SparkParquetAvro_I.PROTOCOL;
  }
}