/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SparkParquetAvro_WS {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SparkParquetAvro_WS\",\"namespace\":\"bigframe.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Web_Sales\",\"fields\":[{\"name\":\"ws_sold_date_sk\",\"type\":\"int\"},{\"name\":\"ws_sold_time_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_date_sk\",\"type\":\"int\"},{\"name\":\"ws_item_sk\",\"type\":\"int\"},{\"name\":\"ws_bill_customer_sk\",\"type\":\"int\"},{\"name\":\"ws_bill_cdemo_sk\",\"type\":\"int\"},{\"name\":\"ws_bill_hdemo_sk\",\"type\":\"int\"},{\"name\":\"ws_bill_addr_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_customer_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_cdemo_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_hdemo_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_addr_sk\",\"type\":\"int\"},{\"name\":\"ws_web_page_sk\",\"type\":\"int\"},{\"name\":\"ws_web_site_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_mode_sk\",\"type\":\"int\"},{\"name\":\"ws_warehouse_sk\",\"type\":\"int\"},{\"name\":\"ws_promo_sk\",\"type\":\"int\"},{\"name\":\"ws_order_number\",\"type\":\"int\"},{\"name\":\"ws_quantity\",\"type\":\"int\"},{\"name\":\"ws_wholesale_cost\",\"type\":\"float\"},{\"name\":\"ws_list_price\",\"type\":\"float\"},{\"name\":\"ws_sales_price\",\"type\":\"float\"},{\"name\":\"ws_ext_discount_amt\",\"type\":\"float\"},{\"name\":\"ws_ext_sales_price\",\"type\":\"float\"},{\"name\":\"ws_ext_wholesale_cost\",\"type\":\"float\"},{\"name\":\"ws_ext_list_price\",\"type\":\"float\"},{\"name\":\"ws_ext_tax\",\"type\":\"float\"},{\"name\":\"ws_coupon_amt\",\"type\":\"float\"},{\"name\":\"ws_ext_ship_cost\",\"type\":\"float\"},{\"name\":\"ws_net_paid\",\"type\":\"float\"},{\"name\":\"ws_net_paid_inc_tax\",\"type\":\"float\"},{\"name\":\"ws_net_paid_inc_ship\",\"type\":\"float\"},{\"name\":\"ws_net_paid_inc_ship_tax\",\"type\":\"float\"},{\"name\":\"ws_net_profit\",\"type\":\"float\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends SparkParquetAvro_WS {
    public static final org.apache.avro.Protocol PROTOCOL = bigframe.avro.SparkParquetAvro_WS.PROTOCOL;
  }
}