/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SparkParquetAvro_CS {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SparkParquetAvro_CS\",\"namespace\":\"bigframe.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Cataglog_Sales\",\"fields\":[{\"name\":\"cs_sold_date_sk\",\"type\":\"int\"},{\"name\":\"cs_sold_time_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_date_sk\",\"type\":\"int\"},{\"name\":\"cs_bill_customer_sk\",\"type\":\"int\"},{\"name\":\"cs_bill_cdemo_sk\",\"type\":\"int\"},{\"name\":\"cs_bill_hdemo_sk\",\"type\":\"int\"},{\"name\":\"cs_bill_addr_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_customer_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_cdemo_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_hdemo_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_addr_sk\",\"type\":\"int\"},{\"name\":\"cs_call_center_sk\",\"type\":\"int\"},{\"name\":\"cs_catalog_page_sk\",\"type\":\"int\"},{\"name\":\"cs_ship_mode_sk\",\"type\":\"int\"},{\"name\":\"cs_warehouse_sk\",\"type\":\"int\"},{\"name\":\"cs_item_sk\",\"type\":\"int\"},{\"name\":\"cs_promo_sk\",\"type\":\"int\"},{\"name\":\"cs_order_number\",\"type\":\"int\"},{\"name\":\"cs_quantity\",\"type\":\"int\"},{\"name\":\"cs_wholesale_cost\",\"type\":\"float\"},{\"name\":\"cs_list_price\",\"type\":\"float\"},{\"name\":\"cs_sales_price\",\"type\":\"float\"},{\"name\":\"cs_ext_discount_amt\",\"type\":\"float\"},{\"name\":\"cs_ext_sales_price\",\"type\":\"float\"},{\"name\":\"cs_ext_wholesale_cost\",\"type\":\"float\"},{\"name\":\"cs_ext_list_price\",\"type\":\"float\"},{\"name\":\"cs_ext_tax\",\"type\":\"float\"},{\"name\":\"cs_coupon_amt\",\"type\":\"float\"},{\"name\":\"cs_ext_ship_cost\",\"type\":\"float\"},{\"name\":\"cs_net_paid\",\"type\":\"float\"},{\"name\":\"cs_net_paid_inc_tax\",\"type\":\"float\"},{\"name\":\"cs_net_paid_inc_ship\",\"type\":\"float\"},{\"name\":\"cs_net_paid_inc_ship_tax\",\"type\":\"float\"},{\"name\":\"cs_net_profit\",\"type\":\"float\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends SparkParquetAvro_CS {
    public static final org.apache.avro.Protocol PROTOCOL = bigframe.avro.SparkParquetAvro_CS.PROTOCOL;
  }
}