/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SparkParquetAvro_URL {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SparkParquetAvro_URL\",\"namespace\":\"bigframe.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Url\",\"fields\":[{\"name\":\"expanded_url\",\"type\":[\"null\",\"string\"]},{\"name\":\"indices\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"int\"}]},{\"name\":\"url\",\"type\":[\"null\",\"string\"]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends SparkParquetAvro_URL {
    public static final org.apache.avro.Protocol PROTOCOL = bigframe.avro.SparkParquetAvro_URL.PROTOCOL;
  }
}