/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Store_Sales extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Store_Sales\",\"namespace\":\"bigframe.avro\",\"fields\":[{\"name\":\"ss_sold_date_sk\",\"type\":\"int\"},{\"name\":\"ss_sold_time_sk\",\"type\":\"int\"},{\"name\":\"ss_item_sk\",\"type\":\"int\"},{\"name\":\"ss_customer_sk\",\"type\":\"int\"},{\"name\":\"ss_cdemo_sk\",\"type\":\"int\"},{\"name\":\"ss_hdemo_sk\",\"type\":\"int\"},{\"name\":\"ss_addr_sk\",\"type\":\"int\"},{\"name\":\"ss_store_sk\",\"type\":\"int\"},{\"name\":\"ss_promo_sk\",\"type\":\"int\"},{\"name\":\"ss_ticket_number\",\"type\":\"int\"},{\"name\":\"ss_quantity\",\"type\":\"int\"},{\"name\":\"ss_wholesale_cost\",\"type\":\"float\"},{\"name\":\"ss_list_price\",\"type\":\"float\"},{\"name\":\"ss_sales_price\",\"type\":\"float\"},{\"name\":\"ss_ext_discount_amt\",\"type\":\"float\"},{\"name\":\"ss_ext_sales_price\",\"type\":\"float\"},{\"name\":\"ss_ext_wholesale_cost\",\"type\":\"float\"},{\"name\":\"ss_ext_list_price\",\"type\":\"float\"},{\"name\":\"ss_ext_tax\",\"type\":\"float\"},{\"name\":\"ss_coupon_amt\",\"type\":\"float\"},{\"name\":\"ss_net_paid\",\"type\":\"float\"},{\"name\":\"ss_net_paid_inc_tax\",\"type\":\"float\"},{\"name\":\"ss_net_profit\",\"type\":\"float\"}]}");
  @Deprecated public int ss_sold_date_sk;
  @Deprecated public int ss_sold_time_sk;
  @Deprecated public int ss_item_sk;
  @Deprecated public int ss_customer_sk;
  @Deprecated public int ss_cdemo_sk;
  @Deprecated public int ss_hdemo_sk;
  @Deprecated public int ss_addr_sk;
  @Deprecated public int ss_store_sk;
  @Deprecated public int ss_promo_sk;
  @Deprecated public int ss_ticket_number;
  @Deprecated public int ss_quantity;
  @Deprecated public float ss_wholesale_cost;
  @Deprecated public float ss_list_price;
  @Deprecated public float ss_sales_price;
  @Deprecated public float ss_ext_discount_amt;
  @Deprecated public float ss_ext_sales_price;
  @Deprecated public float ss_ext_wholesale_cost;
  @Deprecated public float ss_ext_list_price;
  @Deprecated public float ss_ext_tax;
  @Deprecated public float ss_coupon_amt;
  @Deprecated public float ss_net_paid;
  @Deprecated public float ss_net_paid_inc_tax;
  @Deprecated public float ss_net_profit;

  /**
   * Default constructor.
   */
  public Store_Sales() {}

  /**
   * All-args constructor.
   */
  public Store_Sales(java.lang.Integer ss_sold_date_sk, java.lang.Integer ss_sold_time_sk, java.lang.Integer ss_item_sk, java.lang.Integer ss_customer_sk, java.lang.Integer ss_cdemo_sk, java.lang.Integer ss_hdemo_sk, java.lang.Integer ss_addr_sk, java.lang.Integer ss_store_sk, java.lang.Integer ss_promo_sk, java.lang.Integer ss_ticket_number, java.lang.Integer ss_quantity, java.lang.Float ss_wholesale_cost, java.lang.Float ss_list_price, java.lang.Float ss_sales_price, java.lang.Float ss_ext_discount_amt, java.lang.Float ss_ext_sales_price, java.lang.Float ss_ext_wholesale_cost, java.lang.Float ss_ext_list_price, java.lang.Float ss_ext_tax, java.lang.Float ss_coupon_amt, java.lang.Float ss_net_paid, java.lang.Float ss_net_paid_inc_tax, java.lang.Float ss_net_profit) {
    this.ss_sold_date_sk = ss_sold_date_sk;
    this.ss_sold_time_sk = ss_sold_time_sk;
    this.ss_item_sk = ss_item_sk;
    this.ss_customer_sk = ss_customer_sk;
    this.ss_cdemo_sk = ss_cdemo_sk;
    this.ss_hdemo_sk = ss_hdemo_sk;
    this.ss_addr_sk = ss_addr_sk;
    this.ss_store_sk = ss_store_sk;
    this.ss_promo_sk = ss_promo_sk;
    this.ss_ticket_number = ss_ticket_number;
    this.ss_quantity = ss_quantity;
    this.ss_wholesale_cost = ss_wholesale_cost;
    this.ss_list_price = ss_list_price;
    this.ss_sales_price = ss_sales_price;
    this.ss_ext_discount_amt = ss_ext_discount_amt;
    this.ss_ext_sales_price = ss_ext_sales_price;
    this.ss_ext_wholesale_cost = ss_ext_wholesale_cost;
    this.ss_ext_list_price = ss_ext_list_price;
    this.ss_ext_tax = ss_ext_tax;
    this.ss_coupon_amt = ss_coupon_amt;
    this.ss_net_paid = ss_net_paid;
    this.ss_net_paid_inc_tax = ss_net_paid_inc_tax;
    this.ss_net_profit = ss_net_profit;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ss_sold_date_sk;
    case 1: return ss_sold_time_sk;
    case 2: return ss_item_sk;
    case 3: return ss_customer_sk;
    case 4: return ss_cdemo_sk;
    case 5: return ss_hdemo_sk;
    case 6: return ss_addr_sk;
    case 7: return ss_store_sk;
    case 8: return ss_promo_sk;
    case 9: return ss_ticket_number;
    case 10: return ss_quantity;
    case 11: return ss_wholesale_cost;
    case 12: return ss_list_price;
    case 13: return ss_sales_price;
    case 14: return ss_ext_discount_amt;
    case 15: return ss_ext_sales_price;
    case 16: return ss_ext_wholesale_cost;
    case 17: return ss_ext_list_price;
    case 18: return ss_ext_tax;
    case 19: return ss_coupon_amt;
    case 20: return ss_net_paid;
    case 21: return ss_net_paid_inc_tax;
    case 22: return ss_net_profit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ss_sold_date_sk = (java.lang.Integer)value$; break;
    case 1: ss_sold_time_sk = (java.lang.Integer)value$; break;
    case 2: ss_item_sk = (java.lang.Integer)value$; break;
    case 3: ss_customer_sk = (java.lang.Integer)value$; break;
    case 4: ss_cdemo_sk = (java.lang.Integer)value$; break;
    case 5: ss_hdemo_sk = (java.lang.Integer)value$; break;
    case 6: ss_addr_sk = (java.lang.Integer)value$; break;
    case 7: ss_store_sk = (java.lang.Integer)value$; break;
    case 8: ss_promo_sk = (java.lang.Integer)value$; break;
    case 9: ss_ticket_number = (java.lang.Integer)value$; break;
    case 10: ss_quantity = (java.lang.Integer)value$; break;
    case 11: ss_wholesale_cost = (java.lang.Float)value$; break;
    case 12: ss_list_price = (java.lang.Float)value$; break;
    case 13: ss_sales_price = (java.lang.Float)value$; break;
    case 14: ss_ext_discount_amt = (java.lang.Float)value$; break;
    case 15: ss_ext_sales_price = (java.lang.Float)value$; break;
    case 16: ss_ext_wholesale_cost = (java.lang.Float)value$; break;
    case 17: ss_ext_list_price = (java.lang.Float)value$; break;
    case 18: ss_ext_tax = (java.lang.Float)value$; break;
    case 19: ss_coupon_amt = (java.lang.Float)value$; break;
    case 20: ss_net_paid = (java.lang.Float)value$; break;
    case 21: ss_net_paid_inc_tax = (java.lang.Float)value$; break;
    case 22: ss_net_profit = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ss_sold_date_sk' field.
   */
  public java.lang.Integer getSsSoldDateSk() {
    return ss_sold_date_sk;
  }

  /**
   * Sets the value of the 'ss_sold_date_sk' field.
   * @param value the value to set.
   */
  public void setSsSoldDateSk(java.lang.Integer value) {
    this.ss_sold_date_sk = value;
  }

  /**
   * Gets the value of the 'ss_sold_time_sk' field.
   */
  public java.lang.Integer getSsSoldTimeSk() {
    return ss_sold_time_sk;
  }

  /**
   * Sets the value of the 'ss_sold_time_sk' field.
   * @param value the value to set.
   */
  public void setSsSoldTimeSk(java.lang.Integer value) {
    this.ss_sold_time_sk = value;
  }

  /**
   * Gets the value of the 'ss_item_sk' field.
   */
  public java.lang.Integer getSsItemSk() {
    return ss_item_sk;
  }

  /**
   * Sets the value of the 'ss_item_sk' field.
   * @param value the value to set.
   */
  public void setSsItemSk(java.lang.Integer value) {
    this.ss_item_sk = value;
  }

  /**
   * Gets the value of the 'ss_customer_sk' field.
   */
  public java.lang.Integer getSsCustomerSk() {
    return ss_customer_sk;
  }

  /**
   * Sets the value of the 'ss_customer_sk' field.
   * @param value the value to set.
   */
  public void setSsCustomerSk(java.lang.Integer value) {
    this.ss_customer_sk = value;
  }

  /**
   * Gets the value of the 'ss_cdemo_sk' field.
   */
  public java.lang.Integer getSsCdemoSk() {
    return ss_cdemo_sk;
  }

  /**
   * Sets the value of the 'ss_cdemo_sk' field.
   * @param value the value to set.
   */
  public void setSsCdemoSk(java.lang.Integer value) {
    this.ss_cdemo_sk = value;
  }

  /**
   * Gets the value of the 'ss_hdemo_sk' field.
   */
  public java.lang.Integer getSsHdemoSk() {
    return ss_hdemo_sk;
  }

  /**
   * Sets the value of the 'ss_hdemo_sk' field.
   * @param value the value to set.
   */
  public void setSsHdemoSk(java.lang.Integer value) {
    this.ss_hdemo_sk = value;
  }

  /**
   * Gets the value of the 'ss_addr_sk' field.
   */
  public java.lang.Integer getSsAddrSk() {
    return ss_addr_sk;
  }

  /**
   * Sets the value of the 'ss_addr_sk' field.
   * @param value the value to set.
   */
  public void setSsAddrSk(java.lang.Integer value) {
    this.ss_addr_sk = value;
  }

  /**
   * Gets the value of the 'ss_store_sk' field.
   */
  public java.lang.Integer getSsStoreSk() {
    return ss_store_sk;
  }

  /**
   * Sets the value of the 'ss_store_sk' field.
   * @param value the value to set.
   */
  public void setSsStoreSk(java.lang.Integer value) {
    this.ss_store_sk = value;
  }

  /**
   * Gets the value of the 'ss_promo_sk' field.
   */
  public java.lang.Integer getSsPromoSk() {
    return ss_promo_sk;
  }

  /**
   * Sets the value of the 'ss_promo_sk' field.
   * @param value the value to set.
   */
  public void setSsPromoSk(java.lang.Integer value) {
    this.ss_promo_sk = value;
  }

  /**
   * Gets the value of the 'ss_ticket_number' field.
   */
  public java.lang.Integer getSsTicketNumber() {
    return ss_ticket_number;
  }

  /**
   * Sets the value of the 'ss_ticket_number' field.
   * @param value the value to set.
   */
  public void setSsTicketNumber(java.lang.Integer value) {
    this.ss_ticket_number = value;
  }

  /**
   * Gets the value of the 'ss_quantity' field.
   */
  public java.lang.Integer getSsQuantity() {
    return ss_quantity;
  }

  /**
   * Sets the value of the 'ss_quantity' field.
   * @param value the value to set.
   */
  public void setSsQuantity(java.lang.Integer value) {
    this.ss_quantity = value;
  }

  /**
   * Gets the value of the 'ss_wholesale_cost' field.
   */
  public java.lang.Float getSsWholesaleCost() {
    return ss_wholesale_cost;
  }

  /**
   * Sets the value of the 'ss_wholesale_cost' field.
   * @param value the value to set.
   */
  public void setSsWholesaleCost(java.lang.Float value) {
    this.ss_wholesale_cost = value;
  }

  /**
   * Gets the value of the 'ss_list_price' field.
   */
  public java.lang.Float getSsListPrice() {
    return ss_list_price;
  }

  /**
   * Sets the value of the 'ss_list_price' field.
   * @param value the value to set.
   */
  public void setSsListPrice(java.lang.Float value) {
    this.ss_list_price = value;
  }

  /**
   * Gets the value of the 'ss_sales_price' field.
   */
  public java.lang.Float getSsSalesPrice() {
    return ss_sales_price;
  }

  /**
   * Sets the value of the 'ss_sales_price' field.
   * @param value the value to set.
   */
  public void setSsSalesPrice(java.lang.Float value) {
    this.ss_sales_price = value;
  }

  /**
   * Gets the value of the 'ss_ext_discount_amt' field.
   */
  public java.lang.Float getSsExtDiscountAmt() {
    return ss_ext_discount_amt;
  }

  /**
   * Sets the value of the 'ss_ext_discount_amt' field.
   * @param value the value to set.
   */
  public void setSsExtDiscountAmt(java.lang.Float value) {
    this.ss_ext_discount_amt = value;
  }

  /**
   * Gets the value of the 'ss_ext_sales_price' field.
   */
  public java.lang.Float getSsExtSalesPrice() {
    return ss_ext_sales_price;
  }

  /**
   * Sets the value of the 'ss_ext_sales_price' field.
   * @param value the value to set.
   */
  public void setSsExtSalesPrice(java.lang.Float value) {
    this.ss_ext_sales_price = value;
  }

  /**
   * Gets the value of the 'ss_ext_wholesale_cost' field.
   */
  public java.lang.Float getSsExtWholesaleCost() {
    return ss_ext_wholesale_cost;
  }

  /**
   * Sets the value of the 'ss_ext_wholesale_cost' field.
   * @param value the value to set.
   */
  public void setSsExtWholesaleCost(java.lang.Float value) {
    this.ss_ext_wholesale_cost = value;
  }

  /**
   * Gets the value of the 'ss_ext_list_price' field.
   */
  public java.lang.Float getSsExtListPrice() {
    return ss_ext_list_price;
  }

  /**
   * Sets the value of the 'ss_ext_list_price' field.
   * @param value the value to set.
   */
  public void setSsExtListPrice(java.lang.Float value) {
    this.ss_ext_list_price = value;
  }

  /**
   * Gets the value of the 'ss_ext_tax' field.
   */
  public java.lang.Float getSsExtTax() {
    return ss_ext_tax;
  }

  /**
   * Sets the value of the 'ss_ext_tax' field.
   * @param value the value to set.
   */
  public void setSsExtTax(java.lang.Float value) {
    this.ss_ext_tax = value;
  }

  /**
   * Gets the value of the 'ss_coupon_amt' field.
   */
  public java.lang.Float getSsCouponAmt() {
    return ss_coupon_amt;
  }

  /**
   * Sets the value of the 'ss_coupon_amt' field.
   * @param value the value to set.
   */
  public void setSsCouponAmt(java.lang.Float value) {
    this.ss_coupon_amt = value;
  }

  /**
   * Gets the value of the 'ss_net_paid' field.
   */
  public java.lang.Float getSsNetPaid() {
    return ss_net_paid;
  }

  /**
   * Sets the value of the 'ss_net_paid' field.
   * @param value the value to set.
   */
  public void setSsNetPaid(java.lang.Float value) {
    this.ss_net_paid = value;
  }

  /**
   * Gets the value of the 'ss_net_paid_inc_tax' field.
   */
  public java.lang.Float getSsNetPaidIncTax() {
    return ss_net_paid_inc_tax;
  }

  /**
   * Sets the value of the 'ss_net_paid_inc_tax' field.
   * @param value the value to set.
   */
  public void setSsNetPaidIncTax(java.lang.Float value) {
    this.ss_net_paid_inc_tax = value;
  }

  /**
   * Gets the value of the 'ss_net_profit' field.
   */
  public java.lang.Float getSsNetProfit() {
    return ss_net_profit;
  }

  /**
   * Sets the value of the 'ss_net_profit' field.
   * @param value the value to set.
   */
  public void setSsNetProfit(java.lang.Float value) {
    this.ss_net_profit = value;
  }

  /** Creates a new Store_Sales RecordBuilder */
  public static bigframe.avro.Store_Sales.Builder newBuilder() {
    return new bigframe.avro.Store_Sales.Builder();
  }
  
  /** Creates a new Store_Sales RecordBuilder by copying an existing Builder */
  public static bigframe.avro.Store_Sales.Builder newBuilder(bigframe.avro.Store_Sales.Builder other) {
    return new bigframe.avro.Store_Sales.Builder(other);
  }
  
  /** Creates a new Store_Sales RecordBuilder by copying an existing Store_Sales instance */
  public static bigframe.avro.Store_Sales.Builder newBuilder(bigframe.avro.Store_Sales other) {
    return new bigframe.avro.Store_Sales.Builder(other);
  }
  
  /**
   * RecordBuilder for Store_Sales instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Store_Sales>
    implements org.apache.avro.data.RecordBuilder<Store_Sales> {

    private int ss_sold_date_sk;
    private int ss_sold_time_sk;
    private int ss_item_sk;
    private int ss_customer_sk;
    private int ss_cdemo_sk;
    private int ss_hdemo_sk;
    private int ss_addr_sk;
    private int ss_store_sk;
    private int ss_promo_sk;
    private int ss_ticket_number;
    private int ss_quantity;
    private float ss_wholesale_cost;
    private float ss_list_price;
    private float ss_sales_price;
    private float ss_ext_discount_amt;
    private float ss_ext_sales_price;
    private float ss_ext_wholesale_cost;
    private float ss_ext_list_price;
    private float ss_ext_tax;
    private float ss_coupon_amt;
    private float ss_net_paid;
    private float ss_net_paid_inc_tax;
    private float ss_net_profit;

    /** Creates a new Builder */
    private Builder() {
      super(bigframe.avro.Store_Sales.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(bigframe.avro.Store_Sales.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Store_Sales instance */
    private Builder(bigframe.avro.Store_Sales other) {
            super(bigframe.avro.Store_Sales.SCHEMA$);
      if (isValidValue(fields()[0], other.ss_sold_date_sk)) {
        this.ss_sold_date_sk = data().deepCopy(fields()[0].schema(), other.ss_sold_date_sk);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ss_sold_time_sk)) {
        this.ss_sold_time_sk = data().deepCopy(fields()[1].schema(), other.ss_sold_time_sk);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ss_item_sk)) {
        this.ss_item_sk = data().deepCopy(fields()[2].schema(), other.ss_item_sk);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ss_customer_sk)) {
        this.ss_customer_sk = data().deepCopy(fields()[3].schema(), other.ss_customer_sk);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ss_cdemo_sk)) {
        this.ss_cdemo_sk = data().deepCopy(fields()[4].schema(), other.ss_cdemo_sk);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ss_hdemo_sk)) {
        this.ss_hdemo_sk = data().deepCopy(fields()[5].schema(), other.ss_hdemo_sk);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ss_addr_sk)) {
        this.ss_addr_sk = data().deepCopy(fields()[6].schema(), other.ss_addr_sk);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ss_store_sk)) {
        this.ss_store_sk = data().deepCopy(fields()[7].schema(), other.ss_store_sk);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ss_promo_sk)) {
        this.ss_promo_sk = data().deepCopy(fields()[8].schema(), other.ss_promo_sk);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ss_ticket_number)) {
        this.ss_ticket_number = data().deepCopy(fields()[9].schema(), other.ss_ticket_number);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ss_quantity)) {
        this.ss_quantity = data().deepCopy(fields()[10].schema(), other.ss_quantity);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ss_wholesale_cost)) {
        this.ss_wholesale_cost = data().deepCopy(fields()[11].schema(), other.ss_wholesale_cost);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ss_list_price)) {
        this.ss_list_price = data().deepCopy(fields()[12].schema(), other.ss_list_price);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ss_sales_price)) {
        this.ss_sales_price = data().deepCopy(fields()[13].schema(), other.ss_sales_price);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.ss_ext_discount_amt)) {
        this.ss_ext_discount_amt = data().deepCopy(fields()[14].schema(), other.ss_ext_discount_amt);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.ss_ext_sales_price)) {
        this.ss_ext_sales_price = data().deepCopy(fields()[15].schema(), other.ss_ext_sales_price);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.ss_ext_wholesale_cost)) {
        this.ss_ext_wholesale_cost = data().deepCopy(fields()[16].schema(), other.ss_ext_wholesale_cost);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.ss_ext_list_price)) {
        this.ss_ext_list_price = data().deepCopy(fields()[17].schema(), other.ss_ext_list_price);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.ss_ext_tax)) {
        this.ss_ext_tax = data().deepCopy(fields()[18].schema(), other.ss_ext_tax);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.ss_coupon_amt)) {
        this.ss_coupon_amt = data().deepCopy(fields()[19].schema(), other.ss_coupon_amt);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.ss_net_paid)) {
        this.ss_net_paid = data().deepCopy(fields()[20].schema(), other.ss_net_paid);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.ss_net_paid_inc_tax)) {
        this.ss_net_paid_inc_tax = data().deepCopy(fields()[21].schema(), other.ss_net_paid_inc_tax);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.ss_net_profit)) {
        this.ss_net_profit = data().deepCopy(fields()[22].schema(), other.ss_net_profit);
        fieldSetFlags()[22] = true;
      }
    }

    /** Gets the value of the 'ss_sold_date_sk' field */
    public java.lang.Integer getSsSoldDateSk() {
      return ss_sold_date_sk;
    }
    
    /** Sets the value of the 'ss_sold_date_sk' field */
    public bigframe.avro.Store_Sales.Builder setSsSoldDateSk(int value) {
      validate(fields()[0], value);
      this.ss_sold_date_sk = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_sold_date_sk' field has been set */
    public boolean hasSsSoldDateSk() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'ss_sold_date_sk' field */
    public bigframe.avro.Store_Sales.Builder clearSsSoldDateSk() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'ss_sold_time_sk' field */
    public java.lang.Integer getSsSoldTimeSk() {
      return ss_sold_time_sk;
    }
    
    /** Sets the value of the 'ss_sold_time_sk' field */
    public bigframe.avro.Store_Sales.Builder setSsSoldTimeSk(int value) {
      validate(fields()[1], value);
      this.ss_sold_time_sk = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_sold_time_sk' field has been set */
    public boolean hasSsSoldTimeSk() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'ss_sold_time_sk' field */
    public bigframe.avro.Store_Sales.Builder clearSsSoldTimeSk() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'ss_item_sk' field */
    public java.lang.Integer getSsItemSk() {
      return ss_item_sk;
    }
    
    /** Sets the value of the 'ss_item_sk' field */
    public bigframe.avro.Store_Sales.Builder setSsItemSk(int value) {
      validate(fields()[2], value);
      this.ss_item_sk = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_item_sk' field has been set */
    public boolean hasSsItemSk() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'ss_item_sk' field */
    public bigframe.avro.Store_Sales.Builder clearSsItemSk() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ss_customer_sk' field */
    public java.lang.Integer getSsCustomerSk() {
      return ss_customer_sk;
    }
    
    /** Sets the value of the 'ss_customer_sk' field */
    public bigframe.avro.Store_Sales.Builder setSsCustomerSk(int value) {
      validate(fields()[3], value);
      this.ss_customer_sk = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_customer_sk' field has been set */
    public boolean hasSsCustomerSk() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ss_customer_sk' field */
    public bigframe.avro.Store_Sales.Builder clearSsCustomerSk() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'ss_cdemo_sk' field */
    public java.lang.Integer getSsCdemoSk() {
      return ss_cdemo_sk;
    }
    
    /** Sets the value of the 'ss_cdemo_sk' field */
    public bigframe.avro.Store_Sales.Builder setSsCdemoSk(int value) {
      validate(fields()[4], value);
      this.ss_cdemo_sk = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_cdemo_sk' field has been set */
    public boolean hasSsCdemoSk() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'ss_cdemo_sk' field */
    public bigframe.avro.Store_Sales.Builder clearSsCdemoSk() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'ss_hdemo_sk' field */
    public java.lang.Integer getSsHdemoSk() {
      return ss_hdemo_sk;
    }
    
    /** Sets the value of the 'ss_hdemo_sk' field */
    public bigframe.avro.Store_Sales.Builder setSsHdemoSk(int value) {
      validate(fields()[5], value);
      this.ss_hdemo_sk = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_hdemo_sk' field has been set */
    public boolean hasSsHdemoSk() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'ss_hdemo_sk' field */
    public bigframe.avro.Store_Sales.Builder clearSsHdemoSk() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'ss_addr_sk' field */
    public java.lang.Integer getSsAddrSk() {
      return ss_addr_sk;
    }
    
    /** Sets the value of the 'ss_addr_sk' field */
    public bigframe.avro.Store_Sales.Builder setSsAddrSk(int value) {
      validate(fields()[6], value);
      this.ss_addr_sk = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_addr_sk' field has been set */
    public boolean hasSsAddrSk() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'ss_addr_sk' field */
    public bigframe.avro.Store_Sales.Builder clearSsAddrSk() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'ss_store_sk' field */
    public java.lang.Integer getSsStoreSk() {
      return ss_store_sk;
    }
    
    /** Sets the value of the 'ss_store_sk' field */
    public bigframe.avro.Store_Sales.Builder setSsStoreSk(int value) {
      validate(fields()[7], value);
      this.ss_store_sk = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_store_sk' field has been set */
    public boolean hasSsStoreSk() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'ss_store_sk' field */
    public bigframe.avro.Store_Sales.Builder clearSsStoreSk() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'ss_promo_sk' field */
    public java.lang.Integer getSsPromoSk() {
      return ss_promo_sk;
    }
    
    /** Sets the value of the 'ss_promo_sk' field */
    public bigframe.avro.Store_Sales.Builder setSsPromoSk(int value) {
      validate(fields()[8], value);
      this.ss_promo_sk = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_promo_sk' field has been set */
    public boolean hasSsPromoSk() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'ss_promo_sk' field */
    public bigframe.avro.Store_Sales.Builder clearSsPromoSk() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'ss_ticket_number' field */
    public java.lang.Integer getSsTicketNumber() {
      return ss_ticket_number;
    }
    
    /** Sets the value of the 'ss_ticket_number' field */
    public bigframe.avro.Store_Sales.Builder setSsTicketNumber(int value) {
      validate(fields()[9], value);
      this.ss_ticket_number = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_ticket_number' field has been set */
    public boolean hasSsTicketNumber() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'ss_ticket_number' field */
    public bigframe.avro.Store_Sales.Builder clearSsTicketNumber() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'ss_quantity' field */
    public java.lang.Integer getSsQuantity() {
      return ss_quantity;
    }
    
    /** Sets the value of the 'ss_quantity' field */
    public bigframe.avro.Store_Sales.Builder setSsQuantity(int value) {
      validate(fields()[10], value);
      this.ss_quantity = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_quantity' field has been set */
    public boolean hasSsQuantity() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'ss_quantity' field */
    public bigframe.avro.Store_Sales.Builder clearSsQuantity() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'ss_wholesale_cost' field */
    public java.lang.Float getSsWholesaleCost() {
      return ss_wholesale_cost;
    }
    
    /** Sets the value of the 'ss_wholesale_cost' field */
    public bigframe.avro.Store_Sales.Builder setSsWholesaleCost(float value) {
      validate(fields()[11], value);
      this.ss_wholesale_cost = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_wholesale_cost' field has been set */
    public boolean hasSsWholesaleCost() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'ss_wholesale_cost' field */
    public bigframe.avro.Store_Sales.Builder clearSsWholesaleCost() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'ss_list_price' field */
    public java.lang.Float getSsListPrice() {
      return ss_list_price;
    }
    
    /** Sets the value of the 'ss_list_price' field */
    public bigframe.avro.Store_Sales.Builder setSsListPrice(float value) {
      validate(fields()[12], value);
      this.ss_list_price = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_list_price' field has been set */
    public boolean hasSsListPrice() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'ss_list_price' field */
    public bigframe.avro.Store_Sales.Builder clearSsListPrice() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'ss_sales_price' field */
    public java.lang.Float getSsSalesPrice() {
      return ss_sales_price;
    }
    
    /** Sets the value of the 'ss_sales_price' field */
    public bigframe.avro.Store_Sales.Builder setSsSalesPrice(float value) {
      validate(fields()[13], value);
      this.ss_sales_price = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_sales_price' field has been set */
    public boolean hasSsSalesPrice() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'ss_sales_price' field */
    public bigframe.avro.Store_Sales.Builder clearSsSalesPrice() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'ss_ext_discount_amt' field */
    public java.lang.Float getSsExtDiscountAmt() {
      return ss_ext_discount_amt;
    }
    
    /** Sets the value of the 'ss_ext_discount_amt' field */
    public bigframe.avro.Store_Sales.Builder setSsExtDiscountAmt(float value) {
      validate(fields()[14], value);
      this.ss_ext_discount_amt = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_ext_discount_amt' field has been set */
    public boolean hasSsExtDiscountAmt() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'ss_ext_discount_amt' field */
    public bigframe.avro.Store_Sales.Builder clearSsExtDiscountAmt() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'ss_ext_sales_price' field */
    public java.lang.Float getSsExtSalesPrice() {
      return ss_ext_sales_price;
    }
    
    /** Sets the value of the 'ss_ext_sales_price' field */
    public bigframe.avro.Store_Sales.Builder setSsExtSalesPrice(float value) {
      validate(fields()[15], value);
      this.ss_ext_sales_price = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_ext_sales_price' field has been set */
    public boolean hasSsExtSalesPrice() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'ss_ext_sales_price' field */
    public bigframe.avro.Store_Sales.Builder clearSsExtSalesPrice() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'ss_ext_wholesale_cost' field */
    public java.lang.Float getSsExtWholesaleCost() {
      return ss_ext_wholesale_cost;
    }
    
    /** Sets the value of the 'ss_ext_wholesale_cost' field */
    public bigframe.avro.Store_Sales.Builder setSsExtWholesaleCost(float value) {
      validate(fields()[16], value);
      this.ss_ext_wholesale_cost = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_ext_wholesale_cost' field has been set */
    public boolean hasSsExtWholesaleCost() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'ss_ext_wholesale_cost' field */
    public bigframe.avro.Store_Sales.Builder clearSsExtWholesaleCost() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'ss_ext_list_price' field */
    public java.lang.Float getSsExtListPrice() {
      return ss_ext_list_price;
    }
    
    /** Sets the value of the 'ss_ext_list_price' field */
    public bigframe.avro.Store_Sales.Builder setSsExtListPrice(float value) {
      validate(fields()[17], value);
      this.ss_ext_list_price = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_ext_list_price' field has been set */
    public boolean hasSsExtListPrice() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'ss_ext_list_price' field */
    public bigframe.avro.Store_Sales.Builder clearSsExtListPrice() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'ss_ext_tax' field */
    public java.lang.Float getSsExtTax() {
      return ss_ext_tax;
    }
    
    /** Sets the value of the 'ss_ext_tax' field */
    public bigframe.avro.Store_Sales.Builder setSsExtTax(float value) {
      validate(fields()[18], value);
      this.ss_ext_tax = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_ext_tax' field has been set */
    public boolean hasSsExtTax() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'ss_ext_tax' field */
    public bigframe.avro.Store_Sales.Builder clearSsExtTax() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'ss_coupon_amt' field */
    public java.lang.Float getSsCouponAmt() {
      return ss_coupon_amt;
    }
    
    /** Sets the value of the 'ss_coupon_amt' field */
    public bigframe.avro.Store_Sales.Builder setSsCouponAmt(float value) {
      validate(fields()[19], value);
      this.ss_coupon_amt = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_coupon_amt' field has been set */
    public boolean hasSsCouponAmt() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'ss_coupon_amt' field */
    public bigframe.avro.Store_Sales.Builder clearSsCouponAmt() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'ss_net_paid' field */
    public java.lang.Float getSsNetPaid() {
      return ss_net_paid;
    }
    
    /** Sets the value of the 'ss_net_paid' field */
    public bigframe.avro.Store_Sales.Builder setSsNetPaid(float value) {
      validate(fields()[20], value);
      this.ss_net_paid = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_net_paid' field has been set */
    public boolean hasSsNetPaid() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'ss_net_paid' field */
    public bigframe.avro.Store_Sales.Builder clearSsNetPaid() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'ss_net_paid_inc_tax' field */
    public java.lang.Float getSsNetPaidIncTax() {
      return ss_net_paid_inc_tax;
    }
    
    /** Sets the value of the 'ss_net_paid_inc_tax' field */
    public bigframe.avro.Store_Sales.Builder setSsNetPaidIncTax(float value) {
      validate(fields()[21], value);
      this.ss_net_paid_inc_tax = value;
      fieldSetFlags()[21] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_net_paid_inc_tax' field has been set */
    public boolean hasSsNetPaidIncTax() {
      return fieldSetFlags()[21];
    }
    
    /** Clears the value of the 'ss_net_paid_inc_tax' field */
    public bigframe.avro.Store_Sales.Builder clearSsNetPaidIncTax() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /** Gets the value of the 'ss_net_profit' field */
    public java.lang.Float getSsNetProfit() {
      return ss_net_profit;
    }
    
    /** Sets the value of the 'ss_net_profit' field */
    public bigframe.avro.Store_Sales.Builder setSsNetProfit(float value) {
      validate(fields()[22], value);
      this.ss_net_profit = value;
      fieldSetFlags()[22] = true;
      return this; 
    }
    
    /** Checks whether the 'ss_net_profit' field has been set */
    public boolean hasSsNetProfit() {
      return fieldSetFlags()[22];
    }
    
    /** Clears the value of the 'ss_net_profit' field */
    public bigframe.avro.Store_Sales.Builder clearSsNetProfit() {
      fieldSetFlags()[22] = false;
      return this;
    }

    @Override
    public Store_Sales build() {
      try {
        Store_Sales record = new Store_Sales();
        record.ss_sold_date_sk = fieldSetFlags()[0] ? this.ss_sold_date_sk : (java.lang.Integer) defaultValue(fields()[0]);
        record.ss_sold_time_sk = fieldSetFlags()[1] ? this.ss_sold_time_sk : (java.lang.Integer) defaultValue(fields()[1]);
        record.ss_item_sk = fieldSetFlags()[2] ? this.ss_item_sk : (java.lang.Integer) defaultValue(fields()[2]);
        record.ss_customer_sk = fieldSetFlags()[3] ? this.ss_customer_sk : (java.lang.Integer) defaultValue(fields()[3]);
        record.ss_cdemo_sk = fieldSetFlags()[4] ? this.ss_cdemo_sk : (java.lang.Integer) defaultValue(fields()[4]);
        record.ss_hdemo_sk = fieldSetFlags()[5] ? this.ss_hdemo_sk : (java.lang.Integer) defaultValue(fields()[5]);
        record.ss_addr_sk = fieldSetFlags()[6] ? this.ss_addr_sk : (java.lang.Integer) defaultValue(fields()[6]);
        record.ss_store_sk = fieldSetFlags()[7] ? this.ss_store_sk : (java.lang.Integer) defaultValue(fields()[7]);
        record.ss_promo_sk = fieldSetFlags()[8] ? this.ss_promo_sk : (java.lang.Integer) defaultValue(fields()[8]);
        record.ss_ticket_number = fieldSetFlags()[9] ? this.ss_ticket_number : (java.lang.Integer) defaultValue(fields()[9]);
        record.ss_quantity = fieldSetFlags()[10] ? this.ss_quantity : (java.lang.Integer) defaultValue(fields()[10]);
        record.ss_wholesale_cost = fieldSetFlags()[11] ? this.ss_wholesale_cost : (java.lang.Float) defaultValue(fields()[11]);
        record.ss_list_price = fieldSetFlags()[12] ? this.ss_list_price : (java.lang.Float) defaultValue(fields()[12]);
        record.ss_sales_price = fieldSetFlags()[13] ? this.ss_sales_price : (java.lang.Float) defaultValue(fields()[13]);
        record.ss_ext_discount_amt = fieldSetFlags()[14] ? this.ss_ext_discount_amt : (java.lang.Float) defaultValue(fields()[14]);
        record.ss_ext_sales_price = fieldSetFlags()[15] ? this.ss_ext_sales_price : (java.lang.Float) defaultValue(fields()[15]);
        record.ss_ext_wholesale_cost = fieldSetFlags()[16] ? this.ss_ext_wholesale_cost : (java.lang.Float) defaultValue(fields()[16]);
        record.ss_ext_list_price = fieldSetFlags()[17] ? this.ss_ext_list_price : (java.lang.Float) defaultValue(fields()[17]);
        record.ss_ext_tax = fieldSetFlags()[18] ? this.ss_ext_tax : (java.lang.Float) defaultValue(fields()[18]);
        record.ss_coupon_amt = fieldSetFlags()[19] ? this.ss_coupon_amt : (java.lang.Float) defaultValue(fields()[19]);
        record.ss_net_paid = fieldSetFlags()[20] ? this.ss_net_paid : (java.lang.Float) defaultValue(fields()[20]);
        record.ss_net_paid_inc_tax = fieldSetFlags()[21] ? this.ss_net_paid_inc_tax : (java.lang.Float) defaultValue(fields()[21]);
        record.ss_net_profit = fieldSetFlags()[22] ? this.ss_net_profit : (java.lang.Float) defaultValue(fields()[22]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
