/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Twitter_Graph extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Twitter_Graph\",\"namespace\":\"bigframe.avro\",\"fields\":[{\"name\":\"friend_id\",\"type\":\"int\"},{\"name\":\"follower_id\",\"type\":\"int\"}]}");
  @Deprecated public int friend_id;
  @Deprecated public int follower_id;

  /**
   * Default constructor.
   */
  public Twitter_Graph() {}

  /**
   * All-args constructor.
   */
  public Twitter_Graph(java.lang.Integer friend_id, java.lang.Integer follower_id) {
    this.friend_id = friend_id;
    this.follower_id = follower_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return friend_id;
    case 1: return follower_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: friend_id = (java.lang.Integer)value$; break;
    case 1: follower_id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'friend_id' field.
   */
  public java.lang.Integer getFriendId() {
    return friend_id;
  }

  /**
   * Sets the value of the 'friend_id' field.
   * @param value the value to set.
   */
  public void setFriendId(java.lang.Integer value) {
    this.friend_id = value;
  }

  /**
   * Gets the value of the 'follower_id' field.
   */
  public java.lang.Integer getFollowerId() {
    return follower_id;
  }

  /**
   * Sets the value of the 'follower_id' field.
   * @param value the value to set.
   */
  public void setFollowerId(java.lang.Integer value) {
    this.follower_id = value;
  }

  /** Creates a new Twitter_Graph RecordBuilder */
  public static bigframe.avro.Twitter_Graph.Builder newBuilder() {
    return new bigframe.avro.Twitter_Graph.Builder();
  }
  
  /** Creates a new Twitter_Graph RecordBuilder by copying an existing Builder */
  public static bigframe.avro.Twitter_Graph.Builder newBuilder(bigframe.avro.Twitter_Graph.Builder other) {
    return new bigframe.avro.Twitter_Graph.Builder(other);
  }
  
  /** Creates a new Twitter_Graph RecordBuilder by copying an existing Twitter_Graph instance */
  public static bigframe.avro.Twitter_Graph.Builder newBuilder(bigframe.avro.Twitter_Graph other) {
    return new bigframe.avro.Twitter_Graph.Builder(other);
  }
  
  /**
   * RecordBuilder for Twitter_Graph instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Twitter_Graph>
    implements org.apache.avro.data.RecordBuilder<Twitter_Graph> {

    private int friend_id;
    private int follower_id;

    /** Creates a new Builder */
    private Builder() {
      super(bigframe.avro.Twitter_Graph.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(bigframe.avro.Twitter_Graph.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Twitter_Graph instance */
    private Builder(bigframe.avro.Twitter_Graph other) {
            super(bigframe.avro.Twitter_Graph.SCHEMA$);
      if (isValidValue(fields()[0], other.friend_id)) {
        this.friend_id = data().deepCopy(fields()[0].schema(), other.friend_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.follower_id)) {
        this.follower_id = data().deepCopy(fields()[1].schema(), other.follower_id);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'friend_id' field */
    public java.lang.Integer getFriendId() {
      return friend_id;
    }
    
    /** Sets the value of the 'friend_id' field */
    public bigframe.avro.Twitter_Graph.Builder setFriendId(int value) {
      validate(fields()[0], value);
      this.friend_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'friend_id' field has been set */
    public boolean hasFriendId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'friend_id' field */
    public bigframe.avro.Twitter_Graph.Builder clearFriendId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'follower_id' field */
    public java.lang.Integer getFollowerId() {
      return follower_id;
    }
    
    /** Sets the value of the 'follower_id' field */
    public bigframe.avro.Twitter_Graph.Builder setFollowerId(int value) {
      validate(fields()[1], value);
      this.follower_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'follower_id' field has been set */
    public boolean hasFollowerId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'follower_id' field */
    public bigframe.avro.Twitter_Graph.Builder clearFollowerId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Twitter_Graph build() {
      try {
        Twitter_Graph record = new Twitter_Graph();
        record.friend_id = fieldSetFlags()[0] ? this.friend_id : (java.lang.Integer) defaultValue(fields()[0]);
        record.follower_id = fieldSetFlags()[1] ? this.follower_id : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
