/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Url extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Url\",\"namespace\":\"bigframe.avro\",\"fields\":[{\"name\":\"expanded_url\",\"type\":[\"null\",\"string\"]},{\"name\":\"indices\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"int\"}]},{\"name\":\"url\",\"type\":[\"null\",\"string\"]}]}");
  @Deprecated public java.lang.CharSequence expanded_url;
  @Deprecated public java.util.List<java.lang.Integer> indices;
  @Deprecated public java.lang.CharSequence url;

  /**
   * Default constructor.
   */
  public Url() {}

  /**
   * All-args constructor.
   */
  public Url(java.lang.CharSequence expanded_url, java.util.List<java.lang.Integer> indices, java.lang.CharSequence url) {
    this.expanded_url = expanded_url;
    this.indices = indices;
    this.url = url;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return expanded_url;
    case 1: return indices;
    case 2: return url;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: expanded_url = (java.lang.CharSequence)value$; break;
    case 1: indices = (java.util.List<java.lang.Integer>)value$; break;
    case 2: url = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'expanded_url' field.
   */
  public java.lang.CharSequence getExpandedUrl() {
    return expanded_url;
  }

  /**
   * Sets the value of the 'expanded_url' field.
   * @param value the value to set.
   */
  public void setExpandedUrl(java.lang.CharSequence value) {
    this.expanded_url = value;
  }

  /**
   * Gets the value of the 'indices' field.
   */
  public java.util.List<java.lang.Integer> getIndices() {
    return indices;
  }

  /**
   * Sets the value of the 'indices' field.
   * @param value the value to set.
   */
  public void setIndices(java.util.List<java.lang.Integer> value) {
    this.indices = value;
  }

  /**
   * Gets the value of the 'url' field.
   */
  public java.lang.CharSequence getUrl() {
    return url;
  }

  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.CharSequence value) {
    this.url = value;
  }

  /** Creates a new Url RecordBuilder */
  public static bigframe.avro.Url.Builder newBuilder() {
    return new bigframe.avro.Url.Builder();
  }
  
  /** Creates a new Url RecordBuilder by copying an existing Builder */
  public static bigframe.avro.Url.Builder newBuilder(bigframe.avro.Url.Builder other) {
    return new bigframe.avro.Url.Builder(other);
  }
  
  /** Creates a new Url RecordBuilder by copying an existing Url instance */
  public static bigframe.avro.Url.Builder newBuilder(bigframe.avro.Url other) {
    return new bigframe.avro.Url.Builder(other);
  }
  
  /**
   * RecordBuilder for Url instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Url>
    implements org.apache.avro.data.RecordBuilder<Url> {

    private java.lang.CharSequence expanded_url;
    private java.util.List<java.lang.Integer> indices;
    private java.lang.CharSequence url;

    /** Creates a new Builder */
    private Builder() {
      super(bigframe.avro.Url.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(bigframe.avro.Url.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Url instance */
    private Builder(bigframe.avro.Url other) {
            super(bigframe.avro.Url.SCHEMA$);
      if (isValidValue(fields()[0], other.expanded_url)) {
        this.expanded_url = data().deepCopy(fields()[0].schema(), other.expanded_url);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.indices)) {
        this.indices = data().deepCopy(fields()[1].schema(), other.indices);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.url)) {
        this.url = data().deepCopy(fields()[2].schema(), other.url);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'expanded_url' field */
    public java.lang.CharSequence getExpandedUrl() {
      return expanded_url;
    }
    
    /** Sets the value of the 'expanded_url' field */
    public bigframe.avro.Url.Builder setExpandedUrl(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.expanded_url = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'expanded_url' field has been set */
    public boolean hasExpandedUrl() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'expanded_url' field */
    public bigframe.avro.Url.Builder clearExpandedUrl() {
      expanded_url = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'indices' field */
    public java.util.List<java.lang.Integer> getIndices() {
      return indices;
    }
    
    /** Sets the value of the 'indices' field */
    public bigframe.avro.Url.Builder setIndices(java.util.List<java.lang.Integer> value) {
      validate(fields()[1], value);
      this.indices = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'indices' field has been set */
    public boolean hasIndices() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'indices' field */
    public bigframe.avro.Url.Builder clearIndices() {
      indices = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'url' field */
    public java.lang.CharSequence getUrl() {
      return url;
    }
    
    /** Sets the value of the 'url' field */
    public bigframe.avro.Url.Builder setUrl(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.url = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'url' field has been set */
    public boolean hasUrl() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'url' field */
    public bigframe.avro.Url.Builder clearUrl() {
      url = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Url build() {
      try {
        Url record = new Url();
        record.expanded_url = fieldSetFlags()[0] ? this.expanded_url : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.indices = fieldSetFlags()[1] ? this.indices : (java.util.List<java.lang.Integer>) defaultValue(fields()[1]);
        record.url = fieldSetFlags()[2] ? this.url : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
