/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package bigframe.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Web_Sales extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Web_Sales\",\"namespace\":\"bigframe.avro\",\"fields\":[{\"name\":\"ws_sold_date_sk\",\"type\":\"int\"},{\"name\":\"ws_sold_time_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_date_sk\",\"type\":\"int\"},{\"name\":\"ws_item_sk\",\"type\":\"int\"},{\"name\":\"ws_bill_customer_sk\",\"type\":\"int\"},{\"name\":\"ws_bill_cdemo_sk\",\"type\":\"int\"},{\"name\":\"ws_bill_hdemo_sk\",\"type\":\"int\"},{\"name\":\"ws_bill_addr_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_customer_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_cdemo_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_hdemo_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_addr_sk\",\"type\":\"int\"},{\"name\":\"ws_web_page_sk\",\"type\":\"int\"},{\"name\":\"ws_web_site_sk\",\"type\":\"int\"},{\"name\":\"ws_ship_mode_sk\",\"type\":\"int\"},{\"name\":\"ws_warehouse_sk\",\"type\":\"int\"},{\"name\":\"ws_promo_sk\",\"type\":\"int\"},{\"name\":\"ws_order_number\",\"type\":\"int\"},{\"name\":\"ws_quantity\",\"type\":\"int\"},{\"name\":\"ws_wholesale_cost\",\"type\":\"float\"},{\"name\":\"ws_list_price\",\"type\":\"float\"},{\"name\":\"ws_sales_price\",\"type\":\"float\"},{\"name\":\"ws_ext_discount_amt\",\"type\":\"float\"},{\"name\":\"ws_ext_sales_price\",\"type\":\"float\"},{\"name\":\"ws_ext_wholesale_cost\",\"type\":\"float\"},{\"name\":\"ws_ext_list_price\",\"type\":\"float\"},{\"name\":\"ws_ext_tax\",\"type\":\"float\"},{\"name\":\"ws_coupon_amt\",\"type\":\"float\"},{\"name\":\"ws_ext_ship_cost\",\"type\":\"float\"},{\"name\":\"ws_net_paid\",\"type\":\"float\"},{\"name\":\"ws_net_paid_inc_tax\",\"type\":\"float\"},{\"name\":\"ws_net_paid_inc_ship\",\"type\":\"float\"},{\"name\":\"ws_net_paid_inc_ship_tax\",\"type\":\"float\"},{\"name\":\"ws_net_profit\",\"type\":\"float\"}]}");
  @Deprecated public int ws_sold_date_sk;
  @Deprecated public int ws_sold_time_sk;
  @Deprecated public int ws_ship_date_sk;
  @Deprecated public int ws_item_sk;
  @Deprecated public int ws_bill_customer_sk;
  @Deprecated public int ws_bill_cdemo_sk;
  @Deprecated public int ws_bill_hdemo_sk;
  @Deprecated public int ws_bill_addr_sk;
  @Deprecated public int ws_ship_customer_sk;
  @Deprecated public int ws_ship_cdemo_sk;
  @Deprecated public int ws_ship_hdemo_sk;
  @Deprecated public int ws_ship_addr_sk;
  @Deprecated public int ws_web_page_sk;
  @Deprecated public int ws_web_site_sk;
  @Deprecated public int ws_ship_mode_sk;
  @Deprecated public int ws_warehouse_sk;
  @Deprecated public int ws_promo_sk;
  @Deprecated public int ws_order_number;
  @Deprecated public int ws_quantity;
  @Deprecated public float ws_wholesale_cost;
  @Deprecated public float ws_list_price;
  @Deprecated public float ws_sales_price;
  @Deprecated public float ws_ext_discount_amt;
  @Deprecated public float ws_ext_sales_price;
  @Deprecated public float ws_ext_wholesale_cost;
  @Deprecated public float ws_ext_list_price;
  @Deprecated public float ws_ext_tax;
  @Deprecated public float ws_coupon_amt;
  @Deprecated public float ws_ext_ship_cost;
  @Deprecated public float ws_net_paid;
  @Deprecated public float ws_net_paid_inc_tax;
  @Deprecated public float ws_net_paid_inc_ship;
  @Deprecated public float ws_net_paid_inc_ship_tax;
  @Deprecated public float ws_net_profit;

  /**
   * Default constructor.
   */
  public Web_Sales() {}

  /**
   * All-args constructor.
   */
  public Web_Sales(java.lang.Integer ws_sold_date_sk, java.lang.Integer ws_sold_time_sk, java.lang.Integer ws_ship_date_sk, java.lang.Integer ws_item_sk, java.lang.Integer ws_bill_customer_sk, java.lang.Integer ws_bill_cdemo_sk, java.lang.Integer ws_bill_hdemo_sk, java.lang.Integer ws_bill_addr_sk, java.lang.Integer ws_ship_customer_sk, java.lang.Integer ws_ship_cdemo_sk, java.lang.Integer ws_ship_hdemo_sk, java.lang.Integer ws_ship_addr_sk, java.lang.Integer ws_web_page_sk, java.lang.Integer ws_web_site_sk, java.lang.Integer ws_ship_mode_sk, java.lang.Integer ws_warehouse_sk, java.lang.Integer ws_promo_sk, java.lang.Integer ws_order_number, java.lang.Integer ws_quantity, java.lang.Float ws_wholesale_cost, java.lang.Float ws_list_price, java.lang.Float ws_sales_price, java.lang.Float ws_ext_discount_amt, java.lang.Float ws_ext_sales_price, java.lang.Float ws_ext_wholesale_cost, java.lang.Float ws_ext_list_price, java.lang.Float ws_ext_tax, java.lang.Float ws_coupon_amt, java.lang.Float ws_ext_ship_cost, java.lang.Float ws_net_paid, java.lang.Float ws_net_paid_inc_tax, java.lang.Float ws_net_paid_inc_ship, java.lang.Float ws_net_paid_inc_ship_tax, java.lang.Float ws_net_profit) {
    this.ws_sold_date_sk = ws_sold_date_sk;
    this.ws_sold_time_sk = ws_sold_time_sk;
    this.ws_ship_date_sk = ws_ship_date_sk;
    this.ws_item_sk = ws_item_sk;
    this.ws_bill_customer_sk = ws_bill_customer_sk;
    this.ws_bill_cdemo_sk = ws_bill_cdemo_sk;
    this.ws_bill_hdemo_sk = ws_bill_hdemo_sk;
    this.ws_bill_addr_sk = ws_bill_addr_sk;
    this.ws_ship_customer_sk = ws_ship_customer_sk;
    this.ws_ship_cdemo_sk = ws_ship_cdemo_sk;
    this.ws_ship_hdemo_sk = ws_ship_hdemo_sk;
    this.ws_ship_addr_sk = ws_ship_addr_sk;
    this.ws_web_page_sk = ws_web_page_sk;
    this.ws_web_site_sk = ws_web_site_sk;
    this.ws_ship_mode_sk = ws_ship_mode_sk;
    this.ws_warehouse_sk = ws_warehouse_sk;
    this.ws_promo_sk = ws_promo_sk;
    this.ws_order_number = ws_order_number;
    this.ws_quantity = ws_quantity;
    this.ws_wholesale_cost = ws_wholesale_cost;
    this.ws_list_price = ws_list_price;
    this.ws_sales_price = ws_sales_price;
    this.ws_ext_discount_amt = ws_ext_discount_amt;
    this.ws_ext_sales_price = ws_ext_sales_price;
    this.ws_ext_wholesale_cost = ws_ext_wholesale_cost;
    this.ws_ext_list_price = ws_ext_list_price;
    this.ws_ext_tax = ws_ext_tax;
    this.ws_coupon_amt = ws_coupon_amt;
    this.ws_ext_ship_cost = ws_ext_ship_cost;
    this.ws_net_paid = ws_net_paid;
    this.ws_net_paid_inc_tax = ws_net_paid_inc_tax;
    this.ws_net_paid_inc_ship = ws_net_paid_inc_ship;
    this.ws_net_paid_inc_ship_tax = ws_net_paid_inc_ship_tax;
    this.ws_net_profit = ws_net_profit;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ws_sold_date_sk;
    case 1: return ws_sold_time_sk;
    case 2: return ws_ship_date_sk;
    case 3: return ws_item_sk;
    case 4: return ws_bill_customer_sk;
    case 5: return ws_bill_cdemo_sk;
    case 6: return ws_bill_hdemo_sk;
    case 7: return ws_bill_addr_sk;
    case 8: return ws_ship_customer_sk;
    case 9: return ws_ship_cdemo_sk;
    case 10: return ws_ship_hdemo_sk;
    case 11: return ws_ship_addr_sk;
    case 12: return ws_web_page_sk;
    case 13: return ws_web_site_sk;
    case 14: return ws_ship_mode_sk;
    case 15: return ws_warehouse_sk;
    case 16: return ws_promo_sk;
    case 17: return ws_order_number;
    case 18: return ws_quantity;
    case 19: return ws_wholesale_cost;
    case 20: return ws_list_price;
    case 21: return ws_sales_price;
    case 22: return ws_ext_discount_amt;
    case 23: return ws_ext_sales_price;
    case 24: return ws_ext_wholesale_cost;
    case 25: return ws_ext_list_price;
    case 26: return ws_ext_tax;
    case 27: return ws_coupon_amt;
    case 28: return ws_ext_ship_cost;
    case 29: return ws_net_paid;
    case 30: return ws_net_paid_inc_tax;
    case 31: return ws_net_paid_inc_ship;
    case 32: return ws_net_paid_inc_ship_tax;
    case 33: return ws_net_profit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ws_sold_date_sk = (java.lang.Integer)value$; break;
    case 1: ws_sold_time_sk = (java.lang.Integer)value$; break;
    case 2: ws_ship_date_sk = (java.lang.Integer)value$; break;
    case 3: ws_item_sk = (java.lang.Integer)value$; break;
    case 4: ws_bill_customer_sk = (java.lang.Integer)value$; break;
    case 5: ws_bill_cdemo_sk = (java.lang.Integer)value$; break;
    case 6: ws_bill_hdemo_sk = (java.lang.Integer)value$; break;
    case 7: ws_bill_addr_sk = (java.lang.Integer)value$; break;
    case 8: ws_ship_customer_sk = (java.lang.Integer)value$; break;
    case 9: ws_ship_cdemo_sk = (java.lang.Integer)value$; break;
    case 10: ws_ship_hdemo_sk = (java.lang.Integer)value$; break;
    case 11: ws_ship_addr_sk = (java.lang.Integer)value$; break;
    case 12: ws_web_page_sk = (java.lang.Integer)value$; break;
    case 13: ws_web_site_sk = (java.lang.Integer)value$; break;
    case 14: ws_ship_mode_sk = (java.lang.Integer)value$; break;
    case 15: ws_warehouse_sk = (java.lang.Integer)value$; break;
    case 16: ws_promo_sk = (java.lang.Integer)value$; break;
    case 17: ws_order_number = (java.lang.Integer)value$; break;
    case 18: ws_quantity = (java.lang.Integer)value$; break;
    case 19: ws_wholesale_cost = (java.lang.Float)value$; break;
    case 20: ws_list_price = (java.lang.Float)value$; break;
    case 21: ws_sales_price = (java.lang.Float)value$; break;
    case 22: ws_ext_discount_amt = (java.lang.Float)value$; break;
    case 23: ws_ext_sales_price = (java.lang.Float)value$; break;
    case 24: ws_ext_wholesale_cost = (java.lang.Float)value$; break;
    case 25: ws_ext_list_price = (java.lang.Float)value$; break;
    case 26: ws_ext_tax = (java.lang.Float)value$; break;
    case 27: ws_coupon_amt = (java.lang.Float)value$; break;
    case 28: ws_ext_ship_cost = (java.lang.Float)value$; break;
    case 29: ws_net_paid = (java.lang.Float)value$; break;
    case 30: ws_net_paid_inc_tax = (java.lang.Float)value$; break;
    case 31: ws_net_paid_inc_ship = (java.lang.Float)value$; break;
    case 32: ws_net_paid_inc_ship_tax = (java.lang.Float)value$; break;
    case 33: ws_net_profit = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ws_sold_date_sk' field.
   */
  public java.lang.Integer getWsSoldDateSk() {
    return ws_sold_date_sk;
  }

  /**
   * Sets the value of the 'ws_sold_date_sk' field.
   * @param value the value to set.
   */
  public void setWsSoldDateSk(java.lang.Integer value) {
    this.ws_sold_date_sk = value;
  }

  /**
   * Gets the value of the 'ws_sold_time_sk' field.
   */
  public java.lang.Integer getWsSoldTimeSk() {
    return ws_sold_time_sk;
  }

  /**
   * Sets the value of the 'ws_sold_time_sk' field.
   * @param value the value to set.
   */
  public void setWsSoldTimeSk(java.lang.Integer value) {
    this.ws_sold_time_sk = value;
  }

  /**
   * Gets the value of the 'ws_ship_date_sk' field.
   */
  public java.lang.Integer getWsShipDateSk() {
    return ws_ship_date_sk;
  }

  /**
   * Sets the value of the 'ws_ship_date_sk' field.
   * @param value the value to set.
   */
  public void setWsShipDateSk(java.lang.Integer value) {
    this.ws_ship_date_sk = value;
  }

  /**
   * Gets the value of the 'ws_item_sk' field.
   */
  public java.lang.Integer getWsItemSk() {
    return ws_item_sk;
  }

  /**
   * Sets the value of the 'ws_item_sk' field.
   * @param value the value to set.
   */
  public void setWsItemSk(java.lang.Integer value) {
    this.ws_item_sk = value;
  }

  /**
   * Gets the value of the 'ws_bill_customer_sk' field.
   */
  public java.lang.Integer getWsBillCustomerSk() {
    return ws_bill_customer_sk;
  }

  /**
   * Sets the value of the 'ws_bill_customer_sk' field.
   * @param value the value to set.
   */
  public void setWsBillCustomerSk(java.lang.Integer value) {
    this.ws_bill_customer_sk = value;
  }

  /**
   * Gets the value of the 'ws_bill_cdemo_sk' field.
   */
  public java.lang.Integer getWsBillCdemoSk() {
    return ws_bill_cdemo_sk;
  }

  /**
   * Sets the value of the 'ws_bill_cdemo_sk' field.
   * @param value the value to set.
   */
  public void setWsBillCdemoSk(java.lang.Integer value) {
    this.ws_bill_cdemo_sk = value;
  }

  /**
   * Gets the value of the 'ws_bill_hdemo_sk' field.
   */
  public java.lang.Integer getWsBillHdemoSk() {
    return ws_bill_hdemo_sk;
  }

  /**
   * Sets the value of the 'ws_bill_hdemo_sk' field.
   * @param value the value to set.
   */
  public void setWsBillHdemoSk(java.lang.Integer value) {
    this.ws_bill_hdemo_sk = value;
  }

  /**
   * Gets the value of the 'ws_bill_addr_sk' field.
   */
  public java.lang.Integer getWsBillAddrSk() {
    return ws_bill_addr_sk;
  }

  /**
   * Sets the value of the 'ws_bill_addr_sk' field.
   * @param value the value to set.
   */
  public void setWsBillAddrSk(java.lang.Integer value) {
    this.ws_bill_addr_sk = value;
  }

  /**
   * Gets the value of the 'ws_ship_customer_sk' field.
   */
  public java.lang.Integer getWsShipCustomerSk() {
    return ws_ship_customer_sk;
  }

  /**
   * Sets the value of the 'ws_ship_customer_sk' field.
   * @param value the value to set.
   */
  public void setWsShipCustomerSk(java.lang.Integer value) {
    this.ws_ship_customer_sk = value;
  }

  /**
   * Gets the value of the 'ws_ship_cdemo_sk' field.
   */
  public java.lang.Integer getWsShipCdemoSk() {
    return ws_ship_cdemo_sk;
  }

  /**
   * Sets the value of the 'ws_ship_cdemo_sk' field.
   * @param value the value to set.
   */
  public void setWsShipCdemoSk(java.lang.Integer value) {
    this.ws_ship_cdemo_sk = value;
  }

  /**
   * Gets the value of the 'ws_ship_hdemo_sk' field.
   */
  public java.lang.Integer getWsShipHdemoSk() {
    return ws_ship_hdemo_sk;
  }

  /**
   * Sets the value of the 'ws_ship_hdemo_sk' field.
   * @param value the value to set.
   */
  public void setWsShipHdemoSk(java.lang.Integer value) {
    this.ws_ship_hdemo_sk = value;
  }

  /**
   * Gets the value of the 'ws_ship_addr_sk' field.
   */
  public java.lang.Integer getWsShipAddrSk() {
    return ws_ship_addr_sk;
  }

  /**
   * Sets the value of the 'ws_ship_addr_sk' field.
   * @param value the value to set.
   */
  public void setWsShipAddrSk(java.lang.Integer value) {
    this.ws_ship_addr_sk = value;
  }

  /**
   * Gets the value of the 'ws_web_page_sk' field.
   */
  public java.lang.Integer getWsWebPageSk() {
    return ws_web_page_sk;
  }

  /**
   * Sets the value of the 'ws_web_page_sk' field.
   * @param value the value to set.
   */
  public void setWsWebPageSk(java.lang.Integer value) {
    this.ws_web_page_sk = value;
  }

  /**
   * Gets the value of the 'ws_web_site_sk' field.
   */
  public java.lang.Integer getWsWebSiteSk() {
    return ws_web_site_sk;
  }

  /**
   * Sets the value of the 'ws_web_site_sk' field.
   * @param value the value to set.
   */
  public void setWsWebSiteSk(java.lang.Integer value) {
    this.ws_web_site_sk = value;
  }

  /**
   * Gets the value of the 'ws_ship_mode_sk' field.
   */
  public java.lang.Integer getWsShipModeSk() {
    return ws_ship_mode_sk;
  }

  /**
   * Sets the value of the 'ws_ship_mode_sk' field.
   * @param value the value to set.
   */
  public void setWsShipModeSk(java.lang.Integer value) {
    this.ws_ship_mode_sk = value;
  }

  /**
   * Gets the value of the 'ws_warehouse_sk' field.
   */
  public java.lang.Integer getWsWarehouseSk() {
    return ws_warehouse_sk;
  }

  /**
   * Sets the value of the 'ws_warehouse_sk' field.
   * @param value the value to set.
   */
  public void setWsWarehouseSk(java.lang.Integer value) {
    this.ws_warehouse_sk = value;
  }

  /**
   * Gets the value of the 'ws_promo_sk' field.
   */
  public java.lang.Integer getWsPromoSk() {
    return ws_promo_sk;
  }

  /**
   * Sets the value of the 'ws_promo_sk' field.
   * @param value the value to set.
   */
  public void setWsPromoSk(java.lang.Integer value) {
    this.ws_promo_sk = value;
  }

  /**
   * Gets the value of the 'ws_order_number' field.
   */
  public java.lang.Integer getWsOrderNumber() {
    return ws_order_number;
  }

  /**
   * Sets the value of the 'ws_order_number' field.
   * @param value the value to set.
   */
  public void setWsOrderNumber(java.lang.Integer value) {
    this.ws_order_number = value;
  }

  /**
   * Gets the value of the 'ws_quantity' field.
   */
  public java.lang.Integer getWsQuantity() {
    return ws_quantity;
  }

  /**
   * Sets the value of the 'ws_quantity' field.
   * @param value the value to set.
   */
  public void setWsQuantity(java.lang.Integer value) {
    this.ws_quantity = value;
  }

  /**
   * Gets the value of the 'ws_wholesale_cost' field.
   */
  public java.lang.Float getWsWholesaleCost() {
    return ws_wholesale_cost;
  }

  /**
   * Sets the value of the 'ws_wholesale_cost' field.
   * @param value the value to set.
   */
  public void setWsWholesaleCost(java.lang.Float value) {
    this.ws_wholesale_cost = value;
  }

  /**
   * Gets the value of the 'ws_list_price' field.
   */
  public java.lang.Float getWsListPrice() {
    return ws_list_price;
  }

  /**
   * Sets the value of the 'ws_list_price' field.
   * @param value the value to set.
   */
  public void setWsListPrice(java.lang.Float value) {
    this.ws_list_price = value;
  }

  /**
   * Gets the value of the 'ws_sales_price' field.
   */
  public java.lang.Float getWsSalesPrice() {
    return ws_sales_price;
  }

  /**
   * Sets the value of the 'ws_sales_price' field.
   * @param value the value to set.
   */
  public void setWsSalesPrice(java.lang.Float value) {
    this.ws_sales_price = value;
  }

  /**
   * Gets the value of the 'ws_ext_discount_amt' field.
   */
  public java.lang.Float getWsExtDiscountAmt() {
    return ws_ext_discount_amt;
  }

  /**
   * Sets the value of the 'ws_ext_discount_amt' field.
   * @param value the value to set.
   */
  public void setWsExtDiscountAmt(java.lang.Float value) {
    this.ws_ext_discount_amt = value;
  }

  /**
   * Gets the value of the 'ws_ext_sales_price' field.
   */
  public java.lang.Float getWsExtSalesPrice() {
    return ws_ext_sales_price;
  }

  /**
   * Sets the value of the 'ws_ext_sales_price' field.
   * @param value the value to set.
   */
  public void setWsExtSalesPrice(java.lang.Float value) {
    this.ws_ext_sales_price = value;
  }

  /**
   * Gets the value of the 'ws_ext_wholesale_cost' field.
   */
  public java.lang.Float getWsExtWholesaleCost() {
    return ws_ext_wholesale_cost;
  }

  /**
   * Sets the value of the 'ws_ext_wholesale_cost' field.
   * @param value the value to set.
   */
  public void setWsExtWholesaleCost(java.lang.Float value) {
    this.ws_ext_wholesale_cost = value;
  }

  /**
   * Gets the value of the 'ws_ext_list_price' field.
   */
  public java.lang.Float getWsExtListPrice() {
    return ws_ext_list_price;
  }

  /**
   * Sets the value of the 'ws_ext_list_price' field.
   * @param value the value to set.
   */
  public void setWsExtListPrice(java.lang.Float value) {
    this.ws_ext_list_price = value;
  }

  /**
   * Gets the value of the 'ws_ext_tax' field.
   */
  public java.lang.Float getWsExtTax() {
    return ws_ext_tax;
  }

  /**
   * Sets the value of the 'ws_ext_tax' field.
   * @param value the value to set.
   */
  public void setWsExtTax(java.lang.Float value) {
    this.ws_ext_tax = value;
  }

  /**
   * Gets the value of the 'ws_coupon_amt' field.
   */
  public java.lang.Float getWsCouponAmt() {
    return ws_coupon_amt;
  }

  /**
   * Sets the value of the 'ws_coupon_amt' field.
   * @param value the value to set.
   */
  public void setWsCouponAmt(java.lang.Float value) {
    this.ws_coupon_amt = value;
  }

  /**
   * Gets the value of the 'ws_ext_ship_cost' field.
   */
  public java.lang.Float getWsExtShipCost() {
    return ws_ext_ship_cost;
  }

  /**
   * Sets the value of the 'ws_ext_ship_cost' field.
   * @param value the value to set.
   */
  public void setWsExtShipCost(java.lang.Float value) {
    this.ws_ext_ship_cost = value;
  }

  /**
   * Gets the value of the 'ws_net_paid' field.
   */
  public java.lang.Float getWsNetPaid() {
    return ws_net_paid;
  }

  /**
   * Sets the value of the 'ws_net_paid' field.
   * @param value the value to set.
   */
  public void setWsNetPaid(java.lang.Float value) {
    this.ws_net_paid = value;
  }

  /**
   * Gets the value of the 'ws_net_paid_inc_tax' field.
   */
  public java.lang.Float getWsNetPaidIncTax() {
    return ws_net_paid_inc_tax;
  }

  /**
   * Sets the value of the 'ws_net_paid_inc_tax' field.
   * @param value the value to set.
   */
  public void setWsNetPaidIncTax(java.lang.Float value) {
    this.ws_net_paid_inc_tax = value;
  }

  /**
   * Gets the value of the 'ws_net_paid_inc_ship' field.
   */
  public java.lang.Float getWsNetPaidIncShip() {
    return ws_net_paid_inc_ship;
  }

  /**
   * Sets the value of the 'ws_net_paid_inc_ship' field.
   * @param value the value to set.
   */
  public void setWsNetPaidIncShip(java.lang.Float value) {
    this.ws_net_paid_inc_ship = value;
  }

  /**
   * Gets the value of the 'ws_net_paid_inc_ship_tax' field.
   */
  public java.lang.Float getWsNetPaidIncShipTax() {
    return ws_net_paid_inc_ship_tax;
  }

  /**
   * Sets the value of the 'ws_net_paid_inc_ship_tax' field.
   * @param value the value to set.
   */
  public void setWsNetPaidIncShipTax(java.lang.Float value) {
    this.ws_net_paid_inc_ship_tax = value;
  }

  /**
   * Gets the value of the 'ws_net_profit' field.
   */
  public java.lang.Float getWsNetProfit() {
    return ws_net_profit;
  }

  /**
   * Sets the value of the 'ws_net_profit' field.
   * @param value the value to set.
   */
  public void setWsNetProfit(java.lang.Float value) {
    this.ws_net_profit = value;
  }

  /** Creates a new Web_Sales RecordBuilder */
  public static bigframe.avro.Web_Sales.Builder newBuilder() {
    return new bigframe.avro.Web_Sales.Builder();
  }
  
  /** Creates a new Web_Sales RecordBuilder by copying an existing Builder */
  public static bigframe.avro.Web_Sales.Builder newBuilder(bigframe.avro.Web_Sales.Builder other) {
    return new bigframe.avro.Web_Sales.Builder(other);
  }
  
  /** Creates a new Web_Sales RecordBuilder by copying an existing Web_Sales instance */
  public static bigframe.avro.Web_Sales.Builder newBuilder(bigframe.avro.Web_Sales other) {
    return new bigframe.avro.Web_Sales.Builder(other);
  }
  
  /**
   * RecordBuilder for Web_Sales instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Web_Sales>
    implements org.apache.avro.data.RecordBuilder<Web_Sales> {

    private int ws_sold_date_sk;
    private int ws_sold_time_sk;
    private int ws_ship_date_sk;
    private int ws_item_sk;
    private int ws_bill_customer_sk;
    private int ws_bill_cdemo_sk;
    private int ws_bill_hdemo_sk;
    private int ws_bill_addr_sk;
    private int ws_ship_customer_sk;
    private int ws_ship_cdemo_sk;
    private int ws_ship_hdemo_sk;
    private int ws_ship_addr_sk;
    private int ws_web_page_sk;
    private int ws_web_site_sk;
    private int ws_ship_mode_sk;
    private int ws_warehouse_sk;
    private int ws_promo_sk;
    private int ws_order_number;
    private int ws_quantity;
    private float ws_wholesale_cost;
    private float ws_list_price;
    private float ws_sales_price;
    private float ws_ext_discount_amt;
    private float ws_ext_sales_price;
    private float ws_ext_wholesale_cost;
    private float ws_ext_list_price;
    private float ws_ext_tax;
    private float ws_coupon_amt;
    private float ws_ext_ship_cost;
    private float ws_net_paid;
    private float ws_net_paid_inc_tax;
    private float ws_net_paid_inc_ship;
    private float ws_net_paid_inc_ship_tax;
    private float ws_net_profit;

    /** Creates a new Builder */
    private Builder() {
      super(bigframe.avro.Web_Sales.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(bigframe.avro.Web_Sales.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Web_Sales instance */
    private Builder(bigframe.avro.Web_Sales other) {
            super(bigframe.avro.Web_Sales.SCHEMA$);
      if (isValidValue(fields()[0], other.ws_sold_date_sk)) {
        this.ws_sold_date_sk = data().deepCopy(fields()[0].schema(), other.ws_sold_date_sk);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ws_sold_time_sk)) {
        this.ws_sold_time_sk = data().deepCopy(fields()[1].schema(), other.ws_sold_time_sk);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ws_ship_date_sk)) {
        this.ws_ship_date_sk = data().deepCopy(fields()[2].schema(), other.ws_ship_date_sk);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ws_item_sk)) {
        this.ws_item_sk = data().deepCopy(fields()[3].schema(), other.ws_item_sk);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ws_bill_customer_sk)) {
        this.ws_bill_customer_sk = data().deepCopy(fields()[4].schema(), other.ws_bill_customer_sk);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ws_bill_cdemo_sk)) {
        this.ws_bill_cdemo_sk = data().deepCopy(fields()[5].schema(), other.ws_bill_cdemo_sk);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ws_bill_hdemo_sk)) {
        this.ws_bill_hdemo_sk = data().deepCopy(fields()[6].schema(), other.ws_bill_hdemo_sk);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ws_bill_addr_sk)) {
        this.ws_bill_addr_sk = data().deepCopy(fields()[7].schema(), other.ws_bill_addr_sk);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ws_ship_customer_sk)) {
        this.ws_ship_customer_sk = data().deepCopy(fields()[8].schema(), other.ws_ship_customer_sk);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ws_ship_cdemo_sk)) {
        this.ws_ship_cdemo_sk = data().deepCopy(fields()[9].schema(), other.ws_ship_cdemo_sk);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ws_ship_hdemo_sk)) {
        this.ws_ship_hdemo_sk = data().deepCopy(fields()[10].schema(), other.ws_ship_hdemo_sk);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ws_ship_addr_sk)) {
        this.ws_ship_addr_sk = data().deepCopy(fields()[11].schema(), other.ws_ship_addr_sk);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ws_web_page_sk)) {
        this.ws_web_page_sk = data().deepCopy(fields()[12].schema(), other.ws_web_page_sk);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ws_web_site_sk)) {
        this.ws_web_site_sk = data().deepCopy(fields()[13].schema(), other.ws_web_site_sk);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.ws_ship_mode_sk)) {
        this.ws_ship_mode_sk = data().deepCopy(fields()[14].schema(), other.ws_ship_mode_sk);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.ws_warehouse_sk)) {
        this.ws_warehouse_sk = data().deepCopy(fields()[15].schema(), other.ws_warehouse_sk);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.ws_promo_sk)) {
        this.ws_promo_sk = data().deepCopy(fields()[16].schema(), other.ws_promo_sk);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.ws_order_number)) {
        this.ws_order_number = data().deepCopy(fields()[17].schema(), other.ws_order_number);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.ws_quantity)) {
        this.ws_quantity = data().deepCopy(fields()[18].schema(), other.ws_quantity);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.ws_wholesale_cost)) {
        this.ws_wholesale_cost = data().deepCopy(fields()[19].schema(), other.ws_wholesale_cost);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.ws_list_price)) {
        this.ws_list_price = data().deepCopy(fields()[20].schema(), other.ws_list_price);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.ws_sales_price)) {
        this.ws_sales_price = data().deepCopy(fields()[21].schema(), other.ws_sales_price);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.ws_ext_discount_amt)) {
        this.ws_ext_discount_amt = data().deepCopy(fields()[22].schema(), other.ws_ext_discount_amt);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.ws_ext_sales_price)) {
        this.ws_ext_sales_price = data().deepCopy(fields()[23].schema(), other.ws_ext_sales_price);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.ws_ext_wholesale_cost)) {
        this.ws_ext_wholesale_cost = data().deepCopy(fields()[24].schema(), other.ws_ext_wholesale_cost);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.ws_ext_list_price)) {
        this.ws_ext_list_price = data().deepCopy(fields()[25].schema(), other.ws_ext_list_price);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.ws_ext_tax)) {
        this.ws_ext_tax = data().deepCopy(fields()[26].schema(), other.ws_ext_tax);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.ws_coupon_amt)) {
        this.ws_coupon_amt = data().deepCopy(fields()[27].schema(), other.ws_coupon_amt);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.ws_ext_ship_cost)) {
        this.ws_ext_ship_cost = data().deepCopy(fields()[28].schema(), other.ws_ext_ship_cost);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.ws_net_paid)) {
        this.ws_net_paid = data().deepCopy(fields()[29].schema(), other.ws_net_paid);
        fieldSetFlags()[29] = true;
      }
      if (isValidValue(fields()[30], other.ws_net_paid_inc_tax)) {
        this.ws_net_paid_inc_tax = data().deepCopy(fields()[30].schema(), other.ws_net_paid_inc_tax);
        fieldSetFlags()[30] = true;
      }
      if (isValidValue(fields()[31], other.ws_net_paid_inc_ship)) {
        this.ws_net_paid_inc_ship = data().deepCopy(fields()[31].schema(), other.ws_net_paid_inc_ship);
        fieldSetFlags()[31] = true;
      }
      if (isValidValue(fields()[32], other.ws_net_paid_inc_ship_tax)) {
        this.ws_net_paid_inc_ship_tax = data().deepCopy(fields()[32].schema(), other.ws_net_paid_inc_ship_tax);
        fieldSetFlags()[32] = true;
      }
      if (isValidValue(fields()[33], other.ws_net_profit)) {
        this.ws_net_profit = data().deepCopy(fields()[33].schema(), other.ws_net_profit);
        fieldSetFlags()[33] = true;
      }
    }

    /** Gets the value of the 'ws_sold_date_sk' field */
    public java.lang.Integer getWsSoldDateSk() {
      return ws_sold_date_sk;
    }
    
    /** Sets the value of the 'ws_sold_date_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsSoldDateSk(int value) {
      validate(fields()[0], value);
      this.ws_sold_date_sk = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_sold_date_sk' field has been set */
    public boolean hasWsSoldDateSk() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'ws_sold_date_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsSoldDateSk() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'ws_sold_time_sk' field */
    public java.lang.Integer getWsSoldTimeSk() {
      return ws_sold_time_sk;
    }
    
    /** Sets the value of the 'ws_sold_time_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsSoldTimeSk(int value) {
      validate(fields()[1], value);
      this.ws_sold_time_sk = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_sold_time_sk' field has been set */
    public boolean hasWsSoldTimeSk() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'ws_sold_time_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsSoldTimeSk() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'ws_ship_date_sk' field */
    public java.lang.Integer getWsShipDateSk() {
      return ws_ship_date_sk;
    }
    
    /** Sets the value of the 'ws_ship_date_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsShipDateSk(int value) {
      validate(fields()[2], value);
      this.ws_ship_date_sk = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ship_date_sk' field has been set */
    public boolean hasWsShipDateSk() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'ws_ship_date_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsShipDateSk() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ws_item_sk' field */
    public java.lang.Integer getWsItemSk() {
      return ws_item_sk;
    }
    
    /** Sets the value of the 'ws_item_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsItemSk(int value) {
      validate(fields()[3], value);
      this.ws_item_sk = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_item_sk' field has been set */
    public boolean hasWsItemSk() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ws_item_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsItemSk() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'ws_bill_customer_sk' field */
    public java.lang.Integer getWsBillCustomerSk() {
      return ws_bill_customer_sk;
    }
    
    /** Sets the value of the 'ws_bill_customer_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsBillCustomerSk(int value) {
      validate(fields()[4], value);
      this.ws_bill_customer_sk = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_bill_customer_sk' field has been set */
    public boolean hasWsBillCustomerSk() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'ws_bill_customer_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsBillCustomerSk() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'ws_bill_cdemo_sk' field */
    public java.lang.Integer getWsBillCdemoSk() {
      return ws_bill_cdemo_sk;
    }
    
    /** Sets the value of the 'ws_bill_cdemo_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsBillCdemoSk(int value) {
      validate(fields()[5], value);
      this.ws_bill_cdemo_sk = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_bill_cdemo_sk' field has been set */
    public boolean hasWsBillCdemoSk() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'ws_bill_cdemo_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsBillCdemoSk() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'ws_bill_hdemo_sk' field */
    public java.lang.Integer getWsBillHdemoSk() {
      return ws_bill_hdemo_sk;
    }
    
    /** Sets the value of the 'ws_bill_hdemo_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsBillHdemoSk(int value) {
      validate(fields()[6], value);
      this.ws_bill_hdemo_sk = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_bill_hdemo_sk' field has been set */
    public boolean hasWsBillHdemoSk() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'ws_bill_hdemo_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsBillHdemoSk() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'ws_bill_addr_sk' field */
    public java.lang.Integer getWsBillAddrSk() {
      return ws_bill_addr_sk;
    }
    
    /** Sets the value of the 'ws_bill_addr_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsBillAddrSk(int value) {
      validate(fields()[7], value);
      this.ws_bill_addr_sk = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_bill_addr_sk' field has been set */
    public boolean hasWsBillAddrSk() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'ws_bill_addr_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsBillAddrSk() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'ws_ship_customer_sk' field */
    public java.lang.Integer getWsShipCustomerSk() {
      return ws_ship_customer_sk;
    }
    
    /** Sets the value of the 'ws_ship_customer_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsShipCustomerSk(int value) {
      validate(fields()[8], value);
      this.ws_ship_customer_sk = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ship_customer_sk' field has been set */
    public boolean hasWsShipCustomerSk() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'ws_ship_customer_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsShipCustomerSk() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'ws_ship_cdemo_sk' field */
    public java.lang.Integer getWsShipCdemoSk() {
      return ws_ship_cdemo_sk;
    }
    
    /** Sets the value of the 'ws_ship_cdemo_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsShipCdemoSk(int value) {
      validate(fields()[9], value);
      this.ws_ship_cdemo_sk = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ship_cdemo_sk' field has been set */
    public boolean hasWsShipCdemoSk() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'ws_ship_cdemo_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsShipCdemoSk() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'ws_ship_hdemo_sk' field */
    public java.lang.Integer getWsShipHdemoSk() {
      return ws_ship_hdemo_sk;
    }
    
    /** Sets the value of the 'ws_ship_hdemo_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsShipHdemoSk(int value) {
      validate(fields()[10], value);
      this.ws_ship_hdemo_sk = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ship_hdemo_sk' field has been set */
    public boolean hasWsShipHdemoSk() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'ws_ship_hdemo_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsShipHdemoSk() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'ws_ship_addr_sk' field */
    public java.lang.Integer getWsShipAddrSk() {
      return ws_ship_addr_sk;
    }
    
    /** Sets the value of the 'ws_ship_addr_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsShipAddrSk(int value) {
      validate(fields()[11], value);
      this.ws_ship_addr_sk = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ship_addr_sk' field has been set */
    public boolean hasWsShipAddrSk() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'ws_ship_addr_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsShipAddrSk() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'ws_web_page_sk' field */
    public java.lang.Integer getWsWebPageSk() {
      return ws_web_page_sk;
    }
    
    /** Sets the value of the 'ws_web_page_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsWebPageSk(int value) {
      validate(fields()[12], value);
      this.ws_web_page_sk = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_web_page_sk' field has been set */
    public boolean hasWsWebPageSk() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'ws_web_page_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsWebPageSk() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'ws_web_site_sk' field */
    public java.lang.Integer getWsWebSiteSk() {
      return ws_web_site_sk;
    }
    
    /** Sets the value of the 'ws_web_site_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsWebSiteSk(int value) {
      validate(fields()[13], value);
      this.ws_web_site_sk = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_web_site_sk' field has been set */
    public boolean hasWsWebSiteSk() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'ws_web_site_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsWebSiteSk() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'ws_ship_mode_sk' field */
    public java.lang.Integer getWsShipModeSk() {
      return ws_ship_mode_sk;
    }
    
    /** Sets the value of the 'ws_ship_mode_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsShipModeSk(int value) {
      validate(fields()[14], value);
      this.ws_ship_mode_sk = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ship_mode_sk' field has been set */
    public boolean hasWsShipModeSk() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'ws_ship_mode_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsShipModeSk() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'ws_warehouse_sk' field */
    public java.lang.Integer getWsWarehouseSk() {
      return ws_warehouse_sk;
    }
    
    /** Sets the value of the 'ws_warehouse_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsWarehouseSk(int value) {
      validate(fields()[15], value);
      this.ws_warehouse_sk = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_warehouse_sk' field has been set */
    public boolean hasWsWarehouseSk() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'ws_warehouse_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsWarehouseSk() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'ws_promo_sk' field */
    public java.lang.Integer getWsPromoSk() {
      return ws_promo_sk;
    }
    
    /** Sets the value of the 'ws_promo_sk' field */
    public bigframe.avro.Web_Sales.Builder setWsPromoSk(int value) {
      validate(fields()[16], value);
      this.ws_promo_sk = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_promo_sk' field has been set */
    public boolean hasWsPromoSk() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'ws_promo_sk' field */
    public bigframe.avro.Web_Sales.Builder clearWsPromoSk() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'ws_order_number' field */
    public java.lang.Integer getWsOrderNumber() {
      return ws_order_number;
    }
    
    /** Sets the value of the 'ws_order_number' field */
    public bigframe.avro.Web_Sales.Builder setWsOrderNumber(int value) {
      validate(fields()[17], value);
      this.ws_order_number = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_order_number' field has been set */
    public boolean hasWsOrderNumber() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'ws_order_number' field */
    public bigframe.avro.Web_Sales.Builder clearWsOrderNumber() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'ws_quantity' field */
    public java.lang.Integer getWsQuantity() {
      return ws_quantity;
    }
    
    /** Sets the value of the 'ws_quantity' field */
    public bigframe.avro.Web_Sales.Builder setWsQuantity(int value) {
      validate(fields()[18], value);
      this.ws_quantity = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_quantity' field has been set */
    public boolean hasWsQuantity() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'ws_quantity' field */
    public bigframe.avro.Web_Sales.Builder clearWsQuantity() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'ws_wholesale_cost' field */
    public java.lang.Float getWsWholesaleCost() {
      return ws_wholesale_cost;
    }
    
    /** Sets the value of the 'ws_wholesale_cost' field */
    public bigframe.avro.Web_Sales.Builder setWsWholesaleCost(float value) {
      validate(fields()[19], value);
      this.ws_wholesale_cost = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_wholesale_cost' field has been set */
    public boolean hasWsWholesaleCost() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'ws_wholesale_cost' field */
    public bigframe.avro.Web_Sales.Builder clearWsWholesaleCost() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'ws_list_price' field */
    public java.lang.Float getWsListPrice() {
      return ws_list_price;
    }
    
    /** Sets the value of the 'ws_list_price' field */
    public bigframe.avro.Web_Sales.Builder setWsListPrice(float value) {
      validate(fields()[20], value);
      this.ws_list_price = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_list_price' field has been set */
    public boolean hasWsListPrice() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'ws_list_price' field */
    public bigframe.avro.Web_Sales.Builder clearWsListPrice() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'ws_sales_price' field */
    public java.lang.Float getWsSalesPrice() {
      return ws_sales_price;
    }
    
    /** Sets the value of the 'ws_sales_price' field */
    public bigframe.avro.Web_Sales.Builder setWsSalesPrice(float value) {
      validate(fields()[21], value);
      this.ws_sales_price = value;
      fieldSetFlags()[21] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_sales_price' field has been set */
    public boolean hasWsSalesPrice() {
      return fieldSetFlags()[21];
    }
    
    /** Clears the value of the 'ws_sales_price' field */
    public bigframe.avro.Web_Sales.Builder clearWsSalesPrice() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /** Gets the value of the 'ws_ext_discount_amt' field */
    public java.lang.Float getWsExtDiscountAmt() {
      return ws_ext_discount_amt;
    }
    
    /** Sets the value of the 'ws_ext_discount_amt' field */
    public bigframe.avro.Web_Sales.Builder setWsExtDiscountAmt(float value) {
      validate(fields()[22], value);
      this.ws_ext_discount_amt = value;
      fieldSetFlags()[22] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ext_discount_amt' field has been set */
    public boolean hasWsExtDiscountAmt() {
      return fieldSetFlags()[22];
    }
    
    /** Clears the value of the 'ws_ext_discount_amt' field */
    public bigframe.avro.Web_Sales.Builder clearWsExtDiscountAmt() {
      fieldSetFlags()[22] = false;
      return this;
    }

    /** Gets the value of the 'ws_ext_sales_price' field */
    public java.lang.Float getWsExtSalesPrice() {
      return ws_ext_sales_price;
    }
    
    /** Sets the value of the 'ws_ext_sales_price' field */
    public bigframe.avro.Web_Sales.Builder setWsExtSalesPrice(float value) {
      validate(fields()[23], value);
      this.ws_ext_sales_price = value;
      fieldSetFlags()[23] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ext_sales_price' field has been set */
    public boolean hasWsExtSalesPrice() {
      return fieldSetFlags()[23];
    }
    
    /** Clears the value of the 'ws_ext_sales_price' field */
    public bigframe.avro.Web_Sales.Builder clearWsExtSalesPrice() {
      fieldSetFlags()[23] = false;
      return this;
    }

    /** Gets the value of the 'ws_ext_wholesale_cost' field */
    public java.lang.Float getWsExtWholesaleCost() {
      return ws_ext_wholesale_cost;
    }
    
    /** Sets the value of the 'ws_ext_wholesale_cost' field */
    public bigframe.avro.Web_Sales.Builder setWsExtWholesaleCost(float value) {
      validate(fields()[24], value);
      this.ws_ext_wholesale_cost = value;
      fieldSetFlags()[24] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ext_wholesale_cost' field has been set */
    public boolean hasWsExtWholesaleCost() {
      return fieldSetFlags()[24];
    }
    
    /** Clears the value of the 'ws_ext_wholesale_cost' field */
    public bigframe.avro.Web_Sales.Builder clearWsExtWholesaleCost() {
      fieldSetFlags()[24] = false;
      return this;
    }

    /** Gets the value of the 'ws_ext_list_price' field */
    public java.lang.Float getWsExtListPrice() {
      return ws_ext_list_price;
    }
    
    /** Sets the value of the 'ws_ext_list_price' field */
    public bigframe.avro.Web_Sales.Builder setWsExtListPrice(float value) {
      validate(fields()[25], value);
      this.ws_ext_list_price = value;
      fieldSetFlags()[25] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ext_list_price' field has been set */
    public boolean hasWsExtListPrice() {
      return fieldSetFlags()[25];
    }
    
    /** Clears the value of the 'ws_ext_list_price' field */
    public bigframe.avro.Web_Sales.Builder clearWsExtListPrice() {
      fieldSetFlags()[25] = false;
      return this;
    }

    /** Gets the value of the 'ws_ext_tax' field */
    public java.lang.Float getWsExtTax() {
      return ws_ext_tax;
    }
    
    /** Sets the value of the 'ws_ext_tax' field */
    public bigframe.avro.Web_Sales.Builder setWsExtTax(float value) {
      validate(fields()[26], value);
      this.ws_ext_tax = value;
      fieldSetFlags()[26] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ext_tax' field has been set */
    public boolean hasWsExtTax() {
      return fieldSetFlags()[26];
    }
    
    /** Clears the value of the 'ws_ext_tax' field */
    public bigframe.avro.Web_Sales.Builder clearWsExtTax() {
      fieldSetFlags()[26] = false;
      return this;
    }

    /** Gets the value of the 'ws_coupon_amt' field */
    public java.lang.Float getWsCouponAmt() {
      return ws_coupon_amt;
    }
    
    /** Sets the value of the 'ws_coupon_amt' field */
    public bigframe.avro.Web_Sales.Builder setWsCouponAmt(float value) {
      validate(fields()[27], value);
      this.ws_coupon_amt = value;
      fieldSetFlags()[27] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_coupon_amt' field has been set */
    public boolean hasWsCouponAmt() {
      return fieldSetFlags()[27];
    }
    
    /** Clears the value of the 'ws_coupon_amt' field */
    public bigframe.avro.Web_Sales.Builder clearWsCouponAmt() {
      fieldSetFlags()[27] = false;
      return this;
    }

    /** Gets the value of the 'ws_ext_ship_cost' field */
    public java.lang.Float getWsExtShipCost() {
      return ws_ext_ship_cost;
    }
    
    /** Sets the value of the 'ws_ext_ship_cost' field */
    public bigframe.avro.Web_Sales.Builder setWsExtShipCost(float value) {
      validate(fields()[28], value);
      this.ws_ext_ship_cost = value;
      fieldSetFlags()[28] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_ext_ship_cost' field has been set */
    public boolean hasWsExtShipCost() {
      return fieldSetFlags()[28];
    }
    
    /** Clears the value of the 'ws_ext_ship_cost' field */
    public bigframe.avro.Web_Sales.Builder clearWsExtShipCost() {
      fieldSetFlags()[28] = false;
      return this;
    }

    /** Gets the value of the 'ws_net_paid' field */
    public java.lang.Float getWsNetPaid() {
      return ws_net_paid;
    }
    
    /** Sets the value of the 'ws_net_paid' field */
    public bigframe.avro.Web_Sales.Builder setWsNetPaid(float value) {
      validate(fields()[29], value);
      this.ws_net_paid = value;
      fieldSetFlags()[29] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_net_paid' field has been set */
    public boolean hasWsNetPaid() {
      return fieldSetFlags()[29];
    }
    
    /** Clears the value of the 'ws_net_paid' field */
    public bigframe.avro.Web_Sales.Builder clearWsNetPaid() {
      fieldSetFlags()[29] = false;
      return this;
    }

    /** Gets the value of the 'ws_net_paid_inc_tax' field */
    public java.lang.Float getWsNetPaidIncTax() {
      return ws_net_paid_inc_tax;
    }
    
    /** Sets the value of the 'ws_net_paid_inc_tax' field */
    public bigframe.avro.Web_Sales.Builder setWsNetPaidIncTax(float value) {
      validate(fields()[30], value);
      this.ws_net_paid_inc_tax = value;
      fieldSetFlags()[30] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_net_paid_inc_tax' field has been set */
    public boolean hasWsNetPaidIncTax() {
      return fieldSetFlags()[30];
    }
    
    /** Clears the value of the 'ws_net_paid_inc_tax' field */
    public bigframe.avro.Web_Sales.Builder clearWsNetPaidIncTax() {
      fieldSetFlags()[30] = false;
      return this;
    }

    /** Gets the value of the 'ws_net_paid_inc_ship' field */
    public java.lang.Float getWsNetPaidIncShip() {
      return ws_net_paid_inc_ship;
    }
    
    /** Sets the value of the 'ws_net_paid_inc_ship' field */
    public bigframe.avro.Web_Sales.Builder setWsNetPaidIncShip(float value) {
      validate(fields()[31], value);
      this.ws_net_paid_inc_ship = value;
      fieldSetFlags()[31] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_net_paid_inc_ship' field has been set */
    public boolean hasWsNetPaidIncShip() {
      return fieldSetFlags()[31];
    }
    
    /** Clears the value of the 'ws_net_paid_inc_ship' field */
    public bigframe.avro.Web_Sales.Builder clearWsNetPaidIncShip() {
      fieldSetFlags()[31] = false;
      return this;
    }

    /** Gets the value of the 'ws_net_paid_inc_ship_tax' field */
    public java.lang.Float getWsNetPaidIncShipTax() {
      return ws_net_paid_inc_ship_tax;
    }
    
    /** Sets the value of the 'ws_net_paid_inc_ship_tax' field */
    public bigframe.avro.Web_Sales.Builder setWsNetPaidIncShipTax(float value) {
      validate(fields()[32], value);
      this.ws_net_paid_inc_ship_tax = value;
      fieldSetFlags()[32] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_net_paid_inc_ship_tax' field has been set */
    public boolean hasWsNetPaidIncShipTax() {
      return fieldSetFlags()[32];
    }
    
    /** Clears the value of the 'ws_net_paid_inc_ship_tax' field */
    public bigframe.avro.Web_Sales.Builder clearWsNetPaidIncShipTax() {
      fieldSetFlags()[32] = false;
      return this;
    }

    /** Gets the value of the 'ws_net_profit' field */
    public java.lang.Float getWsNetProfit() {
      return ws_net_profit;
    }
    
    /** Sets the value of the 'ws_net_profit' field */
    public bigframe.avro.Web_Sales.Builder setWsNetProfit(float value) {
      validate(fields()[33], value);
      this.ws_net_profit = value;
      fieldSetFlags()[33] = true;
      return this; 
    }
    
    /** Checks whether the 'ws_net_profit' field has been set */
    public boolean hasWsNetProfit() {
      return fieldSetFlags()[33];
    }
    
    /** Clears the value of the 'ws_net_profit' field */
    public bigframe.avro.Web_Sales.Builder clearWsNetProfit() {
      fieldSetFlags()[33] = false;
      return this;
    }

    @Override
    public Web_Sales build() {
      try {
        Web_Sales record = new Web_Sales();
        record.ws_sold_date_sk = fieldSetFlags()[0] ? this.ws_sold_date_sk : (java.lang.Integer) defaultValue(fields()[0]);
        record.ws_sold_time_sk = fieldSetFlags()[1] ? this.ws_sold_time_sk : (java.lang.Integer) defaultValue(fields()[1]);
        record.ws_ship_date_sk = fieldSetFlags()[2] ? this.ws_ship_date_sk : (java.lang.Integer) defaultValue(fields()[2]);
        record.ws_item_sk = fieldSetFlags()[3] ? this.ws_item_sk : (java.lang.Integer) defaultValue(fields()[3]);
        record.ws_bill_customer_sk = fieldSetFlags()[4] ? this.ws_bill_customer_sk : (java.lang.Integer) defaultValue(fields()[4]);
        record.ws_bill_cdemo_sk = fieldSetFlags()[5] ? this.ws_bill_cdemo_sk : (java.lang.Integer) defaultValue(fields()[5]);
        record.ws_bill_hdemo_sk = fieldSetFlags()[6] ? this.ws_bill_hdemo_sk : (java.lang.Integer) defaultValue(fields()[6]);
        record.ws_bill_addr_sk = fieldSetFlags()[7] ? this.ws_bill_addr_sk : (java.lang.Integer) defaultValue(fields()[7]);
        record.ws_ship_customer_sk = fieldSetFlags()[8] ? this.ws_ship_customer_sk : (java.lang.Integer) defaultValue(fields()[8]);
        record.ws_ship_cdemo_sk = fieldSetFlags()[9] ? this.ws_ship_cdemo_sk : (java.lang.Integer) defaultValue(fields()[9]);
        record.ws_ship_hdemo_sk = fieldSetFlags()[10] ? this.ws_ship_hdemo_sk : (java.lang.Integer) defaultValue(fields()[10]);
        record.ws_ship_addr_sk = fieldSetFlags()[11] ? this.ws_ship_addr_sk : (java.lang.Integer) defaultValue(fields()[11]);
        record.ws_web_page_sk = fieldSetFlags()[12] ? this.ws_web_page_sk : (java.lang.Integer) defaultValue(fields()[12]);
        record.ws_web_site_sk = fieldSetFlags()[13] ? this.ws_web_site_sk : (java.lang.Integer) defaultValue(fields()[13]);
        record.ws_ship_mode_sk = fieldSetFlags()[14] ? this.ws_ship_mode_sk : (java.lang.Integer) defaultValue(fields()[14]);
        record.ws_warehouse_sk = fieldSetFlags()[15] ? this.ws_warehouse_sk : (java.lang.Integer) defaultValue(fields()[15]);
        record.ws_promo_sk = fieldSetFlags()[16] ? this.ws_promo_sk : (java.lang.Integer) defaultValue(fields()[16]);
        record.ws_order_number = fieldSetFlags()[17] ? this.ws_order_number : (java.lang.Integer) defaultValue(fields()[17]);
        record.ws_quantity = fieldSetFlags()[18] ? this.ws_quantity : (java.lang.Integer) defaultValue(fields()[18]);
        record.ws_wholesale_cost = fieldSetFlags()[19] ? this.ws_wholesale_cost : (java.lang.Float) defaultValue(fields()[19]);
        record.ws_list_price = fieldSetFlags()[20] ? this.ws_list_price : (java.lang.Float) defaultValue(fields()[20]);
        record.ws_sales_price = fieldSetFlags()[21] ? this.ws_sales_price : (java.lang.Float) defaultValue(fields()[21]);
        record.ws_ext_discount_amt = fieldSetFlags()[22] ? this.ws_ext_discount_amt : (java.lang.Float) defaultValue(fields()[22]);
        record.ws_ext_sales_price = fieldSetFlags()[23] ? this.ws_ext_sales_price : (java.lang.Float) defaultValue(fields()[23]);
        record.ws_ext_wholesale_cost = fieldSetFlags()[24] ? this.ws_ext_wholesale_cost : (java.lang.Float) defaultValue(fields()[24]);
        record.ws_ext_list_price = fieldSetFlags()[25] ? this.ws_ext_list_price : (java.lang.Float) defaultValue(fields()[25]);
        record.ws_ext_tax = fieldSetFlags()[26] ? this.ws_ext_tax : (java.lang.Float) defaultValue(fields()[26]);
        record.ws_coupon_amt = fieldSetFlags()[27] ? this.ws_coupon_amt : (java.lang.Float) defaultValue(fields()[27]);
        record.ws_ext_ship_cost = fieldSetFlags()[28] ? this.ws_ext_ship_cost : (java.lang.Float) defaultValue(fields()[28]);
        record.ws_net_paid = fieldSetFlags()[29] ? this.ws_net_paid : (java.lang.Float) defaultValue(fields()[29]);
        record.ws_net_paid_inc_tax = fieldSetFlags()[30] ? this.ws_net_paid_inc_tax : (java.lang.Float) defaultValue(fields()[30]);
        record.ws_net_paid_inc_ship = fieldSetFlags()[31] ? this.ws_net_paid_inc_ship : (java.lang.Float) defaultValue(fields()[31]);
        record.ws_net_paid_inc_ship_tax = fieldSetFlags()[32] ? this.ws_net_paid_inc_ship_tax : (java.lang.Float) defaultValue(fields()[32]);
        record.ws_net_profit = fieldSetFlags()[33] ? this.ws_net_profit : (java.lang.Float) defaultValue(fields()[33]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
